// @vitest-environment node
import {createRequire} from 'node:module';
import {readdirSync,readFileSync} from 'node:fs';
import type {DatabaseSync as SqliteDatabase,SQLInputValue} from 'node:sqlite';
import {Hono} from 'hono';
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {socialHandles,unfollowCandidates,campaignMetrics} from '../shared/marketingPolicy';
import {publishMarketing,publishingError} from '../../cloudflare/workers/api/src/marketing';
import {storeSqlExport,purgeBackups} from '../../cloudflare/workers/api/src/backupStorage';
import {retentionCandidates,type BackupRun,type BackupSettings} from '../../cloudflare/workers/api/src/backups';
import type {Account} from '../../cloudflare/workers/api/src/accountVault';
import {centersRouter,communityRouter} from '../../cloudflare/workers/api/src/osCenters';
import {dashboardRouter} from '../../cloudflare/workers/api/src/osDashboard';
import type {Env} from '../../cloudflare/workers/api/src/types';
const {DatabaseSync}=createRequire(import.meta.url)('node:sqlite') as typeof import('node:sqlite');
class Statement {
 values:SQLInputValue[]=[];constructor(readonly db:SqliteDatabase,readonly sql:string){}
 bind(...v:SQLInputValue[]){this.values=v;return this;}
 async first(){return this.db.prepare(this.sql).get(...this.values)??null;}
 async all(){return {results:this.db.prepare(this.sql).all(...this.values)};}
 async run(){return {meta:this.db.prepare(this.sql).run(...this.values)};}
}
describe('Marketing, account vault and backup safety',()=>{
 let db:SqliteDatabase,app:Hono,actor:string,env:Env,kv:Map<string,string>,files:Map<string,Uint8Array>;
 beforeEach(()=>{
  db=new DatabaseSync(':memory:');for(const p of readdirSync('cloudflare/d1/migrations').filter(p=>p.endsWith('.sql')).sort())db.exec(readFileSync(`cloudflare/d1/migrations/${p}`,'utf8'));
  for(const [id,email,role] of [['owner','prometheus@avyron.ro','admin'],['staff','staff@example.test','staff'],['client','client@example.test','user']]){db.prepare('INSERT INTO users(id,email,password_hash,created_at,updated_at) VALUES (?,?,?,1,1)').run(id,email,'fixture');db.prepare('INSERT INTO user_roles VALUES (?,?)').run(id,role);}
  db.exec("INSERT INTO clients(id,company_name,email,created_at) VALUES ('c','Client One','c@example.test',1);INSERT INTO projects(id,client_id,name,slug,created_at) VALUES ('p','c','Project','project',1)");
  actor='owner';kv=new Map();files=new Map();env={DB:{prepare:(sql:string)=>new Statement(db,sql),batch:async(statements:Statement[])=>{db.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}},KV:{get:async(k:string)=>kv.get(k)||null,put:async(k:string,v:string)=>{kv.set(k,v);},delete:async(k:string)=>{kv.delete(k);}},FILES:{list:async()=>({objects:[]}),put:async(k:string,v:Uint8Array)=>{files.set(k,v);},delete:async(k:string)=>{files.delete(k);},get:async(k:string)=>files.has(k)?{body:files.get(k)}:null},MEDIA:{list:async()=>({objects:[]})},MFA_ENCRYPTION_KEY:'fixture-key-not-real-at-least-thirty-two',ADMIN_MFA_POLICY:'optional_until_enrollment'} as unknown as Env;
  app=new Hono();app.use('*',async(c,next)=>{Object.assign(c.env,env);c.set('userId',actor);c.set('roles',actor==='owner'?['admin']:actor==='staff'?['staff']:['user']);await next();});app.route('/',centersRouter);app.route('/',communityRouter);app.route('/',dashboardRouter);app.onError(e=>{console.error(e);return new Response('safe failure',{status:500});});
 });
 afterEach(()=>{db.close();vi.restoreAllMocks();});
 const req=(path:string,body?:unknown,method='POST',key=crypto.randomUUID())=>app.request(`/api/centers/${path}`,body===undefined?{}:{method,headers:{'content-type':'application/json','idempotency-key':key},body:JSON.stringify(body)},env);
 const accountBody={brand:'avyron',provider:'instagram',label:'Instagram test',auth_method:'oauth_token',login_url:'https://www.instagram.com/',external_id:'123456',api_version:'v26.0',expires_at:null};
 const campaignBody={brand:'avyron',name:'Autumn',strategy:'Education',audience:'Businesses',objective:'Qualified leads',currency:'RON',budget_minor:10000,status:'active',starts_at:null,ends_at:null};
 async function seed(){const a=await (await req('accounts',accountBody)).json(),c=await (await req('marketing/campaigns',campaignBody)).json();expect(a.id).toBeTruthy();expect(c.id).toBeTruthy();return {account:a.id,campaign:c.id};}
 const postBody=(ids:{account:string;campaign:string})=>({campaign_id:ids.campaign,account_id:ids.account,format:'feed',title:'Launch',caption:'A useful update',media_url:'https://avyron.ro/photo.jpg',media_kind:'image',criteria:'Useful information',creative_brief:'Image brief'});
 it('limits account access to platform owners and hides ciphertext references',async()=>{const {account}=await seed();await req(`accounts/${account}/secret`,{secret:'fixture-super-secret',revision:1},'PUT');expect([...kv.values()].join('')).not.toContain('fixture-super-secret');const listed=await(await req('accounts')).text();expect(listed).not.toContain('secret_reference');expect(listed).not.toContain('fixture-super-secret');expect((await req(`accounts/${account}/reveal`,{reason:'Access review'})).status).toBe(400);actor='staff';expect((await req('accounts')).status).toBe(403);expect((await req(`accounts/${account}/secret`,{secret:'new-token-value',revision:2},'PUT')).status).toBe(403);});
 it('rejects private login targets and identity changes',async()=>{expect((await req('accounts',{...accountBody,login_url:'http://localhost/'})).status).toBe(400);const {account}=await seed();expect((await req(`accounts/${account}`,{...accountBody,brand:'cutiutamagica',revision:1},'PATCH')).status).toBe(400);});
 it('encrypts passwords and records reasoned explicit reveal',async()=>{const {id}=await(await req('accounts',{...accountBody,auth_method:'password'})).json();await req(`accounts/${id}/secret`,{secret:'private-password',revision:1},'PUT');expect((await req(`accounts/${id}/reveal`,{reason:'short'})).status).toBe(400);expect(await(await req(`accounts/${id}/reveal`,{reason:'Authorized login review'})).json()).toEqual({secret:'private-password'});await req(`accounts/${id}/disable`,{revision:2});expect((await req(`accounts/${id}/reveal`,{reason:'Authorized login review'})).status).toBe(400);});
 it('does not allow stale secret rotations',async()=>{const {account}=await seed();expect((await req(`accounts/${account}/secret`,{secret:'first-token',revision:1},'PUT')).status).toBe(200);expect((await req(`accounts/${account}/secret`,{secret:'stale-token',revision:1},'PUT')).status).toBe(409);expect(kv.size).toBe(1);});
 it('prevents cross-brand content and invalid public media',async()=>{const ids=await seed();const other=await(await req('accounts',{...accountBody,brand:'cutiutamagica'})).json();expect((await req('marketing/posts',{...postBody(ids),account_id:other.id})).status).toBe(400);expect((await req('marketing/posts',{...postBody(ids),media_url:'http://127.0.0.1/private'})).status).toBe(400);});
 it('invalidates exact approval on edits and detects stale decisions',async()=>{const ids=await seed(),{id}=await(await req('marketing/posts',postBody(ids))).json();expect((await req(`marketing/posts/${id}/decision`,{action:'publish',revision:1})).status).toBe(409);expect((await req(`marketing/posts/${id}/decision`,{action:'approve',revision:1})).status).toBe(200);expect((await req(`marketing/posts/${id}/decision`,{action:'reject',revision:1})).status).toBe(409);expect((await req(`marketing/posts/${id}`,{...postBody(ids),caption:'Edited',revision:2},'PATCH')).status).toBe(200);expect(db.prepare('SELECT status,approved_revision FROM marketing_posts WHERE id=?').get(id)).toEqual({status:'draft',approved_revision:null});});
 it('allows granted marketing authors but restricts approvals to owners',async()=>{const ids=await seed(),{id}=await(await req('marketing/posts',postBody(ids))).json();await req('team/staff',{department:'marketing',job_title:'Marketing',read:['marketing'],write:['marketing'],revision:0},'PUT');actor='staff';expect((await req('marketing')).status).toBe(200);expect((await req(`marketing/posts/${id}/decision`,{action:'approve',revision:1})).status).toBe(403);});
 it('records daily costs only once and derives real ratios',async()=>{const ids=await seed(),metrics={day:'2026-08-01',cost_minor:2000,revenue_minor:10000,impressions:100,clicks:20,leads:5,conversions:2,evidence:'Ads export'};expect((await req(`marketing/campaigns/${ids.campaign}/measurements`,metrics)).status).toBe(200);expect((await req(`marketing/campaigns/${ids.campaign}/measurements`,metrics)).status).toBe(409);expect((await req(`marketing/campaigns/${ids.campaign}/measurements`,{...metrics,day:'2026-02-30'})).status).toBe(400);const data=await(await req('marketing')).json();expect(data.campaigns[0].metrics).toMatchObject({remaining_minor:8000,cpc_minor:100,cpl_minor:400,cpa_minor:1000,roas:5});expect(campaignMetrics({cost_minor:0,revenue_minor:0,budget_minor:0,clicks:0,leads:0,conversions:0}).roas).toBeNull();});
 it('parses official exports, excludes protected handles and caps proposals at 50',()=>{expect(socialHandles(JSON.stringify({relationships_following:[{string_list_data:[{value:'Alice',timestamp:1}]}]}))).toEqual(['alice']);expect(socialHandles('@Alice\nbob\nALICE')).toEqual(['alice','bob']);const candidates=unfollowCandidates(['alice'],['alice','partner',...Array.from({length:70},(_,i)=>`user${i}`)],['partner']);expect(candidates).toHaveLength(50);expect(candidates).not.toContain('alice');expect(candidates).not.toContain('partner');});
 it('requires complete export confirmation and persists only candidates and counts',async()=>{const {account}=await seed(),body={account_id:account,followers:'alice',following:'alice\nbob\npartner',protected_handles:'partner',complete:true,observed_at:Date.now()-1000,evidence:'Official export'};expect((await req('marketing/social-audit',{...body,complete:false})).status).toBe(400);const result=await(await req('marketing/social-audit',body)).json();expect(result.candidates).toEqual(['bob']);expect(db.prepare('SELECT candidates_json FROM social_audits').get()!.candidates_json).toBe('["bob"]');});
 async function approvedPost(provider='instagram'){
  const ids=await seed();await req(`accounts/${ids.account}/secret`,{secret:'fixture-provider-token',revision:1},'PUT');db.prepare("UPDATE os_accounts SET status='verified',provider=? WHERE id=?").run(provider,ids.account);const {id}=await(await req('marketing/posts',postBody(ids))).json();await req(`marketing/posts/${id}/decision`,{action:'approve',revision:1});return {id,ids};
 }
 it('publishes the approved Instagram container once and stores provider evidence',async()=>{const {id}=await approvedPost();const fetcher=vi.fn().mockResolvedValueOnce(Response.json({id:'111'})).mockResolvedValueOnce(Response.json({status_code:'FINISHED'})).mockResolvedValueOnce(Response.json({id:'222'}));await publishMarketing(env,id,fetcher);await publishMarketing(env,id,fetcher);expect(fetcher).toHaveBeenCalledTimes(3);expect(db.prepare('SELECT status,remote_id FROM marketing_posts WHERE id=?').get(id)).toEqual({status:'published',remote_id:'222'});});
 it('never automatically republishes ambiguous Facebook writes',async()=>{const {id}=await approvedPost('facebook');const fetcher=vi.fn().mockRejectedValue(new Error('network timeout'));await publishMarketing(env,id,fetcher);await publishMarketing(env,id,fetcher);expect(fetcher).toHaveBeenCalledTimes(1);expect(db.prepare('SELECT status FROM marketing_posts WHERE id=?').get(id)!.status).toBe('uncertain');expect((await req(`marketing/posts/${id}`,{...postBody({account:'x',campaign:'x'}),revision:2},'PATCH')).status).not.toBe(200);});
 it('polls existing video containers without creating duplicates',async()=>{const {id}=await approvedPost();const first=vi.fn().mockResolvedValueOnce(Response.json({id:'111'})).mockResolvedValueOnce(Response.json({status_code:'IN_PROGRESS'}));await publishMarketing(env,id,first);expect(db.prepare('SELECT status FROM marketing_posts WHERE id=?').get(id)!.status).toBe('processing');const second=vi.fn().mockResolvedValueOnce(Response.json({status_code:'FINISHED'})).mockResolvedValueOnce(Response.json({id:'222'}));await publishMarketing(env,id,second);expect(second.mock.calls[0][0]).toContain('/111?fields=status_code');expect(second).toHaveBeenCalledTimes(2);});
 it('respects paused campaigns, revoked accounts and agent kill switches',async()=>{const {id,ids}=await approvedPost();const fetcher=vi.fn();db.prepare("UPDATE marketing_campaigns SET status='paused' WHERE id=?").run(ids.campaign);await publishMarketing(env,id,fetcher);expect(fetcher).not.toHaveBeenCalled();db.prepare("UPDATE marketing_campaigns SET status='active' WHERE id=?").run(ids.campaign);db.prepare("UPDATE os_accounts SET status='disabled' WHERE id=?").run(ids.account);await publishMarketing(env,id,fetcher);expect(fetcher).not.toHaveBeenCalled();expect(db.prepare('SELECT status FROM marketing_posts WHERE id=?').get(id)!.status).toBe('failed');});
 it('keeps unsupported provider formats explicit',()=>{expect(publishingError({media_kind:'video',media_url:'https://avyron.ro/a.mp4',format:'reel'} as never,{status:'verified',provider:'facebook',auth_method:'oauth_token'} as Account)).toBe('facebook_story_reel_assisted_required');});
 it('blocks AI model calls without configured Cost Guard policy',async()=>{const run=vi.fn();env.AI={run};const response=await(await req('marketing/generate',{criteria:'Scrie o postare educațională, în română.',format:'feed'})).json();expect(response.error.code).toBe('cost_guard');expect(run).not.toHaveBeenCalled();expect(db.prepare("SELECT status FROM ai_runs WHERE agent_slug='marketing-studio'").get()!.status).toBe('failed');});
 it('never returns device tokens in lists, rejects unpaired heartbeats and revokes tasks',async()=>{const {account}=await seed(),device=await(await req('devices',{label:'iMac'})).json();expect(await(await req('devices')).text()).not.toContain(device.token);expect((await req(`devices/${device.id}/heartbeat`,{})).status).toBe(403);await req(`devices/${device.id}/tasks`,{account_id:account,action:'login',instructions:'Open official page'});expect((await req(`devices/${device.id}/revoke`,{})).status).toBe(200);expect(db.prepare('SELECT status FROM os_device_tasks').get()!.status).toBe('cancelled');});
 it('requires a verified Cloudflare account and acknowledgement for backup',async()=>{expect((await req('backups',{baseline:true})).status).toBe(400);expect((await req('backups',{baseline:true,acknowledge_export_pause:true})).status).toBe(400);actor='staff';expect((await req('backups')).status).toBe(403);});
 it('database triggers protect baseline and serialize backup versus deletion',()=>{db.exec("INSERT INTO backup_runs(id,status,protected,config_json,created_at) VALUES ('base','complete',1,'{}',1),('run','queued',0,'{}',1)");expect(()=>db.exec("UPDATE backup_runs SET protected=0 WHERE id='base'")).toThrow('baseline_protected');expect(()=>db.exec("DELETE FROM backup_runs WHERE id='base'")).toThrow('baseline_protected');expect(()=>db.exec("INSERT INTO backup_runs(id,status,config_json,created_at) VALUES ('gc','deleting','{}',1)")).toThrow('UNIQUE');});
 it('retention always keeps protected baseline and newest minimum copies',()=>{const runs=Array.from({length:6},(_,i)=>({id:String(i),status:'complete',created_at:i+1,protected:i===0?1:0})) as BackupRun[];expect(retentionCandidates(runs,{keep_count:2,retention_days:7} as BackupSettings,1e12).map(r=>r.id)).toEqual(['1','2','3']);});
 it('streams SQL with multipart upload and aborts on capacity overflow',async()=>{
  const upload={uploadPart:vi.fn(async(partNumber:number,value:Uint8Array)=>({partNumber,etag:String(value.byteLength)})),complete:vi.fn(async()=>({key:'sql'})),abort:vi.fn(async()=>{})};
  const bucket={createMultipartUpload:vi.fn(async()=>upload)} as unknown as R2Bucket;
  const stream=(size:number)=>new ReadableStream<Uint8Array>({start(controller){controller.enqueue(new Uint8Array(size));controller.close();}});
  await storeSqlExport(bucket,'sql',stream(20),100);expect(upload.complete).toHaveBeenCalledTimes(1);expect(upload.uploadPart.mock.calls[0][1].byteLength).toBe(20);
  await expect(storeSqlExport(bucket,'sql',stream(101),100)).rejects.toThrow('backup_capacity_exceeded');expect(upload.abort).toHaveBeenCalledTimes(1);
 });
 it('retention removes expired orphan data while preserving baseline blobs',async()=>{
  db.exec("INSERT INTO backup_runs(id,status,protected,config_json,created_at) VALUES ('base','complete',1,'{}',1),('old','failed',0,'{}',2);INSERT INTO backup_blobs VALUES ('os-backups/blobs/base',4,'etag',1),('os-backups/blobs/old',4,'etag',1);INSERT INTO backup_objects VALUES ('base','FILES','document','os-backups/blobs/base','etag',4),('old','FILES','old','os-backups/blobs/old','etag',4)");
  const removed:string[]=[];env.FILES={list:async()=>({objects:[{key:'os-backups/blobs/base'},{key:'os-backups/blobs/old'}],truncated:false}),delete:async(k:string)=>{removed.push(k);}} as unknown as R2Bucket;
  await purgeBackups(env,{keep_count:2,retention_days:7} as BackupSettings);expect(removed).toContain('os-backups/blobs/old');expect(removed).not.toContain('os-backups/blobs/base');expect(db.prepare("SELECT status FROM backup_runs WHERE id='base'").get()!.status).toBe('complete');expect(db.prepare("SELECT status FROM backup_runs WHERE id='old'").get()!.status).toBe('deleted');expect(()=>db.exec("DELETE FROM backup_objects WHERE run_id='base'")).toThrow('baseline_protected');
 });

 it('inventory verification requires credentials and exact SQL size',async()=>{
  db.exec("INSERT INTO backup_runs(id,status,config_json,sql_key,manifest_key,bytes,objects_count,created_at) VALUES ('check','complete','{}','os-backups/check/data.sql','os-backups/check/manifest.json',4,0,1)");
  let credentials=false,size=4;env.FILES={head:async(key:string)=>key.endsWith('credentials.json')?(credentials?{size:2}:null):{size:key.endsWith('data.sql')?size:100}} as unknown as R2Bucket;
  expect((await req('backups/check/verify',{})).status).toBe(400);credentials=true;expect((await req('backups/check/verify',{})).status).toBe(200);size=7;expect((await req('backups/check/verify',{})).status).toBe(400);
 });

});
