// @vitest-environment node
import {createRequire} from 'node:module';
import {readdirSync,readFileSync} from 'node:fs';
import type {DatabaseSync as SqliteDatabase,SQLInputValue} from 'node:sqlite';
import {Hono} from 'hono';
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {surveyAdmin} from '../../cloudflare/workers/api/src/surveys/admin';
import {surveyPublic} from '../../cloudflare/workers/api/src/surveys/public';
import type {Env} from '../../cloudflare/workers/api/src/types';
import {createSurvey} from '../../cloudflare/workers/api/src/surveys/data';
vi.mock('../../cloudflare/workers/api/src/antispam',()=>({checkRateLimit:async()=>({ok:true}),clientIp:()=> 'fixture',hashKey:async(v:string)=>v,verifyTurnstile:async()=>({ok:true})}));
vi.mock('../../cloudflare/workers/api/src/surveys/tasks',()=>({processSurveyEvents:async()=>{},generateSurveyAi:async()=>({available:false}),purgeSurvey:async()=>{},suggestSurveyText:async()=>({available:false})}));
const {DatabaseSync}=createRequire(import.meta.url)('node:sqlite') as typeof import('node:sqlite');
class Statement{values:SQLInputValue[]=[];constructor(readonly db:SqliteDatabase,readonly sql:string){}bind(...v:SQLInputValue[]){this.values=v;return this;}async first(){return this.db.prepare(this.sql).get(...this.values)??null;}async all(){return {results:this.db.prepare(this.sql).all(...this.values)};}async run(){return {meta:this.db.prepare(this.sql).run(...this.values)};}}
describe('Smart Survey routes against complete SQLite schema',()=>{
 let db:SqliteDatabase,app:Hono,actor:string,env:Env;
 beforeEach(()=>{db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');for(const p of readdirSync('cloudflare/d1/migrations').filter(p=>p.endsWith('.sql')).sort())db.exec(readFileSync(`cloudflare/d1/migrations/${p}`,'utf8'));for(const [uid,email,role]of [['owner','prometheus@avyron.ro','admin'],['staff','staff@example.test','staff'],['client','client@example.test','user']]){db.prepare('INSERT INTO users(id,email,password_hash,created_at,updated_at) VALUES (?,?,?,1,1)').run(uid,email,'fixture');db.prepare('INSERT INTO user_roles VALUES (?,?)').run(uid,role);}db.exec("INSERT INTO clients(id,company_name,email,created_at) VALUES ('c','Company','c@example.test',1);INSERT INTO projects(id,client_id,name,created_at) VALUES ('p','c','Project',1);INSERT INTO leads(id,name,email,created_at) VALUES ('lead','Client','c@example.test',1)");actor='owner';env={DB:{prepare:(sql:string)=>new Statement(db,sql),batch:async(statements:Statement[])=>{db.exec('BEGIN');try{const r=[];for(const s of statements)r.push(await s.run());db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}},JWT_SECRET:'test-secret-never-production',TURNSTILE_SECRET:'fixture',TURNSTILE_ALLOWED_HOSTNAMES:'localhost',ALLOWED_ORIGINS:'http://localhost:8080',FILES:{put:async()=>{},delete:async()=>{},get:async()=>null}}as unknown as Env;app=new Hono();app.use('*',async(c,next)=>{c.set('userId',actor);c.set('roles',actor==='owner'?['admin']:actor==='staff'?['staff']:['user']);await next();});app.route('/',surveyAdmin);app.route('/',surveyPublic);});
 afterEach(()=>db.close());
 const req=(path:string,body?:unknown,method=body===undefined?'GET':'POST',token?:string)=>app.request(path,{method,headers:{'content-type':'application/json',...(token?{'x-survey-token':token}:{})},body:body===undefined?undefined:JSON.stringify(body)},env,{waitUntil:()=>{},passThroughOnException:()=>{},props:{}});
 const create=async()=>{const r=await req('/api/survey-admin/surveys',{template:'website'});expect(r.status).toBe(201);return r.json() as Promise<{id:string;token:string}>;};
 const valid={business:'Company',activity:'Servicii profesionale',objectives:['Prezentare profesională'],page_topics:'Acasă și Servicii',name:'Client',email:'client@example.test',privacy:true};
 it('creates templates and isolated sessions, restores progress and rejects stale writes',async()=>{const s=await create();const read=await req('/api/surveys/session',undefined,'GET',s.token);expect(read.status).toBe(200);expect((await read.json()).revision).toBe(1);expect((await req('/api/surveys/session',{revision:1,patch:{business:'Company'}},'PATCH',s.token)).status).toBe(200);expect((await req('/api/surveys/session',{revision:1,patch:{business:'Overwritten'}},'PATCH',s.token)).status).toBe(409);const resume=await (await req('/api/surveys/session',undefined,'GET',s.token)).json();expect(resume.answers.business).toBe('Company');expect(resume.revision).toBe(2);});
 it('rejects invalid tokens, revoked and expired links',async()=>{const s=await create();expect((await req('/api/surveys/session',undefined,'GET','a'.repeat(64))).status).toBe(404);db.prepare('UPDATE survey_sessions SET expires_at=1 WHERE survey_id=?').run(s.id);expect((await req('/api/surveys/session',undefined,'GET',s.token)).status).toBe(404);});
 it('does not leak CRM data to unassigned staff or clients',async()=>{const s=await create();actor='client';expect((await req('/api/survey-admin/surveys')).status).toBe(403);actor='staff';expect((await req(`/api/survey-admin/surveys/${s.id}`)).status).toBe(403);expect((await req('/api/survey-admin/surveys',{template:'website',lead_id:'lead'})).status).toBe(403);});
 it('prefills known lead data and keeps exactly one lead after submission',async()=>{const r=await req('/api/survey-admin/surveys',{template:'website',lead_id:'lead'});expect(r.status).toBe(201);const s=await r.json();expect((await (await req('/api/surveys/session',undefined,'GET',s.token)).json()).context.name).toBe('Client');await req('/api/surveys/session',{revision:1,patch:valid},'PATCH',s.token);const sent=await req('/api/surveys/submit',{revision:2},'POST',s.token);expect(sent.status).toBe(200);expect(db.prepare('SELECT COUNT(*) n FROM leads').get()!.n).toBe(1);expect(db.prepare('SELECT lead_id FROM surveys WHERE id=?').get(s.id)!.lead_id).toBe('lead');});
 it('submits idempotently and approves the exact brief into Documents Hub',async()=>{const s=await create();expect((await req('/api/surveys/submit',{revision:1},'POST',s.token)).status).toBe(400);await req('/api/surveys/session',{revision:1,patch:valid},'PATCH',s.token);expect((await req('/api/surveys/submit',{revision:2},'POST',s.token)).status).toBe(200);expect((await req('/api/surveys/submit',{revision:2},'POST',s.token)).status).toBe(200);expect(db.prepare('SELECT COUNT(*) n FROM survey_briefs').get()!.n).toBe(1);expect(db.prepare("SELECT COUNT(*) n FROM outbox_events WHERE event_type='survey.completed'").get()!.n).toBe(1);expect(db.prepare("SELECT COUNT(*) n FROM outbox_events WHERE event_type='survey.ai_requested'").get()!.n).toBe(1);const b=db.prepare('SELECT * FROM survey_briefs').get()!;const r=await req(`/api/survey-admin/surveys/${s.id}/brief`,{id:b.id,revision:1,status:'approved',text:'Brief verificat de echipa AVYRON.',comment:''},'PATCH');expect(r.status,await r.text()).toBe(200);expect(db.prepare("SELECT COUNT(*) n FROM hub_documents WHERE category='brief' AND status='approved'").get()!.n).toBe(1);expect((await req('/api/surveys/session',{revision:2,patch:{business:'Modified'}},'PATCH',s.token)).status).toBe(409);});
 it('pins existing sessions to immutable template versions',async()=>{const s=await create();const t=db.prepare("SELECT schema_json FROM survey_versions WHERE id='website_v1'").get()!;const updated={...JSON.parse(String(t.schema_json)),title:'Version Two'};expect((await req('/api/survey-admin/templates',{id:'website',baseVersion:1,template:updated,active:true})).status).toBe(200);const v=await(await req('/api/surveys/session',undefined,'GET',s.token)).json();expect(v.template.title).toBe('Website Discovery');expect(()=>db.exec("UPDATE survey_versions SET version=5 WHERE id='website_v1'")).toThrow();});
 it('does not accept a file from a different survey',async()=>{const a=await create(),b=await create();db.prepare("INSERT INTO survey_files VALUES ('foreign-file',?,'materials','a.txt','private/a','text/plain',5,'files','ready',1)").run(a.id);expect((await req('/api/surveys/session',{revision:1,patch:{materials:['foreign-file']}},'PATCH',b.token)).status).toBe(400);});
 it('rejects unknown or hidden fields and clears stale branches',async()=>{const s=await create();expect((await req('/api/surveys/session',{revision:1,patch:{admin:true}},'PATCH',s.token)).status).toBe(400);await req('/api/surveys/session',{revision:1,patch:{website_exists:true,website:'https://example.test'}},'PATCH',s.token);const r=await req('/api/surveys/session',{revision:2,patch:{website_exists:false}},'PATCH',s.token);expect((await r.json()).answers.website).toBeUndefined();});
 it('requires the assigned identity for authenticated surveys',async()=>{const s=await createSurvey(env,{title:'Private',version:'website_v1',mode:'authenticated',user:'client'});expect((await req('/api/surveys/session',undefined,'GET',s.token)).status).toBe(404);actor='client';expect((await req('/api/surveys/session',undefined,'GET',s.token)).status).toBe(200);});
 it('supports targeted followup without editing the old approved brief',async()=>{const s=await create();await req('/api/surveys/session',{revision:1,patch:valid},'PATCH',s.token);await req('/api/surveys/submit',{revision:2},'POST',s.token);const survey=db.prepare('SELECT revision FROM surveys WHERE id=?').get(s.id)!;expect((await req(`/api/survey-admin/surveys/${s.id}/action`,{action:'followup',revision:survey.revision,questions:['audience']})).status).toBe(200);const r=await(await req('/api/surveys/session',undefined,'GET',s.token)).json();expect(r.survey.followup).toEqual(['audience']);expect(r.revision).toBe(3);await req('/api/surveys/session',{revision:3,patch:{audience:'Companii locale'}},'PATCH',s.token);expect((await req('/api/surveys/submit',{revision:4},'POST',s.token)).status).toBe(200);expect(db.prepare('SELECT COUNT(*) n FROM survey_briefs').get()!.n).toBe(2);});
 it('binds one-time access to a secure cookie without treating its proof as a user identity',async()=>{const s=await createSurvey(env,{title:'One time',version:'website_v1',mode:'one_time'});const first=await req('/api/surveys/session',undefined,'GET',s.token);expect(first.status).toBe(200);const cookie=first.headers.get('set-cookie');expect(cookie).toContain('HttpOnly');expect((await req('/api/surveys/session',undefined,'GET',s.token)).status).toBe(404);const resumed=await app.request('/api/surveys/session',{headers:{'x-survey-token':s.token,cookie:cookie!.split(';')[0]}},env);expect(resumed.status).toBe(200);});
 it('scopes granted staff to assigned projects in lists and direct requests',async()=>{db.prepare("INSERT INTO staff_dashboard_access(user_id,department,read_json,write_json,updated_by,updated_at) VALUES ('staff','developer','[\"surveys\"]','[\"surveys\"]','owner',1)").run();const result=await req('/api/survey-admin/surveys',{template:'website',project_id:'p'});expect(result.status).toBe(201);const s=await result.json();actor='staff';expect((await req(`/api/survey-admin/surveys/${s.id}`)).status).toBe(404);expect((await(await req('/api/survey-admin/surveys')).json()).data).toHaveLength(0);db.prepare("INSERT INTO project_staff(project_id,user_id,assigned_at) VALUES ('p','staff',1)").run();expect((await req(`/api/survey-admin/surveys/${s.id}`)).status).toBe(200);expect((await(await req('/api/survey-admin/surveys')).json()).data).toHaveLength(1);expect((await req('/api/survey-admin/surveys',{template:'website',project_id:'p'})).status).toBe(201);});
 it('follows lead conversion without duplicating the survey',async()=>{const result=await req('/api/survey-admin/surveys',{template:'website',lead_id:'lead'});const s=await result.json();db.prepare("UPDATE leads SET converted_project_id='p',lifecycle_stage='converted' WHERE id='lead'").run();expect(db.prepare('SELECT lead_id,client_id,project_id FROM surveys WHERE id=?').get(s.id)).toMatchObject({lead_id:'lead',client_id:'c',project_id:'p'});expect(db.prepare('SELECT COUNT(*) n FROM surveys').get()!.n).toBe(1);});

});
