import {describe,it,expect} from 'vitest';
import {seedTemplates} from '../shared/surveys/templates';
import {templateSchema,surveyPath,evaluate,answerError,deterministicBrief} from '../shared/surveys/engine';
import {inspectUpload} from '../../cloudflare/workers/api/src/surveys/files';
import {serveSurveyHost} from '../worker/surveyHost';
const t=seedTemplates[0].template;
describe('Smart Survey deterministic engine',()=>{
 it('validates all initial templates without dependency cycles',()=>{expect(seedTemplates).toHaveLength(13);for(const s of seedTemplates)expect(templateSchema.safeParse(s.template).success).toBe(true);});
 it('asks for URLs and bookings only on their active branch',()=>{expect(surveyPath(t,{website_exists:false}).some(q=>q.id==='website')).toBe(false);expect(surveyPath(t,{website_exists:true}).some(q=>q.id==='website')).toBe(true);expect(surveyPath(t,{features:['Programări']}).some(q=>q.id==='booking_flow')).toBe(true);expect(surveyPath(t,{features:['Blog']}).some(q=>q.id==='booking_flow')).toBe(false);});
 it('ignores answers on hidden branches in briefs',()=>{const b=deterministicBrief(t,{website_exists:false,website:'https://stale.example'});expect(JSON.stringify(b)).not.toContain('stale.example');});
 it('validates required conditions and scores known answers',()=>{const blank=evaluate(t,{});expect(blank.score).toBe(0);expect(blank.errors.business).toBeTruthy();const partial=evaluate(t,{business:'AVYRON',activity:'Dezvoltare',objectives:['Prezentare profesională'],page_topics:'Servicii',name:'Client',email:'client@example.test',privacy:true});expect(partial.score).toBeGreaterThan(0);expect(partial.errors).toEqual({});});
 it('rejects cycles, unknown dependencies and duplicate IDs',()=>{const clone=structuredClone(t);clone.questions[0].rules=[{action:'SHOW IF',when:[{field:'business',op:'answered'}]}];expect(templateSchema.safeParse(clone).success).toBe(false);clone.questions[0].rules=[];clone.questions[1].id=clone.questions[0].id;expect(templateSchema.safeParse(clone).success).toBe(false);});
 it('repeats content only for selected pages',()=>{const content=seedTemplates.find(t=>t.id==='content')!.template;const repeated=surveyPath(content,{page_topics:['Acasă','Contact']}).filter(q=>q.id.startsWith('page_copy'));expect(repeated.map(q=>q.id)).toEqual(['page_copy__0','page_copy__1']);});
 it('validates typed values and rejects unknown select choices',()=>{const email=t.questions.find(q=>q.id==='email')!;expect(answerError(email,'not-an-email',{})).toBeTruthy();expect(answerError(email,'name@example.test',{})).toBeNull();const options=t.questions.find(q=>q.id==='features')!;expect(answerError(options,['Injected option'],{})).toBeTruthy();});
 it('validates MIME and signatures, rejects disguised executables and unsafe SVG',()=>{expect(()=>inspectUpload('x.exe','application/octet-stream',new Uint8Array([77,90]))).toThrow();expect(()=>inspectUpload('x.png','image/png',new Uint8Array([77,90]))).toThrow();expect(()=>inspectUpload('x.svg','image/svg+xml',new TextEncoder().encode('<svg><script>alert(1)</script></svg>'))).toThrow();expect(inspectUpload('note.txt','text/plain',new TextEncoder().encode('Text valid')).mime).toBe('text/plain');});
 it('isolates host routes and never indexes private tokens',async()=>{const assets={fetch:async()=>new Response('<html>shell</html>',{headers:{'Content-Type':'text/html'}})};const root=await serveSurveyHost(new Request('https://surveys.avyron.ro/'),assets);expect(root?.status).toBe(200);const page=await serveSurveyHost(new Request(`https://surveys.avyron.ro/s/${'a'.repeat(64)}`),assets);expect(page?.headers.get('X-Robots-Tag')).toBe('noindex, nofollow');expect(page?.headers.get('Cache-Control')).toBe('private, no-store');expect((await serveSurveyHost(new Request('https://surveys.avyron.ro/blog/private'),assets))?.status).toBe(404);expect(await (await serveSurveyHost(new Request('https://surveys.avyron.ro/sitemap.xml'),assets))?.text()).not.toContain('/s/');});
});
