// @vitest-environment node
import {createRequire} from 'node:module';
import {readdirSync,readFileSync} from 'node:fs';
import type {DatabaseSync as SqliteDatabase,SQLInputValue} from 'node:sqlite';
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {processSurveyAiJobs,generateSurveyAi} from '../../cloudflare/workers/api/src/surveys/tasks';
import {groundedRephrase} from '../../cloudflare/workers/api/src/surveys/rephrase';
import {sha256} from '../../cloudflare/workers/api/src/security';
import type {Env} from '../../cloudflare/workers/api/src/types';
const {reserve}=vi.hoisted(()=>({reserve:vi.fn(async()=>({decision:'allowed',reason:'within_budget'}))}));
vi.mock('../../cloudflare/workers/api/src/aiCostGuard',()=>({reserveAiCost:reserve}));
vi.mock('../../cloudflare/workers/api/src/surveys/cost',()=>({surveyFx:async()=>4.5,surveyCostEstimate:()=>({units:2000,minor:1})}));
const {DatabaseSync}=createRequire(import.meta.url)('node:sqlite') as typeof import('node:sqlite');
class Statement{values:SQLInputValue[]=[];constructor(readonly db:SqliteDatabase,readonly sql:string){}bind(...v:SQLInputValue[]){this.values=v;return this;}async first(){return this.db.prepare(this.sql).get(...this.values)??null;}async all(){return {results:this.db.prepare(this.sql).all(...this.values)};}async run(){return {meta:this.db.prepare(this.sql).run(...this.values)};}}
describe('Durable survey AI processing',()=>{
 let db:SqliteDatabase,env:Env;const model=vi.fn();
 beforeEach(()=>{reserve.mockClear();model.mockReset();model.mockResolvedValue({response:JSON.stringify({summary:'Companie: Test.',citations:[{id:'business',quote:'Test'}],openQuestions:[],recommendations:[]})});db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');for(const p of readdirSync('cloudflare/d1/migrations').filter(p=>p.endsWith('.sql')).sort())db.exec(readFileSync(`cloudflare/d1/migrations/${p}`,'utf8'));const now=Date.now();db.prepare("INSERT INTO surveys(id,title,version_id,status,created_at,updated_at,retention_at) VALUES('s','Test','website_v1','completed',?,?,?)").run(now,now,now+86400000);db.prepare("INSERT INTO survey_responses(survey_id,answers_json,updated_at) VALUES('s','{\"business\":\"Test\"}',?)").run(now);db.prepare("INSERT INTO survey_briefs(id,survey_id,response_revision,source_json,created_at,updated_at) VALUES('b','s',1,'{}',?,?)").run(now,now);db.prepare("INSERT INTO outbox_events(id,deduplication_key,aggregate_type,aggregate_id,event_type,payload_json,status,available_at,created_at) VALUES('e','ai:s:1','survey','s','survey.ai_requested','{\"briefId\":\"b\"}','pending',0,?)").run(now);db.exec("UPDATE survey_settings SET ai_enabled=1;UPDATE financial_agent_provider_policies SET currency='RON',daily_budget_minor=250,monthly_budget_minor=2500 WHERE agent_slug='survey-brief'");env={DB:{prepare:(sql:string)=>new Statement(db,sql),batch:async(stmts:Statement[])=>{db.exec('BEGIN');try{const results=[];for(const s of stmts)results.push(await s.run());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}},AI:{run:model}}as unknown as Env;});
 afterEach(()=>db.close());
 it('processes an independently queued draft and does not run it twice',async()=>{await processSurveyAiJobs(env);expect(db.prepare("SELECT status FROM outbox_events WHERE id='e'").get()!.status).toBe('published');expect(db.prepare("SELECT ai_json FROM survey_briefs WHERE id='b'").get()!.ai_json).toContain('Companie');await processSurveyAiJobs(env);expect(model).toHaveBeenCalledTimes(1);expect(reserve).toHaveBeenCalledTimes(1);});
 it('accepts structured Workers AI JSON-mode responses',async()=>{model.mockResolvedValue({response:{summary:'Companie: Test.',citations:[{id:'business',quote:'Test'}],openQuestions:[],recommendations:[]}});await processSurveyAiJobs(env);expect(db.prepare("SELECT ai_json FROM survey_briefs WHERE id='b'").get()!.ai_json).toContain('Companie');});
 it('recovers an interrupted model run with a separately reserved attempt',async()=>{const run=`survey_${await sha256('b:ai')}`;db.prepare("INSERT INTO ai_runs(id,agent_slug,agent_version_id,status,input_hash,input_tokens,started_at,created_at) VALUES(?,'survey-brief','survey_brief_v1','running','test',1,?,?)").run(run,Date.now()-960000,Date.now()-960000);await processSurveyAiJobs(env);expect(db.prepare('SELECT status,error_code FROM ai_runs WHERE id=?').get(run)).toMatchObject({status:'failed',error_code:'execution_interrupted'});expect(db.prepare('SELECT status FROM ai_runs WHERE id=?').get(`${run}:2`)!.status).toBe('succeeded');expect(reserve.mock.calls[0][0].idempotencyKey).toBe(`${run}:2`);});
 it('bounds failures to three attempts while retaining the structured brief',async()=>{model.mockRejectedValue(new Error('provider unavailable'));for(let i=0;i<3;i++){db.exec("UPDATE outbox_events SET available_at=0 WHERE id='e'");await processSurveyAiJobs(env);}expect(db.prepare("SELECT status,attempts FROM outbox_events WHERE id='e'").get()).toMatchObject({status:'dead',attempts:3});expect(db.prepare("SELECT source_json FROM survey_briefs WHERE id='b'").get()!.source_json).toBe('{}');expect((await generateSurveyAi(env,'s')).reason).toBe('attempts_exhausted');expect(model).toHaveBeenCalledTimes(3);expect(new Set(reserve.mock.calls.map(c=>c[0].idempotencyKey)).size).toBe(3);});
 it('does not invoke a model while an existing attempt still holds its lease',async()=>{const run=`survey_${await sha256('b:ai')}`;db.prepare("INSERT INTO ai_runs(id,agent_slug,agent_version_id,status,input_hash,input_tokens,started_at,created_at) VALUES(?,'survey-brief','survey_brief_v1','running','test',1,?,?)").run(run,Date.now(),Date.now());expect((await generateSurveyAi(env,'s')).reason).toBe('already_running');expect(model).not.toHaveBeenCalled();});
});

describe('Rephrase factual vocabulary guard',()=>{
 it('allows clear phrasing and Romanian inflections',()=>{expect(groundedRephrase('vreau ceva modern pentru construcții','Îmi doresc o prezentare modernă pentru domeniul construcțiilor.')).toBe(true);});
 it('rejects invented services, numbers and names',()=>{for(const suggestion of ['Oferim proiectare și întreținere.','Avem 20 de angajați.','Compania se numește Exemplu.'])expect(groundedRephrase('servicii de construcții',suggestion)).toBe(false);expect(groundedRephrase('vreau un proiect','Vreau proiectare.')).toBe(false);expect(groundedRephrase('Nu vreau magazin','Vreau magazin.')).toBe(false);});
});
