import { useState } from 'react';
import { workspaceApi } from '@/lib/workspaceApi';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
export function ProjectStatisticsForm({projectId}:{projectId:string}){
 const [busy,setBusy]=useState(false),[form,setForm]=useState({period_start:'',period_end:'',visits:'',unique_visitors:'',uptime_percent:'',avg_response_ms:'',source:''});
 const labels={period_start:'Început interval',period_end:'Sfârșit interval',visits:'Vizite',unique_visitors:'Vizitatori unici',uptime_percent:'Disponibilitate (%)',avg_response_ms:'Răspuns mediu (ms)',source:'Sursa raportului'};
 return <details className="my-4 rounded-xl border bg-card p-4"><summary className="cursor-pointer font-medium">Înregistrează un raport de performanță</summary><p className="my-2 text-xs text-muted-foreground">Introdu numai măsurători din raportul sursă. Câmpurile goale rămân necunoscute. Raportul devine vizibil conturilor cu acces la proiect.</p><form className="grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await workspaceApi.write(`statistics/${projectId}`,{...form,period_start:new Date(form.period_start).getTime(),period_end:new Date(form.period_end).getTime(),visits:form.visits===''?null:Number(form.visits),unique_visitors:form.unique_visitors===''?null:Number(form.unique_visitors),uptime_percent:form.uptime_percent===''?null:Number(form.uptime_percent),avg_response_ms:form.avg_response_ms===''?null:Number(form.avg_response_ms)});toast.success('Raport înregistrat.');}catch(error){toast.error(error instanceof Error?error.message:'Raportul nu poate fi salvat.');}finally{setBusy(false);}}}>{Object.entries(labels).map(([key,label])=><label key={key} className="grid gap-1 text-sm">{label}<input required={key.startsWith('period')||key==='source'} type={key.startsWith('period')?'datetime-local':key==='source'?'text':'number'} min={key.startsWith('period')?undefined:0} max={key==='uptime_percent'?100:undefined} step={key==='uptime_percent'?0.01:undefined} maxLength={key==='source'?200:undefined} value={form[key as keyof typeof form]} onChange={e=>setForm(v=>({...v,[key]:e.target.value}))} className="rounded-lg border bg-background p-2"/></label>)}<Button disabled={busy}>{busy?'Se salvează…':'Salvează raportul'}</Button></form></details>;
}
