-- AVY — pachet extins de cunoștințe: întrebări reale despre agenție, prețuri,
-- servicii, obiecții, calificare lead și pași de conversie (WhatsApp / apel).
-- Toate răspunsurile se termină cu un pas concret: configurator, formular,
-- WhatsApp (+40 734 605 055) sau apel. Fără promisiuni de preț inventate.

INSERT OR IGNORE INTO ai_knowledge
  (id, agent_slug, category, language, question, answer, keywords, source, priority, created_at, updated_at)
VALUES
-- ————— PREȚURI (RO) —————
 ('kb2_ro_pret_site', NULL, 'preturi', 'ro', 'Cât costă un site de prezentare?',
  'Un website de prezentare premium pornește de la 300 euro și include design pe brandul tău, structură orientată pe conversie, viteză reală și SEO tehnic. Prețul final depinde de numărul de pagini, texte, fotografii și funcții (formulare, rezervări, multilingv). Îți dau o estimare în 2 minute prin configuratorul de pe pagina produsului sau un preț ferm pe WhatsApp la +40 734 605 055.',
  'pret site website prezentare cat costa tarif 300 euro', 'seed', 9, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_pret_magazin', NULL, 'preturi', 'ro', 'Cât costă un magazin online?',
  'Magazinul online pornește de la 1000 euro pentru o variantă complet funcțională: catalog, coș, plăți, livrare și panou de administrare. Cresc costul integrările (eMAG, ERP, facturare, abonamente, B2B) și volumul de produse de importat. Spune-mi câte produse ai și ce integrări îți trebuie și îți dau imediat un interval realist.',
  'pret magazin online ecommerce shop cat costa 1000 euro emag', 'seed', 9, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_pret_blog', NULL, 'preturi', 'ro', 'Cât costă un blog profesional?',
  'Blog Profesional și Content Hub pornește de la 1.500 lei, în loc de 2.400 lei. Include arhitectură SEO, panou de administrare pentru articole, performanță și indexare corectă în Google. Opțional: limbi suplimentare de la a 3-a (+100 lei fiecare) și AI Content Intelligence (1.000 lei). Configuratorul de pe pagina blogului îți arată prețul exact pe configurația ta.',
  'pret blog profesional content hub 1500 lei configurator', 'seed', 9, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_pret_app', NULL, 'preturi', 'ro', 'Cât costă o aplicație web sau mobilă?',
  'Aplicațiile web și mobile pornesc de la 1500 euro și se estimează pe funcționalități: conturi, plăți, notificări, panouri de administrare, integrări. Cel mai rapid mod: îmi spui pe scurt ce face aplicația și ce trebuie să poată face utilizatorul, iar echipa îți trimite un plan cu buget și etape în 24 de ore.',
  'pret aplicatie app mobil web software cat costa 1500', 'seed', 8, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_pret_ai', NULL, 'preturi', 'ro', 'Cât costă un agent AI pentru afacerea mea?',
  'Un agent AI personalizat pornește de la 500 euro. Este antrenat pe produsele, prețurile și tonul tău, răspunde 24/7 pe site și pe WhatsApp, preia comenzi, programări și date de contact, și predă discuția echipei când e nevoie de om. Exact cum funcționez eu acum pentru Avyron.',
  'pret agent ai chatbot asistent 500 euro whatsapp automatizare', 'seed', 8, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_pret_social', NULL, 'preturi', 'ro', 'Cât costă identitatea de social media?',
  'Pachetul de identitate social media pornește de la 250 euro: linie vizuală, șabloane de postare, structura profilurilor și ghid de folosire, astfel încât conturile tale să arate unitar și profesionist. Se combină foarte bine cu un site nou, pentru un brand coerent peste tot.',
  'pret social media identitate branding instagram facebook 250', 'seed', 7, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_pret_qa', NULL, 'preturi', 'ro', 'Cât costă testarea QA?',
  'Testarea QA web și mobil pornește de la 300 euro și acoperă fluxurile critice: formulare, plăți, compatibilitate pe dispozitive, viteză și erori de interfață. Primești un raport clar cu problemele găsite, prioritizate, și recomandări de rezolvare.',
  'pret qa testare bug raport 300 euro', 'seed', 6, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_audit_gratuit', NULL, 'preturi', 'ro', 'Faceți audit gratuit la site-ul actual?',
  'Da. Auditul site-ului sau al softului actual este gratuit: verificăm viteza, SEO tehnic, structura, securitatea și punctele unde pierzi clienți, apoi îți spunem clar ce merită reparat și ce merită refăcut. Trimite-mi adresa site-ului pe WhatsApp la +40 734 605 055 și pornim auditul.',
  'audit gratuit analiza site verificare seo viteza', 'seed', 9, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_plata_rate', NULL, 'preturi', 'ro', 'Se poate plăti în rate sau în tranșe?',
  'Da, lucrăm de regulă cu un avans la start și restul la livrare, iar la proiectele mari împărțim pe etape. Emitem factură pentru fiecare plată. Discutăm calendarul de plată împreună cu oferta, ca să știi din prima ce și când plătești.',
  'plata rate transe avans factura tva contract', 'seed', 7, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_costuri_lunare', NULL, 'preturi', 'ro', 'Ce costuri lunare am după lansare?',
  'Obligatoriu ai doar domeniul (aproximativ 60-120 lei pe an) și găzduirea, care la infrastructura noastră Cloudflare este foarte ieftină, iar la multe proiecte practic zero. Opțional adaugi un pachet de mentenanță pentru actualizări, backup, monitorizare și mici modificări lunare. Fără abonamente ascunse.',
  'costuri lunare hosting gazduire domeniu mentenanta abonament', 'seed', 8, strftime('%s','now'), strftime('%s','now')),

-- ————— SERVICII ȘI LIVRARE (RO) —————
 ('kb2_ro_durata', NULL, 'proces', 'ro', 'În cât timp e gata site-ul?',
  'Un site de prezentare durează în medie 2-3 săptămâni, un blog profesional 1-2 săptămâni, un magazin online 3-6 săptămâni, în funcție de conținut și integrări. Primul livrabil vizual îl vezi de obicei în 3-7 zile. Dacă ai un termen fix, spune-mi data și verific dacă îl putem prinde.',
  'cat dureaza timp livrare termen gata zile saptamani', 'seed', 9, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_continut', NULL, 'proces', 'ro', 'Trebuie să vin eu cu textele și pozele?',
  'Nu neapărat. Dacă ai materiale, le folosim și le optimizăm. Dacă nu, scriem noi textele orientate pe vânzare și punem imagini profesionale potrivite domeniului tău. Tu doar confirmi informațiile reale: servicii, prețuri, program, contact.',
  'texte poze continut copywriting imagini cine scrie', 'seed', 8, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_admin', NULL, 'produse', 'ro', 'Pot modifica singur textele și prețurile?',
  'Da. Primești panou de administrare și o sesiune scurtă de instruire: schimbi texte, prețuri, imagini, articole și date de contact fără cod și fără să ne suni de fiecare dată. Rămânem disponibili pentru modificările mai complexe.',
  'administrare panou modific singur texte preturi cms', 'seed', 8, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_seo', NULL, 'produse', 'ro', 'Site-ul apare în Google?',
  'Da. Fiecare pagină primește titlu și descriere optimizate, adrese curate, date structurate, sitemap și viteză bună - exact ce cere Google. Indexarea inițială durează de obicei 1-3 săptămâni, iar pozițiile pe cuvinte competitive cresc cu conținut constant. Îți putem face și un plan de conținut lunar.',
  'seo google indexare pozitionare cuvinte cheie trafic', 'seed', 9, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_mentenanta', NULL, 'produse', 'ro', 'Ce include pachetul de mentenanță?',
  'Mentenanța include monitorizare, backup, actualizări de securitate, mici modificări de conținut și suport prioritar, cu raport periodic. Este opțională, dar recomandată dacă site-ul îți aduce clienți și nu vrei să te ocupi tu de partea tehnică.',
  'mentenanta suport backup actualizari monitorizare abonament', 'seed', 7, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_proprietate', NULL, 'obiectii', 'ro', 'Rămâne site-ul și domeniul pe numele meu?',
  'Da, complet. Domeniul, conturile și proiectul rămân pe numele tău, iar la final primești acces total și documentație. Nu te legăm de noi: colaborezi mai departe pentru că îți convine rezultatul, nu pentru că nu ai unde pleca.',
  'proprietate domeniu cont acces cod dependenta migrare', 'seed', 8, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_migrare', NULL, 'tehnic', 'ro', 'Îmi puteți muta site-ul actual fără să pierd Google?',
  'Da. Facem migrarea cu redirecționări corecte, păstrarea adreselor importante și verificare în Search Console, astfel încât traficul și pozițiile să nu scadă. Înainte de mutare facem backup complet și o listă de verificare pe care ți-o arătăm.',
  'migrare mutare site wordpress redirect search console trafic', 'seed', 7, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_mobil', NULL, 'tehnic', 'ro', 'Site-ul arată bine pe telefon?',
  'Construim mai întâi pentru telefon, pentru că de acolo vine majoritatea traficului: butoane mari, încărcare rapidă, formulare simple și apel sau WhatsApp la o atingere. Testăm pe dispozitive reale înainte de lansare.',
  'mobil telefon responsive tableta viteza incarcare', 'seed', 7, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_gdpr', NULL, 'tehnic', 'ro', 'Sunteți conformi GDPR și cookie-uri?',
  'Da. Punem banner de cookie-uri cu consimțământ real, politici de confidențialitate și termeni, colectăm doar datele necesare și le ținem pe infrastructură securizată. Analiza de trafic pornește doar după acordul vizitatorului.',
  'gdpr cookie confidentialitate date legal politica', 'seed', 6, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_securitate', NULL, 'tehnic', 'ro', 'Cât de sigur este site-ul?',
  'Rulăm pe infrastructură Cloudflare, cu certificat SSL, protecție anti-spam și anti-bot, limitare de cereri și backup. Nu folosim mormane de pluginuri care se sparg, deci suprafața de atac este mult mai mică decât la un site clasic pe template.',
  'securitate ssl hacking spam protectie backup', 'seed', 6, strftime('%s','now'), strftime('%s','now')),

-- ————— OBIECȚII (RO) —————
 ('kb2_ro_obiectie_scump', NULL, 'obiectii', 'ro', 'Mi se pare scump, am găsit mai ieftin.',
  'Te înțeleg, și e o întrebare corectă. Diferența nu e designul, ci ce se întâmplă după lansare: viteză, SEO tehnic, structură care aduce cereri și suport real când ai nevoie. Un site care nu aduce clienți e scump la orice preț. Putem începe și cu o variantă redusă, care crește etapizat - îți fac o propunere pe bugetul tău dacă îmi spui cu ce sumă lucrezi.',
  'scump ieftin buget mic concurenta pret mare merita', 'seed', 8, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_obiectie_singur', NULL, 'obiectii', 'ro', 'Pot să îmi fac singur site-ul cu un constructor?',
  'Poți, pentru un site simplu de vizită. Diferența apare la viteză, la SEO tehnic și la structura care transformă vizitatorii în cereri - plus timpul tău, care e mai valoros în afacerea ta. Dacă vrei, îți fac gratuit un audit la ce ai acum și îți spun sincer dacă merită refăcut sau doar optimizat.',
  'singur constructor wix wordpress diy fac eu', 'seed', 7, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_obiectie_incredere', NULL, 'obiectii', 'ro', 'De unde știu că sunteți serioși?',
  'Lucrăm cu firmă înregistrată în România, contract, facturi și etape clare de plată. Poți vedea proiecte reale în secțiunea de exemple, iar înainte de orice plată primești ofertă scrisă cu ce include exact. Dacă vrei, programăm un apel scurt cu echipa.',
  'incredere firma contract garantie serios recenzii portofoliu exemple', 'seed', 8, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_obiectie_timp', NULL, 'obiectii', 'ro', 'Nu am timp să mă ocup de proiect.',
  'Nu e nevoie de mult timp de la tine: o discuție de 15-20 de minute la început, o confirmare a informațiilor reale și o rundă de revizii. Restul îl ducem noi, inclusiv textele. Cel mai simplu e un mesaj pe WhatsApp la +40 734 605 055 cu ce faci și ce vrei să obții.',
  'nu am timp ocupat implicare cat dureaza din partea mea', 'seed', 7, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_garantie', NULL, 'obiectii', 'ro', 'Ce se întâmplă dacă apare o problemă după lansare?',
  'După lansare urmează o perioadă de suport în care reparăm gratuit orice problemă ține de munca noastră. După aceea rămâi acoperit prin pachetul de mentenanță sau ne scrii punctual. Nu dispărem după factură.',
  'garantie probleme bug dupa lansare suport reparatii', 'seed', 7, strftime('%s','now'), strftime('%s','now')),

-- ————— CALIFICARE LEAD ȘI CONVERSIE (RO) —————
 ('kb2_ro_oferta', NULL, 'contact', 'ro', 'Vreau o ofertă. Ce informații trebuie să vă dau?',
  'Perfect. Am nevoie de patru lucruri: 1) ce faci și pentru cine, 2) ce tip de proiect vrei (site, magazin, blog, aplicație, agent AI), 3) termenul dorit, 4) un buget orientativ. Le poți completa în formularul de pe pagina produsului sau mi le scrii direct pe WhatsApp la +40 734 605 055 și primești răspuns în aceeași zi lucrătoare.',
  'oferta cerere pret informatii formular vreau oferta cotatie', 'seed', 10, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_configurator', NULL, 'contact', 'ro', 'Pot vedea un preț fără să vorbesc cu cineva?',
  'Da. Pe paginile de produs ai un configurator: alegi tipul de proiect, numărul de pagini, limbile și funcțiile dorite, iar prețul estimat apare instant. La final poți trimite exact acea configurație echipei, ca oferta să fie pe fix ce ai ales.',
  'configurator estimare pret instant simulare calculator', 'seed', 9, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_apel', NULL, 'contact', 'ro', 'Putem vorbi la telefon?',
  'Sigur. Ne poți suna la +40 734 605 055 sau ne scrii pe WhatsApp la același număr, iar dacă preferi, lasă-mi numărul tău în formular și te sunăm noi la ora care îți convine. Un apel de 15 minute lămurește de obicei tot: soluție, buget și termen.',
  'apel telefon suna programare discutie call intalnire', 'seed', 10, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_whatsapp', NULL, 'contact', 'ro', 'Aveți WhatsApp?',
  'Da, WhatsApp la +40 734 605 055 - e cel mai rapid canal. Trimite-ne un mesaj cu domeniul tău de activitate și ce vrei să obții, iar dacă ai deja un site, adaugă și adresa lui: îți răspundem cu o primă evaluare gratuită.',
  'whatsapp mesaj numar telefon contact rapid', 'seed', 10, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_program', NULL, 'contact', 'ro', 'Care este programul vostru de lucru?',
  'Răspundem de regulă în aceeași zi lucrătoare, în intervalul 09:00-18:00. Mesajele trimise seara sau în weekend primesc răspuns la prima oră în ziua lucrătoare următoare. Eu, AVY, sunt aici non-stop pentru întrebări și estimări.',
  'program orar disponibilitate raspuns weekend', 'seed', 6, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_zona', NULL, 'agentie', 'ro', 'Lucrați doar în Iași sau în toată țara?',
  'Lucrăm cu clienți din toată România și din afara ei, complet la distanță: discuții online, livrare și instruire pe video. Suntem înregistrați în județul Iași, deci pentru clienții locali putem organiza și o întâlnire față în față.',
  'zona iasi bucuresti romania online distanta local', 'seed', 6, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_recomandare', NULL, 'produse', 'ro', 'Nu știu ce mi se potrivește. Ce îmi recomandați?',
  'Îți spun în trei întrebări: vinzi produse online, oferi servicii sau vrei mai ales vizibilitate? Dacă vinzi produse - magazin online. Dacă oferi servicii și vrei cereri - site de prezentare plus blog pentru Google. Dacă ai deja trafic și vrei automatizare - agent AI. Spune-mi ce faci și îți recomand varianta cu cel mai bun raport cost-rezultat.',
  'ce imi recomandati nu stiu ce aleg potrivit consultanta', 'seed', 8, strftime('%s','now'), strftime('%s','now')),
 ('kb2_ro_rezultate', NULL, 'agentie', 'ro', 'Ce rezultate pot să aștept?',
  'Realist: un site bine construit crește cererile pentru că se încarcă rapid, spune clar ce oferi și are butoane de contact la îndemână. Rezultatele SEO apar treptat, în 1-3 luni pentru cuvintele locale. Nu promitem poziții garantate - promitem o bază tehnică pe care creșterea chiar se poate construi și date măsurate lunar.',
  'rezultate garantii clienti trafic vanzari cat creste', 'seed', 7, strftime('%s','now'), strftime('%s','now')),

-- ————— ENGLEZĂ —————
 ('kb2_en_site_price', NULL, 'preturi', 'en', 'How much does a presentation website cost?',
  'A premium presentation website starts at 300 EUR and includes brand-based design, a conversion-focused structure, real speed and technical SEO. The final price depends on pages, content and features. Use the configurator on the product page for an instant estimate, or message us on WhatsApp at +40 734 605 055 for a firm quote.',
  'price website presentation cost how much 300', 'seed', 9, strftime('%s','now'), strftime('%s','now')),
 ('kb2_en_shop_price', NULL, 'preturi', 'en', 'How much does an online store cost?',
  'An online store starts at 1000 EUR fully functional: catalog, cart, payments, shipping and admin panel. Integrations (marketplaces, ERP, invoicing, subscriptions, B2B) and product volume influence the price. Tell me your product count and integrations and I will give you a realistic range.',
  'price store ecommerce shop cost 1000', 'seed', 8, strftime('%s','now'), strftime('%s','now')),
 ('kb2_en_ai_price', NULL, 'preturi', 'en', 'How much does an AI agent cost?',
  'A custom AI agent starts at 500 EUR. It is trained on your products, prices and tone of voice, answers 24/7 on your site and WhatsApp, captures leads and bookings, and hands over to your team when a human is needed.',
  'price ai agent chatbot assistant 500', 'seed', 7, strftime('%s','now'), strftime('%s','now')),
 ('kb2_en_timeline', NULL, 'proces', 'en', 'How long does a project take?',
  'A presentation website takes 2-3 weeks on average, a professional blog 1-2 weeks, an online store 3-6 weeks, depending on content and integrations. You usually see the first visual deliverable within 3-7 days. If you have a fixed deadline, tell me the date and I will check feasibility.',
  'timeline how long duration delivery weeks deadline', 'seed', 8, strftime('%s','now'), strftime('%s','now')),
 ('kb2_en_audit', NULL, 'preturi', 'en', 'Do you offer a free audit?',
  'Yes. The audit of your current website or software is free: we check speed, technical SEO, structure, security and where you lose customers, then tell you clearly what to fix and what to rebuild. Send your website address on WhatsApp at +40 734 605 055 and we will start.',
  'free audit analysis check website review', 'seed', 8, strftime('%s','now'), strftime('%s','now')),
 ('kb2_en_quote', NULL, 'contact', 'en', 'I want a quote. What do you need from me?',
  'Four things: what you do and for whom, the project type, your deadline and an approximate budget. Fill in the form on the product page or message us on WhatsApp at +40 734 605 055 - you get an answer the same business day.',
  'quote offer request price information form', 'seed', 9, strftime('%s','now'), strftime('%s','now')),
 ('kb2_en_call', NULL, 'contact', 'en', 'Can we talk on the phone?',
  'Of course. Call or WhatsApp us at +40 734 605 055, or leave your number in the form and we will call you at a convenient time. A 15-minute call usually clarifies solution, budget and timeline.',
  'call phone talk meeting schedule whatsapp', 'seed', 9, strftime('%s','now'), strftime('%s','now')),
 ('kb2_en_ownership', NULL, 'obiectii', 'en', 'Do I own the website and the domain?',
  'Yes, entirely. The domain, accounts and project stay in your name, and at handover you receive full access and documentation. You stay with us because of the results, not because you are locked in.',
  'ownership domain access code lock migration', 'seed', 7, strftime('%s','now'), strftime('%s','now')),
 ('kb2_en_expensive', NULL, 'obiectii', 'en', 'It looks expensive, I found cheaper offers.',
  'Fair question. The difference is not the design, it is what happens after launch: speed, technical SEO, a structure that generates enquiries and real support. A website that brings no clients is expensive at any price. Tell me your budget and I will propose a staged scope that fits it.',
  'expensive cheap budget competitor price worth', 'seed', 7, strftime('%s','now'), strftime('%s','now')),
 ('kb2_en_maintenance', NULL, 'produse', 'en', 'What are the monthly costs after launch?',
  'Mandatory costs are only the domain (about 15-25 EUR per year) and hosting, which on our Cloudflare infrastructure is very low and often practically zero. Optionally you add a maintenance plan for updates, backups, monitoring and small monthly changes. No hidden subscriptions.',
  'monthly cost hosting domain maintenance subscription', 'seed', 7, strftime('%s','now'), strftime('%s','now'));

-- AVY este instruit explicit să ghideze spre configurator, formular, WhatsApp sau apel.
UPDATE ai_agents SET
  system_prompt = 'Ești AVY, asistentul oficial al agenției Avyron. Ton profesionist, prietenos, direct, tech, fără vorbe goale. Răspunzi DOAR pe baza contextului furnizat despre Avyron. Dacă nu știi, spui sincer și trimiți la echipă. Califici discret cererea (tip de proiect, termen, buget) și închizi fiecare răspuns cu UN SINGUR pas concret: configuratorul pentru preț instant, formularul pentru ofertă, WhatsApp la +40 734 605 055 sau apel la același număr.',
  guardrails = 'Nu inventa prețuri, termene sau garanții. Folosește doar prețurile din context (de la: site 300 EUR, magazin 1000 EUR, aplicații 1500 EUR, agent AI 500 EUR, social media 250 EUR, QA 300 EUR, blog 1.500 lei, audit gratuit). Nu cere date sensibile (card, CNP, parole). Maxim 120 de cuvinte. Un singur îndemn la acțiune pe răspuns. Răspunde în limba utilizatorului.',
  updated_at = strftime('%s','now')
WHERE slug = 'avy';

UPDATE ai_agents SET
  system_prompt = 'Ești agentul de lead-uri Avyron pentru Meta, Instagram, Facebook și WhatsApp. Răspunzi în maximum 3 fraze, califici cererea prin întrebări scurte (domeniu de activitate, tip de proiect, termen, buget orientativ) și propui imediat pasul următor: un apel de 15 minute la +40 734 605 055 sau trimiterea unei oferte scrise în aceeași zi lucrătoare.',
  updated_at = strftime('%s','now')
WHERE slug = 'leads';
