import { useEffect,useRef,useState } from 'react';
import { ArrowDown,ArrowUp,Check,Download,FileText,Upload,X } from 'lucide-react';
import type { Question } from '@/shared/surveys/engine';
import { uploadTypes } from '@/shared/surveys/engine';
import { uploadSurveyFile,surveyFileBlob,downloadSurveyFile,surveyMessage,surveyRequest,type SurveyFile } from '@/lib/surveysApi';
type Props={question:Question;value:unknown;onChange:(value:unknown)=>void;token?:string;files?:SurveyFile[];onFile?:(file:SurveyFile)=>void;error?:string;disabled?:boolean};
export default function QuestionField({question:q,value,onChange,token,files=[],onFile,error,disabled=false}:Props){
 const input=useRef<HTMLInputElement>(null),[uploading,setUploading]=useState(false),[progress,setProgress]=useState(0),[uploadError,setUploadError]=useState(''),[retry,setRetry]=useState<File[]>([]),[suggestion,setSuggestion]=useState(''),[helpBusy,setHelpBusy]=useState(false),[helpError,setHelpError]=useState('');
 const id=`survey-field-${q.id}`,described=`${id}-hint ${id}-error`;
 const upload=async(selected:File[])=>{if(!token||disabled)return;setUploading(true);setUploadError('');setRetry([]);let ids=Array.isArray(value)?[...value] as string[]:[];const multiple=q.type==='files';for(let i=0;i<selected.length;i++){const file=selected[i];try{const stored=await uploadSurveyFile(file,q.id,token,setProgress);onFile?.(stored);ids=multiple?[...ids,stored.id]:[stored.id];onChange(ids);}catch(e){setUploadError(surveyMessage(e));setRetry(selected.slice(i));break;}}setUploading(false);};
 if(q.type==='info')return <div className="survey-info">{q.help}</div>;
 const attrs={id,'aria-describedby':described,'aria-invalid':!!error,disabled};
 let field;
 if(uploadTypes.includes(q.type))field=<><div className="survey-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!uploading)void upload(Array.from(e.dataTransfer.files).slice(0,q.type==='files'?10:1));}}><Upload size={28}/><strong>Ajută-ne să vedem ce ai în minte</strong><p>Alege fișierele sau trage-le aici.<br/>Maximum 10 MB / fișier · 60 MB în total</p><input {...attrs} ref={input} type="file" multiple={q.type==='files'} accept={['image','logo'].includes(q.type)?'image/png,image/jpeg,image/webp,image/gif,image/svg+xml,application/pdf':'.png,.jpg,.jpeg,.webp,.gif,.svg,.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt'} onChange={e=>{void upload(Array.from(e.target.files||[]));e.target.value='';}} disabled={disabled||uploading} aria-label="Selectează fișiere"/>{uploading&&<><progress max={100} value={progress} aria-label="Progres încărcare"/><span>{progress}%</span></>}</div><div className="survey-file-list">{(Array.isArray(value)?value:[]).map(fileId=>{const f=files.find(f=>f.id===fileId);return <div key={String(fileId)}>{f&&token&&['image/png','image/jpeg','image/webp','image/gif'].includes(f.mime_type)?<PrivateImage file={f} token={token}/>:<FileText size={18}/>}<span>{f?.original_filename||'Fișier încărcat'}<small>{f?`${Math.round(f.size/1024)} KB`:''}</small></span>{f&&token&&<button type="button" aria-label={`Descarcă ${f.original_filename}`} onClick={()=>void downloadSurveyFile(f,token).catch(e=>setUploadError(surveyMessage(e)))}><Download size={17}/></button>}<button type="button" disabled={disabled||uploading} aria-label={`Elimină ${f?.original_filename||'fișierul'} din răspuns`} onClick={()=>onChange((value as string[]).filter(x=>x!==fileId))}><X size={17}/></button></div>;})}</div>{uploadError&&<p role="alert" className="survey-error">{uploadError}</p>}{retry.length>0&&<button type="button" className="survey-button" disabled={uploading} onClick={()=>void upload(retry)}>Reîncearcă încărcarea</button>}</>;
 else if(['single','multi','yesno','image-select'].includes(q.type)){const opts=q.type==='yesno'?['Da','Nu']:q.options;field=<div className="survey-answer-options" role={q.type==='multi'?'group':'radiogroup'} aria-label={q.label}>{opts.map((opt,i)=>{const val=q.type==='yesno'?i===0:opt,selected=q.type==='multi'?Array.isArray(value)&&value.includes(opt):value===val;return <button key={opt} type="button" role={q.type==='multi'?'checkbox':'radio'} aria-checked={selected} disabled={disabled} className={selected?'selected':''} onClick={()=>onChange(q.type==='multi'?(selected?(value as string[]).filter(v=>v!==opt):[...(Array.isArray(value)?value:[]),opt]):val)}>{q.type==='image-select'&&(q.imageUrls?.[opt]?<img className="survey-visual-option" src={q.imageUrls[opt]} alt="" loading="lazy"/>:<span className={`survey-visual-option visual-${i%4}`} aria-hidden="true"/>)}<span>{opt}</span><span className="answer-check">{selected&&<Check size={16}/>}</span></button>;})}</div>;}
 else if(q.type==='dropdown')field=<select {...attrs} value={typeof value==='string'?value:''} onChange={e=>onChange(e.target.value)}><option value="">Alege o opțiune</option>{q.options.map(o=><option key={o}>{o}</option>)}</select>;
 else if(q.type==='long')field=<textarea {...attrs} rows={6} maxLength={6000} placeholder="Câteva idei sunt suficiente pentru început…" value={typeof value==='string'?value:''} onChange={e=>onChange(e.target.value)}/>;
 else if(q.type==='consent')field=<label className="survey-consent"><input {...attrs} type="checkbox" checked={value===true} onChange={e=>onChange(e.target.checked?true:null)}/><span>{q.label} <a href="https://avyron.ro/gdpr" target="_blank" rel="noopener noreferrer">Citește informarea</a></span></label>;
 else if(['rating','scale'].includes(q.type))field=<div className="survey-scale" role="radiogroup" aria-label={q.label}>{Array.from({length:Math.min(11,(q.max??5)-(q.min??1)+1)},(_,i)=>i+(q.min??1)).map(n=><button type="button" role="radio" aria-checked={value===n} className={value===n?'selected':''} disabled={disabled} onClick={()=>onChange(n)} key={n}>{n}</button>)}</div>;
 else if(q.type==='ranking'){const list=Array.isArray(value)&&value.length===q.options.length?value as string[]:q.options;field=<ol className="survey-ranking">{list.map((o,i)=><li key={o}><span>{i+1}. {o}</span>{[-1,1].map(dir=><button type="button" key={dir} aria-label={`${dir<0?'Mută mai sus':'Mută mai jos'}: ${o}`} disabled={disabled||i+dir<0||i+dir>=list.length} onClick={()=>{const next=[...list];[next[i],next[i+dir]]=[next[i+dir],next[i]];onChange(next);}}>{dir<0?<ArrowUp size={16}/>:<ArrowDown size={16}/>}</button>)}</li>)}<button type="button" className="survey-button" onClick={()=>onChange([...list])} disabled={disabled}>Confirmă ordinea</button></ol>;}
 else if(q.type==='matrix')field=<div className="survey-matrix">{q.rows.map(row=><label key={row}>{row}<select disabled={disabled} value={String((value as Record<string,unknown>)?.[row]||'')} onChange={e=>onChange({...((value&&typeof value==='object'?value:{}) as object),[row]:e.target.value})}><option value="">Alege</option>{q.options.map(o=><option key={o}>{o}</option>)}</select></label>)}</div>;
 else field=<input {...attrs} type={({short:'text',email:'email',phone:'tel',url:'url',number:'number',currency:'number',date:'date',color:'color'} as Record<string,string>)[q.type]||'text'} min={q.min} max={q.max} maxLength={500} autoComplete={q.type==='email'?'email':q.type==='phone'?'tel':'off'} value={typeof value==='string'||typeof value==='number'?value:q.type==='color'?'#8b8cf8':''} onChange={e=>onChange(['number','currency'].includes(q.type)?e.target.value===''?null:Number(e.target.value):e.target.value)}/>;
 return <div className="survey-field"><label className="sr-only" htmlFor={id}>{q.label}</label>{field}{q.type==='long'&&token&&<div><button type="button" className="survey-button subtle" disabled={disabled||helpBusy||String(value||'').trim().length<5} onClick={()=>{setHelpBusy(true);setHelpError('');void surveyRequest<{available:boolean;suggestion?:string}>('assist',{question:q.id,text:String(value).slice(0,3000)},token).then(r=>{if(r.available&&r.suggestion)setSuggestion(r.suggestion);else setHelpError('Asistența AI nu este disponibilă momentan. Răspunsul tău este suficient; îl clarificăm împreună.');}).catch(e=>setHelpError(surveyMessage(e))).finally(()=>setHelpBusy(false));}}>{helpBusy?'Pregătim o propunere…':'Ajută-mă să formulez'}</button>{helpError&&<p className="survey-muted" role="status">{helpError}</p>}{suggestion&&<div className="survey-info"><strong>Propunere de verificat</strong><p>{suggestion}</p><p>Confirmă că descrie corect afacerea ta. Nu a fost salvată încă.</p><button type="button" className="survey-button" onClick={()=>{onChange(suggestion);setSuggestion('');}}>Folosește această formulare</button><button type="button" className="survey-button subtle" onClick={()=>setSuggestion('')}>Păstrează textul meu</button></div>}</div>}<p id={`${id}-hint`} className="survey-field-help">{q.help}</p><p id={`${id}-error`} role={error?'alert':undefined} className="survey-error">{error||''}</p></div>;
}

function PrivateImage({file,token}:{file:SurveyFile;token:string}){const [url,setUrl]=useState('');useEffect(()=>{let active=true,object='';void surveyFileBlob(file,token).then(blob=>{if(!active)return;object=URL.createObjectURL(blob);setUrl(object);}).catch(()=>{});return()=>{active=false;if(object)URL.revokeObjectURL(object);};},[file,token]);return url?<img src={url} alt={`Previzualizare ${file.original_filename}`} loading="lazy" style={{width:56,height:56,objectFit:'cover',borderRadius:8}}/>:<FileText size={18}/>;}
