import { templateSchema, type Question, type SurveyTemplate } from './engine';
const q=(id:string,label:string,type:Question['type']='short',extra:Partial<Question>={}):Question=>({id,label,type,section:'business',help:'',required:false,importance:'recommended',options:[],rows:[],rules:[],...extra});
const show=(field:string,value:string|boolean|number):Question['rules']=>[{action:'SHOW IF',when:[{field,op:'eq',value}]}];
const business=[q('business','Cum se numește afacerea ta?','short',{required:true,importance:'critical',help:'Numele comercial este suficient. Nu avem nevoie de documente fiscale acum.'}),q('activity','Ce face afacerea ta, pe scurt?','long',{required:true,importance:'critical',help:'Spune-ne în cuvintele tale ce oferi și ce te diferențiază.'}),q('audience','Cui te adresezi?','long',{help:'Tipuri de clienți, localitate sau piață. Un răspuns scurt este un început bun.'}),q('website_exists','Ai deja un website?','yesno'),q('website','Care este adresa website-ului?','url',{rules:show('website_exists',true)}),q('website_problems','Ce ai dori să îmbunătățim la website?','long',{rules:show('website_exists',true)})];
const goals=[q('objectives','Ce vrei să obții prin proiect?','multi',{section:'goals',required:true,importance:'critical',options:['Mai multe solicitări','Prezentare profesională','Vânzări online','Programări','Automatizare','Vizibilitate în Google']}),q('description','Ce este cel mai important pentru tine?','long',{section:'goals',help:'Povestește-ne rezultatul pe care l-ai considera un succes.'}),q('deadline','Ai o dată preferată pentru lansare?','date',{section:'goals',importance:'optional',help:'Este o preferință, nu un termen contractual. Îl confirmăm împreună.'})];
const design=[q('brand_exists','Ai deja logo și identitate vizuală?','yesno',{section:'design'}),q('logo','Încarcă logo-ul sau ghidul de brand','logo',{section:'design',rules:show('brand_exists',true),help:'Poți reveni cu materialele mai târziu.'}),q('branding_needed','Ai nevoie de ajutor pentru identitatea vizuală?','yesno',{section:'design',rules:show('brand_exists',false)}),q('style','Cum ai vrea să se simtă noul proiect?','single',{section:'design',options:['Minimalist și clar','Elegant și premium','Cald și apropiat','Tehnic și modern','Ne hotărâm împreună']}),q('references','Ai exemple sau competitori relevanți?','long',{section:'design',importance:'optional',help:'Adaugă linkuri și spune-ne ce îți place la ele.'}),q('materials','Adaugă materialele pe care le ai deja','files',{section:'design',help:'Fotografii, texte sau documente. Fără parole ori date sensibile.'})];
const contact=[q('name','Cum te putem numi?','short',{section:'review',required:true,importance:'critical'}),q('email','La ce email te putem contacta?','email',{section:'review',required:true,importance:'critical'}),q('phone','Număr de telefon','phone',{section:'review',importance:'optional',help:'Opțional. Îl folosim pentru discuția despre proiect.'}),q('contact_channel','Cum preferi să vorbim?','single',{section:'review',options:['Email','Telefon','WhatsApp'],help:'Poți lua legătura direct cu noi în orice moment.'}),q('privacy','Am citit informarea privind prelucrarea datelor pentru această solicitare.','consent',{section:'review',required:true,importance:'critical',help:'Datele sunt folosite pentru analizarea solicitării și pregătirea proiectului. Aceasta nu este o înscriere la newsletter.'})];
const sections=[{id:'business',title:'Afacerea ta'},{id:'goals',title:'Obiective'},{id:'content',title:'Conținut și funcții'},{id:'design',title:'Stil și materiale'},{id:'review',title:'Verificare și contact'}];
const content=(id:string,label:string,type:Question['type']='long',extra:Partial<Question>={})=>q(id,label,type,{section:'content',...extra});
const website=[content('pages','De câte pagini crezi că ai nevoie?','single',{options:['O singură pagină','2–5 pagini','6–10 pagini','Peste 10 pagini','Am nevoie de îndrumare']}),content('page_topics','Ce servicii sau secțiuni trebuie prezentate?','long',{required:true,importance:'critical',help:'De exemplu: Acasă, Despre noi, Servicii, Proiecte și Contact.'}),content('languages','În ce limbi va fi conținutul?','multi',{options:['Română','Engleză','Altă limbă']}),content('features','Ce funcții sunt utile clienților tăi?','multi',{options:['Formular de contact','WhatsApp','Programări','Galerie','Blog','Hartă','Zonă privată']}),content('booking_flow','Cum se desfășoară o programare?','long',{rules:[{action:'SHOW IF',when:[{field:'features',op:'includes',value:'Programări'}]}]}),content('content_ready','Ai textele și fotografiile pregătite?','single',{options:['Da','Parțial','Am nevoie de ajutor']}),content('care','Ai nevoie de suport după lansare?','single',{options:['Doresc informații despre Plus','Doresc informații despre Pro','Doresc informații despre Pro Activ','Discutăm după definirea proiectului','Voi administra intern'],help:'Înregistrăm interesul; nu activăm automat un abonament.'})];
const definitions:[string,string,string,string,Question[]][]=[
 ['website','Website Discovery','Site Prezentare Profesional','Punem în ordine ideile pentru un website care îți reprezintă afacerea.',website],
 ['ecommerce','E-commerce Discovery','Magazin Online','Înțelegem produsele, comenzile și modul tău de lucru.',[content('products_count','Câte produse vei comercializa?','number',{required:true,importance:'critical',min:1,max:1000000}),content('catalog_system','Cum gestionezi catalogul, stocurile și importurile?','long',{rules:[{action:'SHOW IF',when:[{field:'products_count',op:'gt',value:1000}]}]}),content('payments','Ce metode de plată sunt necesare?','multi',{options:['Card','Ramburs','Transfer bancar','De stabilit']}),content('shipping','Cu ce curieri sau servicii de livrare lucrezi?'),content('invoicing','Ce sistem de facturare folosești?'),content('catalog','Încarcă un exemplu de catalog','document')]],
 ['blog','Professional Blog','Blog Profesional','Pregătim structura editorială și experiența cititorilor.',[content('topics','Care sunt subiectele și categoriile principale?','long',{required:true,importance:'critical'}),content('authors','Cine va scrie și aproba articolele?'),content('frequency','Cât de des vrei să publici?','single',{options:['Zilnic','Săptămânal','Lunar','De stabilit']}),content('languages','Limbile blogului','multi',{options:['Română','Engleză','Altă limbă']}),content('migration','Există articole care trebuie migrate?','yesno')]],
 ['application','Web Application','Aplicații Web și Mobile','Descriem fluxurile reale și nevoile utilizatorilor.',[content('users','Cine va utiliza aplicația și cu ce roluri?','long',{required:true,importance:'critical'}),content('workflows','Descrie principalele acțiuni ale utilizatorilor.','long',{required:true,importance:'critical'}),content('platforms','Unde va fi folosită?','multi',{options:['Browser','iOS','Android','Intern']}),content('integrations','Ce sisteme trebuie conectate?'),content('sensitive_data','Ce categorii de date va prelucra aplicația?','long',{help:'Descrie categoriile, fără să încarci date personale reale.'})]],
 ['ai','AI Agent / Chatbot','Agent AI personalizat','Definim clar ce poate face agentul și când cere ajutor uman.',[content('mission','Ce sarcini trebuie să îndeplinească agentul?','long',{required:true,importance:'critical'}),content('sources','Din ce surse aprobate poate răspunde?'),content('channels','Unde va fi disponibil?','multi',{options:['Website','Platformă internă','WhatsApp','Alt canal']}),content('boundaries','Ce nu are voie să facă agentul?','long',{required:true,importance:'critical'}),content('handoff','Când trebuie să transfere conversația unui operator?')]],
 ['seo','SEO Discovery','SEO','Înțelegem piața, conținutul și prioritățile de căutare.',[content('regions','Ce localități sau piețe vizezi?','long',{required:true,importance:'critical'}),content('search_topics','Pentru ce servicii vrei să fii găsit?'),content('competitors','Care sunt principalii concurenți?'),content('seo_history','Ce optimizări au fost făcute până acum?')]],
 ['branding','Branding & Social Identity','Identitate Social Media','Clarificăm personalitatea brandului și prezența digitală.',[content('values','Ce valori trebuie să transmită brandul?','long',{required:true,importance:'critical'}),content('channels','Canalele de comunicare','multi',{options:['Facebook','Instagram','TikTok','LinkedIn','Website']}),content('tone','Ce ton de comunicare preferi?'),content('avoid','Ce stiluri sau abordări vrei să evităm?')]],
 ['onboarding','Client Onboarding','Onboarding client','Organizăm colaborarea și responsabilitățile.',[content('stakeholders','Cine oferă feedback și cine aprobă livrabilele?','long',{required:true,importance:'critical'}),content('availability','Cum preferi să organizăm întâlnirile?'),content('dependencies','Există dependențe sau termene importante?')]],
 ['content','Project Content Collection','Colectare materiale','Adunăm conținutul proiectului într-un singur loc.',[content('page_topics','Pentru ce pagini trimiți conținut?','multi',{options:['Acasă','Despre','Servicii','Produse','Contact']}),content('page_copy','Textul paginii','long',{repeat:{source:'page_topics',max:5},help:'Poți trimite o primă versiune; o rafinăm împreună.'}),content('rights','Ai dreptul de utilizare a materialelor trimise?','yesno',{required:true,importance:'critical'})]],
 ['qa','QA / Acceptance','Testare QA Web & Mobile','Stabilim fluxurile de testare și criteriile de acceptare.',[content('test_flows','Care sunt fluxurile critice?','long',{required:true,importance:'critical'}),content('devices','Dispozitive de verificat','multi',{options:['Desktop','iPhone / Safari','Android / Chrome','Tabletă']}),content('acceptance','Care sunt criteriile de acceptare?'),content('issues','Probleme deja cunoscute')]],
 ['feedback','Project Feedback','Feedback proiect','Ne ajuți să îmbunătățim colaborarea.',[content('satisfaction','Cum evaluezi experiența?','rating',{min:1,max:5,required:true,importance:'critical'}),content('strengths','Ce a funcționat bine?'),content('improvements','Ce putem îmbunătăți?')]],
 ['maintenance','Maintenance / Update Request','Mentenanță și abonamente','Documentăm actualizarea de care ai nevoie.',[content('request','Ce vrei să actualizăm?','long',{required:true,importance:'critical'}),content('impact','Cum îți afectează activitatea?'),content('urgency','Cât de urgentă este solicitarea?','single',{options:['Activitatea este blocată','Important, în următoarele zile','Actualizare planificată']}),content('plan','Abonamentul tău, dacă îl cunoști','single',{options:['Plus','Pro','Pro Activ','Nu am abonament','Nu sunt sigur']})]],
 ['audit','Website Audit','Audit Website / Soft Actual','Identificăm obiectivele și problemele pentru audit.',[content('audit_url','Adresa produsului de analizat','url',{required:true,importance:'critical'}),content('issues','Ce probleme ai observat?','long',{required:true,importance:'critical'}),content('scope','Ce ar trebui să analizăm?','multi',{options:['Performanță','SEO','Accesibilitate','Securitate','Fluxuri comerciale']})]],
];
export const seedTemplates:ReadonlyArray<{id:string;template:SurveyTemplate}>=definitions.map(([id,title,service,description,fields])=>({id,template:templateSchema.parse({title,description,service,sections,questions:[...business,...goals,...fields,...design,...contact]})}));
export const SURVEY_CONTACT={phone:'+40734605055',phoneLabel:'+40 734 605 055',whatsapp:'https://wa.me/40734605055?text=Bun%C4%83%21%20A%C8%99%20vrea%20s%C4%83%20discut%C4%83m%20despre%20proiectul%20meu.',email:'contact@avyron.ro',development:'development@avyron.ro',website:'https://avyron.ro'};
