import {useEffect,useState} from 'react';
import {Download,RefreshCw,WifiOff} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {takeInstallPrompt,clearInstallPrompt} from '@/lib/pwa';
export default function InstallApp(){
 const [open,setOpen]=useState(false),[available,setAvailable]=useState(Boolean(takeInstallPrompt())),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const standalone=()=>window.matchMedia('(display-mode: standalone)').matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone);
 const [installed,setInstalled]=useState(standalone);
 useEffect(()=>{const update=()=>{setAvailable(Boolean(takeInstallPrompt()));setInstalled(standalone());};window.addEventListener('avyron:install-state',update);window.addEventListener('appinstalled',update);return()=>{window.removeEventListener('avyron:install-state',update);window.removeEventListener('appinstalled',update);};},[]);
 const install=async()=>{const prompt=takeInstallPrompt();if(!prompt)return;setBusy(true);try{await prompt.prompt();const choice=await prompt.userChoice;setMessage(choice.outcome==='accepted'?'Cererea de instalare a fost acceptată.':'Poți reveni oricând pentru instalare.');}catch{setMessage('Folosește opțiunea de instalare din meniul browserului.');}finally{clearInstallPrompt();setBusy(false);}};
 return <><button type="button" onClick={()=>setOpen(true)} aria-label="Descarcă aplicația web" title="Descarcă aplicația web" className="inline-flex items-center shrink-0 rounded-xl border border-violet-400/20 bg-violet-500/10 p-2.5 text-violet-200"><Download className="size-4"/><span className="ml-2 hidden xl:inline">Descarcă aplicația web</span></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[85dvh] overflow-y-auto"><DialogHeader><DialogTitle>{installed?'Aplicația este instalată':'Instalează AVYRON OS'}</DialogTitle><DialogDescription>Același cont și aceleași date, sincronizate online cu platforma internă.</DialogDescription></DialogHeader>{installed?<p>Accesezi deja aplicația în mod standalone.</p>:<><p className="text-sm">Instalarea adaugă Avyron pe ecranul principal. Întregul site rămâne accesibil, iar dashboardul respectă permisiunile contului staff.</p>{available&&<Button disabled={busy} onClick={()=>void install()}>Instalează aplicația</Button>}<ol className="list-decimal space-y-3 pl-5 text-sm"><li><strong>iPhone / iPad:</strong> deschide site-ul în Safari, apasă Partajare, apoi „Adaugă pe ecranul principal” și activează deschiderea ca aplicație dacă apare opțiunea.</li><li><strong>Android:</strong> în Chrome, folosește butonul de instalare sau meniul ⋮ → „Instalează aplicația” / „Adaugă pe ecranul de pornire”.</li><li><strong>Mac / Windows:</strong> folosește instalarea din bara browserului; în Safari pe Mac, „Adaugă în Dock”.</li></ol></>}<p className="text-xs text-muted-foreground">La prima deschidere poate fi necesară autentificarea din nou. Datele private necesită internet și nu sunt salvate offline.</p>{message&&<p role="status" className="text-sm">{message}</p>}</DialogContent></Dialog></>;
}
export function AppConnectivity(){
 const [online,setOnline]=useState(navigator.onLine),[update,setUpdate]=useState<ServiceWorkerRegistration|null>(null);
 useEffect(()=>{if('serviceWorker' in navigator)void navigator.serviceWorker.getRegistration().then(r=>{if(r?.waiting)setUpdate(r);}).catch(()=>{});const on=()=>setOnline(navigator.onLine),ready=(e:Event)=>setUpdate((e as CustomEvent<ServiceWorkerRegistration>).detail);window.addEventListener('online',on);window.addEventListener('offline',on);window.addEventListener('avyron:pwa-update',ready);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',on);window.removeEventListener('avyron:pwa-update',ready);};},[]);
 return <>{!online&&<div role="status" className="flex items-center gap-2 bg-amber-950 px-4 py-2 text-sm text-amber-100"><WifiOff className="size-4"/>Offline · datele pot fi vechi; modificările necesită conexiune.</div>}{update&&<div role="status" className="flex flex-wrap items-center gap-2 bg-violet-950 px-4 py-2 text-sm text-violet-100">Actualizare disponibilă. Salvează lucrul înainte de reîncărcare.<Button size="sm" onClick={()=>{navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});update.waiting?.postMessage('ACTIVATE_UPDATE');}}><RefreshCw className="mr-2 size-4"/>Actualizează aplicația</Button></div>}</>;
}
