import { useCallback, useEffect, useMemo, useState } from "react";
import { Link2, Database, FileCheck2, Github, Globe2, PlugZap, Plus, Search, ShieldCheck, Sparkles, WandSparkles, Workflow, ExternalLink, Upload, CheckCircle2, XCircle, Clock3, Settings2 } from "lucide-react";
import { toast } from "sonner";
import PageBackLink from "@/components/site/PageBackLink";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";
import { engineApi, type EngineBinding, type EngineCapability, type EngineOverview, type EngineSource, type EngineSourceDetail, type EngineSuggestion } from "@/lib/engineApi";

type View = "sources" | "suggestions" | "bindings" | "governance";
const statusLabel: Record<string, string> = {
  suggested: "Sugestie", reviewing: "În verificare", approved: "Aprobat", active: "Activ",
  paused: "Pauză", rejected: "Respins", archived: "Arhivat", unverified: "Neverificat",
  observed: "Observat", verified: "Verificat", stale: "Expirat", blocked: "Blocat",
  pending: "În așteptare", reviewed: "Revizuit", restricted: "Restricționat",
  discovered: "Descoperit", validated: "Validat", ready: "Gata", uploaded: "Încărcat",
};
const statusTone = (status: string) => status === "active" || status === "ready" || status === "verified" || status === "approved"
  ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-600"
  : status === "blocked" || status === "rejected"
    ? "border-destructive/30 bg-destructive/10 text-destructive"
    : status === "reviewing" || status === "pending" || status === "unverified"
      ? "border-amber-500/30 bg-amber-500/10 text-amber-700"
      : "border-border bg-muted/50 text-muted-foreground";
const formatDate = (value: number | null | undefined) => value ? new Intl.DateTimeFormat("ro-RO", { dateStyle: "medium" }).format(new Date(value)) : "—";
const selectClass = "h-10 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring";

export default function AvyEngine() {
  const [view, setView] = useState<View>("sources");
  const [overview, setOverview] = useState<EngineOverview | null>(null), [sources, setSources] = useState<EngineSource[]>([]);
  const [capabilities, setCapabilities] = useState<Array<EngineCapability & { source_name: string; source_status: string }>>([]);
  const [suggestions, setSuggestions] = useState<EngineSuggestion[]>([]), [bindings, setBindings] = useState<EngineBinding[]>([]);
  const [detail, setDetail] = useState<EngineSourceDetail | null>(null), [sheetOpen, setSheetOpen] = useState(false);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(""), [query, setQuery] = useState("");
  const [sourceDialog, setSourceDialog] = useState(false), [suggestionDialog, setSuggestionDialog] = useState(false), [bindingDialog, setBindingDialog] = useState(false), [capabilityDialog, setCapabilityDialog] = useState(false), [connectorDialog, setConnectorDialog] = useState(false);
  const [sourceForm, setSourceForm] = useState({ name: "", canonicalUrl: "https://", sourceType: "website", accessMode: "public", pricingModel: "unknown", summary: "", accountLabel: "" });
  const [suggestionForm, setSuggestionForm] = useState({ name: "", canonicalUrl: "https://", sourceType: "website", rationale: "" });
  const [capabilityForm, setCapabilityForm] = useState({ name: "", category: "ui_component", summary: "", deliveryMethod: "manual", availability: "unknown", riskLevel: "medium", documentationUrl: "" });
  const [bindingForm, setBindingForm] = useState({ capabilityId: "", targetType: "avyron_os", targetKey: "core", purpose: "", visibility: "internal" });
  const [connectorForm, setConnectorForm] = useState({ name: "", kind: "public_http", endpointUrl: "https://", authType: "none", capabilityId: "" });
  const [sourceConfig, setSourceConfig] = useState({ name: "", summary: "", accountLabel: "", accessMode: "public", lifecycleStatus: "reviewing", verificationStatus: "unverified", securityStatus: "pending", pricingModel: "unknown", robotsReviewed: false, termsReviewed: false, discoveryEnabled: false });
  const [policyForm, setPolicyForm] = useState({ enabled: false, frequencyDays: "30", maxSourcesPerRun: "1" });

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const [o, s, c, sg, b] = await Promise.all([engineApi.overview(), engineApi.sources(), engineApi.capabilities(), engineApi.suggestions(), engineApi.bindings()]);
      setOverview(o); setSources(s.data); setCapabilities(c.data); setSuggestions(sg.data); setBindings(b.data);
      if (o.discoveryPolicy) setPolicyForm({ enabled: o.discoveryPolicy.enabled === 1, frequencyDays: String(o.discoveryPolicy.frequency_days), maxSourcesPerRun: String(o.discoveryPolicy.max_sources_per_run) });
      if (!bindingForm.capabilityId && c.data[0]) setBindingForm((form) => ({ ...form, capabilityId: c.data[0].id }));
    } catch (cause) { setError(cause instanceof Error ? cause.message : "AVY Engine nu a putut fi încărcat."); }
    finally { setLoading(false); }
  }, [bindingForm.capabilityId]);

  useEffect(() => { void load(); }, [load]);
  useEffect(() => { void import("@/lib/seo").then(({ setPageMeta }) => setPageMeta({ title: "AVY Engine — AVYRON OS", description: "Registru intern de resurse și capabilități aprobate.", path: "/intern/avy-engine", robots: "noindex, nofollow" })); }, []);

  const openSource = async (source: EngineSource) => {
    setSheetOpen(true); setDetail(null);
    try {
      const data = await engineApi.source(source.id); setDetail(data);
      setSourceConfig({ name: data.source.name, summary: data.source.summary, accountLabel: data.source.account_label || "", accessMode: data.source.access_mode, lifecycleStatus: data.source.lifecycle_status, verificationStatus: data.source.verification_status, securityStatus: data.source.security_status, pricingModel: data.source.pricing_model, robotsReviewed: data.source.robots_reviewed === 1, termsReviewed: data.source.terms_reviewed === 1, discoveryEnabled: data.source.discovery_enabled === 1 });
    } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Sursa nu poate fi deschisă."); setSheetOpen(false); }
  };
  const reloadDetail = async () => { if (detail) setDetail(await engineApi.source(detail.source.id)); await load(); };
  const act = async (work: () => Promise<unknown>, success: string, refresh = true) => {
    setBusy(true); try { await work(); toast.success(success); if (refresh) await load(); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Operația nu a putut fi finalizată."); } finally { setBusy(false); }
  };
  const createSource = () => act(async () => { await engineApi.createSource({ ...sourceForm, accountLabel: sourceForm.accountLabel || null }); setSourceDialog(false); setSourceForm({ name: "", canonicalUrl: "https://", sourceType: "website", accessMode: "public", pricingModel: "unknown", summary: "", accountLabel: "" }); }, "Sursa a fost adăugată pentru verificare.");
  const createSuggestion = () => act(async () => { await engineApi.createSuggestion(suggestionForm); setSuggestionDialog(false); setSuggestionForm({ name: "", canonicalUrl: "https://", sourceType: "website", rationale: "" }); }, "Sugestia a intrat în fluxul de aprobare.");
  const saveSourceConfig = () => detail && act(async () => { await engineApi.updateSource(detail.source.id, sourceConfig); await reloadDetail(); }, "Regulile sursei au fost actualizate.", false);
  const createCapability = () => detail && act(async () => { await engineApi.createCapability(detail.source.id, { ...capabilityForm, documentationUrl: capabilityForm.documentationUrl || null }); setCapabilityDialog(false); setCapabilityForm({ name: "", category: "ui_component", summary: "", deliveryMethod: "manual", availability: "unknown", riskLevel: "medium", documentationUrl: "" }); await reloadDetail(); }, "Capabilitatea a fost adăugată.", false);
  const createConnector = () => detail && act(async () => { await engineApi.createConnector(detail.source.id, { ...connectorForm, endpointUrl: connectorForm.kind === "manual_import" ? null : connectorForm.endpointUrl, capabilityId: connectorForm.capabilityId || null }); setConnectorDialog(false); setConnectorForm({ name: "", kind: "public_http", endpointUrl: "https://", authType: "none", capabilityId: "" }); await reloadDetail(); }, "Conectorul a fost înregistrat fără credențiale.", false);
  const uploadDocument = (file: File) => detail && act(async () => { await engineApi.uploadDocument(detail.source.id, file, "documentation"); await reloadDetail(); }, "Documentul a fost stocat privat pentru revizuire.", false);
  const createBinding = () => act(async () => { await engineApi.createBinding(bindingForm); setBindingDialog(false); setBindingForm((form) => ({ ...form, targetKey: "", purpose: "" })); }, "Legătura a fost creată ca propunere.");
  const runDiscovery = () => detail && act(async () => { const result = await engineApi.discover(detail.source.id); toast.info(`${result.count} sugestii noi necesită aprobare.`); await reloadDetail(); }, "Analiza controlată s-a încheiat.", false);
  const savePolicy = () => act(() => engineApi.updateDiscoveryPolicy({ enabled: policyForm.enabled, frequencyDays: Number(policyForm.frequencyDays), maxSourcesPerRun: Number(policyForm.maxSourcesPerRun) }), "Politica de descoperire a fost actualizată.");

  const filteredSources = useMemo(() => { const q = query.trim().toLowerCase(); return !q ? sources : sources.filter((source) => `${source.name} ${source.canonical_url} ${source.source_type}`.toLowerCase().includes(q)); }, [sources, query]);
  const tabs: Array<{ id: View; label: string; count?: number }> = [
    { id: "sources", label: "Surse", count: sources.length }, { id: "suggestions", label: "Sugestii", count: overview?.suggestions.pending },
    { id: "bindings", label: "Utilizare", count: bindings.length }, { id: "governance", label: "Control" },
  ];

  return (
    <main className="min-h-screen bg-[radial-gradient(circle_at_top_right,rgba(6,182,212,.09),transparent_32%),hsl(var(--secondary)/.3)] px-4 py-7 sm:px-6">
      <div className="mx-auto max-w-7xl space-y-6">
        <div className="flex flex-wrap items-center justify-between gap-3"><PageBackLink to="/profil" label="Dashboard" /><Badge variant="outline" className="gap-1.5 border-cyan-500/30 bg-cyan-500/10 text-cyan-700"><ShieldCheck className="size-3.5" /> Control super admin</Badge></div>
        <header className="relative overflow-hidden rounded-3xl border border-cyan-500/20 bg-card/85 p-6 shadow-sm backdrop-blur-xl sm:p-8">
          <div className="absolute -right-16 -top-20 size-64 rounded-full bg-cyan-500/10 blur-3xl" />
          <div className="relative flex flex-col justify-between gap-6 lg:flex-row lg:items-end">
            <div className="max-w-3xl"><p className="flex items-center gap-2 font-mono text-[11px] uppercase tracking-[.22em] text-cyan-600"><Sparkles className="size-4" /> AVYRON capability control plane</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">AVY Engine</h1><p className="mt-3 text-sm leading-6 text-muted-foreground sm:text-base">Surse, funcții, documentație și integrări verificate înainte de a ajunge la agenți, produse sau proiecte. Nimic extern nu este executat ori publicat automat.</p></div>
            <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setSuggestionDialog(true)}><WandSparkles className="mr-2 size-4" /> Propune resursă</Button><Button onClick={() => setSourceDialog(true)}><Plus className="mr-2 size-4" /> Adaugă sursă</Button></div>
          </div>
        </header>

        {error && <div className="rounded-2xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{error} <Button className="ml-2" size="sm" variant="outline" onClick={() => void load()}>Reîncearcă</Button></div>}
        <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4" aria-label="Sumar AVY Engine">
          {[
            [Database, "Surse", overview?.sources.total || 0, `${overview?.sources.active || 0} active`],
            [Sparkles, "Capabilități", overview?.capabilities.total || 0, `${overview?.capabilities.ready || 0} gata de utilizare`],
            [FileCheck2, "Documente", overview?.documents.total || 0, `${overview?.documents.pending || 0} de revizuit`],
            [Workflow, "Legături", overview?.bindings.total || 0, `${overview?.bindings.active || 0} active`],
          ].map(([Icon, label, value, note]) => { const KpiIcon = Icon as typeof Database; return <div key={String(label)} className="rounded-2xl border bg-card/75 p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{String(label)}</span><KpiIcon className="size-4 text-cyan-600" /></div><p className="mt-3 text-2xl font-semibold">{String(value)}</p><p className="mt-1 text-xs text-muted-foreground">{String(note)}</p></div>; })}
        </section>

        <section className="rounded-2xl border bg-card/80 p-2 shadow-sm">
          <div className="flex flex-wrap gap-1" role="tablist">{tabs.map((item) => <button key={item.id} type="button" role="tab" aria-selected={view === item.id} onClick={() => setView(item.id)} className={`rounded-xl px-4 py-2.5 text-sm font-medium transition ${view === item.id ? "bg-foreground text-background shadow" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}>{item.label}{item.count !== undefined && <span className="ml-2 opacity-70">{item.count}</span>}</button>)}</div>
        </section>

        {loading ? <div className="h-72 animate-pulse rounded-2xl bg-muted/50" aria-label="Se încarcă AVY Engine" /> : view === "sources" ? (
          <section className="space-y-4">
            <div className="relative max-w-xl"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Caută platformă, domeniu sau tip…" /></div>
            <div className="grid gap-3 lg:grid-cols-2">{filteredSources.map((source) => <button key={source.id} type="button" onClick={() => void openSource(source)} className="group rounded-2xl border bg-card p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-cyan-500/35 hover:shadow-md">
              <div className="flex items-start justify-between gap-4"><div className="flex min-w-0 gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-cyan-500/10 text-cyan-700">{source.source_type === "repository" ? <Github className="size-5" /> : <Globe2 className="size-5" />}</span><div className="min-w-0"><h2 className="truncate font-semibold">{source.name}</h2><p className="mt-0.5 truncate text-xs text-muted-foreground">{source.canonical_url}</p></div></div><ExternalLink className="size-4 shrink-0 text-muted-foreground transition group-hover:text-cyan-600" /></div>
              <p className="mt-4 line-clamp-2 min-h-10 text-sm leading-5 text-muted-foreground">{source.summary || "Descrierea trebuie configurată."}</p>
              <div className="mt-4 flex flex-wrap items-center gap-2"><Badge variant="outline" className={statusTone(source.lifecycle_status)}>{statusLabel[source.lifecycle_status] || source.lifecycle_status}</Badge><Badge variant="outline" className={statusTone(source.verification_status)}>{statusLabel[source.verification_status] || source.verification_status}</Badge><span className="ml-auto text-xs text-muted-foreground">{source.capability_count || 0} funcții · {source.document_count || 0} documente</span></div>
            </button>)}</div>
          </section>
        ) : view === "suggestions" ? (
          <section className="space-y-3">{suggestions.length === 0 ? <Empty icon={WandSparkles} title="Nicio sugestie în așteptare" text="Sugestiile manuale sau ale agentului vor apărea aici înainte de aprobare." /> : suggestions.map((suggestion) => <article key={suggestion.id} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{suggestion.name}</h2><Badge variant="outline" className={statusTone(suggestion.status)}>{statusLabel[suggestion.status] || suggestion.status}</Badge><Badge variant="secondary">{suggestion.suggested_by_kind === "agent" ? "AVY Engine Scout" : "Manual"}</Badge></div><a className="mt-1 inline-flex items-center gap-1 text-xs text-cyan-700 hover:underline" href={suggestion.canonical_url} target="_blank" rel="noreferrer">{suggestion.canonical_url}<ExternalLink className="size-3" /></a><p className="mt-3 max-w-3xl text-sm text-muted-foreground">{suggestion.rationale}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={() => void act(() => engineApi.reviewSuggestion(suggestion.id, "rejected"), "Sugestia a fost respinsă.")}><XCircle className="mr-1.5 size-4" /> Respinge</Button><Button size="sm" disabled={busy} onClick={() => void act(() => engineApi.promoteSuggestion(suggestion.id), "Sugestia a devenit sursă aprobată pentru verificare.")}><CheckCircle2 className="mr-1.5 size-4" /> Aprobă ca sursă</Button></div></div></article>)}</section>
        ) : view === "bindings" ? (
          <section className="space-y-4"><div className="flex items-center justify-between gap-3"><p className="max-w-2xl text-sm text-muted-foreground">Legăturile controlează ce funcție poate fi utilizată de AVYRON OS, un agent, produs, proiect sau pagină. Publicarea necesită o aprobare separată.</p><Button onClick={() => setBindingDialog(true)}><Link2 className="mr-2 size-4" /> Leagă o funcție</Button></div>{bindings.length === 0 ? <Empty icon={Link2} title="Nicio funcție distribuită" text="Validează întâi o capabilitate, apoi creează o legătură controlată." /> : <div className="space-y-2">{bindings.map((binding) => <article key={binding.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border bg-card p-4"><div><div className="flex flex-wrap items-center gap-2"><strong>{binding.capability_name}</strong><Badge variant="outline" className={statusTone(binding.status)}>{statusLabel[binding.status] || binding.status}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{binding.source_name} → {binding.target_type}:{binding.target_key}</p><p className="mt-2 text-sm text-muted-foreground">{binding.purpose}</p></div><div className="flex gap-2">{binding.status !== "active" && <Button size="sm" disabled={busy} onClick={() => void act(() => engineApi.updateBinding(binding.id, "active"), "Legătura a fost activată.")}>Activează</Button>}<Button size="sm" variant="outline" disabled={busy} onClick={() => void act(() => engineApi.updateBinding(binding.id, "paused"), "Legătura a fost pusă pe pauză.")}>Pauză</Button></div></article>)}</div>}</section>
        ) : (
          <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><Settings2 className="size-5 text-cyan-600" /><h2 className="font-semibold">Descoperire periodică</h2></div><p className="mt-2 text-sm text-muted-foreground">Agentul inspectează numai surse active, cu termeni și robots verificate. Orice rezultat rămâne sugestie până la aprobarea umană.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Interval (zile)"><Input type="number" min={7} max={180} value={policyForm.frequencyDays} onChange={(event) => setPolicyForm((form) => ({ ...form, frequencyDays: event.target.value }))} /></Field><Field label="Surse / rulare"><Input type="number" min={1} max={5} value={policyForm.maxSourcesPerRun} onChange={(event) => setPolicyForm((form) => ({ ...form, maxSourcesPerRun: event.target.value }))} /></Field></div><div className="mt-4 flex items-center justify-between rounded-xl border p-3"><div><p className="text-sm font-medium">Program automat</p><p className="text-xs text-muted-foreground">{policyForm.enabled ? "Activat cu porți de cost și securitate" : "Dezactivat implicit"}</p></div><Button variant={policyForm.enabled ? "default" : "outline"} onClick={() => setPolicyForm((form) => ({ ...form, enabled: !form.enabled }))}>{policyForm.enabled ? "Activ" : "Inactiv"}</Button></div><Button className="mt-4 w-full" disabled={busy} onClick={() => void savePolicy()}>Salvează politica</Button></div>
          <div className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-emerald-600" /><h2 className="font-semibold">Porți obligatorii</h2></div><div className="mt-5 space-y-3">{["URL HTTPS public și verificat contra SSRF", "Termeni, robots și licență revizuite", "Fișiere private, neverificate și neexecutabile", "Agent limitat la linkurile observate", "AI Cost Guard înainte de Workers AI", "Activare și publicare numai prin super admin"].map((item, index) => <div key={item} className="flex gap-3 rounded-xl bg-muted/50 p-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-emerald-500/10 text-xs font-semibold text-emerald-700">{index + 1}</span><span className="text-sm">{item}</span></div>)}</div></div></section>
        )}
      </div>

      <Sheet open={sheetOpen} onOpenChange={setSheetOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>{detail?.source.name || "Sursă AVY Engine"}</SheetTitle><SheetDescription>Configurare, funcții, conectori și documente într-un singur profil.</SheetDescription></SheetHeader>{detail ? <div className="mt-6 space-y-6">
        <div className="rounded-2xl border bg-muted/35 p-4"><a className="inline-flex items-center gap-1 text-sm font-medium text-cyan-700 hover:underline" href={detail.source.canonical_url} target="_blank" rel="noreferrer">{detail.source.canonical_url}<ExternalLink className="size-3.5" /></a><p className="mt-2 text-sm leading-6 text-muted-foreground">{detail.source.summary}</p><div className="mt-3 flex flex-wrap gap-2"><Badge variant="outline" className={statusTone(detail.source.lifecycle_status)}>{statusLabel[detail.source.lifecycle_status] || detail.source.lifecycle_status}</Badge><Badge variant="outline" className={statusTone(detail.source.security_status)}>{statusLabel[detail.source.security_status] || detail.source.security_status}</Badge><Badge variant="secondary">{detail.source.pricing_model}</Badge></div></div>
        <SectionTitle title="Control și aprobare" action={<Button size="sm" disabled={busy} onClick={() => void saveSourceConfig()}>Salvează</Button>} />
        <div className="space-y-3">
          <Field label="Nume intern"><Input value={sourceConfig.name} onChange={(event) => setSourceConfig((form) => ({ ...form, name: event.target.value }))} /></Field>
          <Field label="Rezumat verificabil"><Textarea value={sourceConfig.summary} onChange={(event) => setSourceConfig((form) => ({ ...form, summary: event.target.value }))} /></Field>
          <Field label="Cont / alias intern (fără parolă)"><Input value={sourceConfig.accountLabel} onChange={(event) => setSourceConfig((form) => ({ ...form, accountLabel: event.target.value }))} placeholder="ex. cont Avyron" /></Field>
        </div>
        <div className="grid gap-3 sm:grid-cols-2"><Field label="Stare"><select className={selectClass} value={sourceConfig.lifecycleStatus} onChange={(event) => setSourceConfig((form) => ({ ...form, lifecycleStatus: event.target.value }))}>{["reviewing","approved","active","paused","rejected"].map((value) => <option key={value} value={value}>{statusLabel[value] || value}</option>)}</select></Field><Field label="Verificare"><select className={selectClass} value={sourceConfig.verificationStatus} onChange={(event) => setSourceConfig((form) => ({ ...form, verificationStatus: event.target.value }))}>{["unverified","observed","verified","stale","blocked"].map((value) => <option key={value} value={value}>{statusLabel[value] || value}</option>)}</select></Field><Field label="Securitate"><select className={selectClass} value={sourceConfig.securityStatus} onChange={(event) => setSourceConfig((form) => ({ ...form, securityStatus: event.target.value }))}>{["pending","reviewed","restricted","blocked"].map((value) => <option key={value} value={value}>{statusLabel[value] || value}</option>)}</select></Field><Field label="Mod de acces"><select className={selectClass} value={sourceConfig.accessMode} onChange={(event) => setSourceConfig((form) => ({ ...form, accessMode: event.target.value }))}>{["public","account_required","oauth","api_key","mixed"].map((value) => <option key={value} value={value}>{value}</option>)}</select></Field><Field label="Acces comercial"><select className={selectClass} value={sourceConfig.pricingModel} onChange={(event) => setSourceConfig((form) => ({ ...form, pricingModel: event.target.value }))}>{["unknown","free","freemium","paid","mixed"].map((value) => <option key={value} value={value}>{value}</option>)}</select></Field></div><div className="space-y-2">{[["robotsReviewed","Robots/politica de acces revizuită"],["termsReviewed","Termeni și licență revizuite"],["discoveryEnabled","Permite analiză periodică"]] .map(([key,label]) => <label key={key} className="flex items-center justify-between rounded-xl border p-3 text-sm"><span>{label}</span><input type="checkbox" checked={Boolean(sourceConfig[key as keyof typeof sourceConfig])} onChange={(event) => setSourceConfig((form) => ({ ...form, [key]: event.target.checked }))} /></label>)}</div>
        {detail.source.lifecycle_status === "active" && <Button variant="outline" className="w-full" disabled={busy} onClick={() => void runDiscovery()}><WandSparkles className="mr-2 size-4" /> Analizează sursa cu AVY Engine Scout</Button>}
        <SectionTitle title="Capabilități" action={<Button size="sm" variant="outline" onClick={() => setCapabilityDialog(true)}><Plus className="mr-1 size-4" /> Adaugă</Button>} /><div className="space-y-2">{detail.capabilities.map((capability) => <div key={capability.id} className="rounded-xl border p-3"><div className="flex items-center justify-between gap-2"><div><p className="text-sm font-medium">{capability.name}</p><p className="text-xs text-muted-foreground">{capability.category} · {capability.delivery_method} · {capability.availability}</p></div><Badge variant="outline" className={statusTone(capability.implementation_status)}>{statusLabel[capability.implementation_status] || capability.implementation_status}</Badge></div><p className="mt-2 text-sm text-muted-foreground">{capability.summary}</p>{capability.implementation_status !== "ready" && <Button className="mt-3" size="sm" variant="outline" disabled={busy} onClick={() => void act(async () => { await engineApi.updateCapability(capability.id, "ready"); await reloadDetail(); }, "Capabilitatea a fost aprobată.", false)}>Aprobă pentru utilizare</Button>}</div>)}{detail.capabilities.length === 0 && <p className="text-sm text-muted-foreground">Nicio capabilitate documentată.</p>}</div>
        <SectionTitle title="Conectori" action={<Button size="sm" variant="outline" onClick={() => setConnectorDialog(true)}><Plus className="mr-1 size-4" /> Adaugă</Button>} /><div className="space-y-2">{detail.connectors.map((connector) => <div key={connector.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div className="flex items-center gap-3"><PlugZap className="size-4 text-cyan-600" /><div><p className="text-sm font-medium">{connector.name}</p><p className="text-xs text-muted-foreground">{connector.kind} · autentificare {connector.auth_type}</p></div></div><div className="flex items-center gap-2"><Badge variant="secondary">{connector.status}</Badge>{connector.status !== "testing" && connector.status !== "revoked" && <Button size="sm" variant="outline" disabled={busy} onClick={() => void act(async () => { await engineApi.updateConnector(connector.id, "testing"); await reloadDetail(); }, "Conectorul a intrat în testare, fără activare.", false)}>Testează</Button>}{connector.status !== "revoked" && <Button size="sm" variant="ghost" disabled={busy} onClick={() => void act(async () => { await engineApi.updateConnector(connector.id, "revoked"); await reloadDetail(); }, "Conectorul a fost revocat.", false)}>Revocă</Button>}</div></div>)}{detail.connectors.length === 0 && <p className="text-sm text-muted-foreground">Niciun conector configurat.</p>}</div>
        <SectionTitle title="Documentație privată" action={<Label className="cursor-pointer"><span className="inline-flex h-9 items-center rounded-md border px-3 text-sm font-medium"><Upload className="mr-2 size-4" /> Încarcă</span><input className="sr-only" type="file" accept=".pdf,.png,.jpg,.jpeg,.txt,.md,.json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadDocument(file); event.target.value = ""; }} /></Label>} /><div className="space-y-2">{detail.documents.map((document) => <div key={document.id} className="rounded-xl border p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{document.file_name}</p><p className="text-xs text-muted-foreground">{document.document_type} · {(document.size_bytes / 1024).toFixed(1)} KB · {document.trust_level}</p></div><Badge variant="outline" className={statusTone(document.status)}>{statusLabel[document.status] || document.status}</Badge></div><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={() => void engineApi.downloadDocument(document.id, document.file_name)}>Descarcă</Button>{document.status !== "approved" && <Button size="sm" disabled={busy} onClick={() => void act(async () => { await engineApi.updateDocument(document.id, { status: "approved", trustLevel: "reviewed", agentUsable: true }); await reloadDetail(); }, "Documentul a fost aprobat pentru agenți.", false)}>Aprobă</Button>}</div></div>)}{detail.documents.length === 0 && <p className="text-sm text-muted-foreground">Fișierele încărcate rămân neîncrezătoare până la revizuire.</p>}</div>
      </div> : <div className="mt-8 h-56 animate-pulse rounded-2xl bg-muted" />}</SheetContent></Sheet>

      <FormDialog open={sourceDialog} onOpenChange={setSourceDialog} title="Sursă nouă" description="Sursa intră în verificare și nu este folosită automat."><Field label="Nume"><Input value={sourceForm.name} onChange={(event) => setSourceForm((form) => ({ ...form, name: event.target.value }))} /></Field><Field label="URL HTTPS"><Input value={sourceForm.canonicalUrl} onChange={(event) => setSourceForm((form) => ({ ...form, canonicalUrl: event.target.value }))} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Tip"><select className={selectClass} value={sourceForm.sourceType} onChange={(event) => setSourceForm((form) => ({ ...form, sourceType: event.target.value }))}>{["website","platform","marketplace","repository","documentation","api","mcp"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Acces"><select className={selectClass} value={sourceForm.accessMode} onChange={(event) => setSourceForm((form) => ({ ...form, accessMode: event.target.value }))}>{["public","account_required","oauth","api_key","mixed"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Model comercial"><select className={selectClass} value={sourceForm.pricingModel} onChange={(event) => setSourceForm((form) => ({ ...form, pricingModel: event.target.value }))}>{["unknown","free","freemium","paid","mixed"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Cont / alias intern (fără parolă)"><Input value={sourceForm.accountLabel} onChange={(event) => setSourceForm((form) => ({ ...form, accountLabel: event.target.value }))} placeholder="ex. cont Avyron" /></Field></div><Field label="Rezumat"><Textarea value={sourceForm.summary} onChange={(event) => setSourceForm((form) => ({ ...form, summary: event.target.value }))} /></Field><Button disabled={busy} onClick={() => void createSource()}>Adaugă pentru verificare</Button></FormDialog>
      <FormDialog open={suggestionDialog} onOpenChange={setSuggestionDialog} title="Propune o resursă" description="Aprobarea creează doar o sursă în revizuire, nu o integrare activă."><Field label="Nume"><Input value={suggestionForm.name} onChange={(event) => setSuggestionForm((form) => ({ ...form, name: event.target.value }))} /></Field><Field label="URL HTTPS"><Input value={suggestionForm.canonicalUrl} onChange={(event) => setSuggestionForm((form) => ({ ...form, canonicalUrl: event.target.value }))} /></Field><Field label="Motiv"><Textarea value={suggestionForm.rationale} onChange={(event) => setSuggestionForm((form) => ({ ...form, rationale: event.target.value }))} /></Field><Button disabled={busy} onClick={() => void createSuggestion()}>Trimite spre aprobare</Button></FormDialog>
      <FormDialog open={capabilityDialog} onOpenChange={setCapabilityDialog} title="Capabilitate nouă" description="Descrie funcția observată fără a presupune licență sau compatibilitate."><Field label="Nume"><Input value={capabilityForm.name} onChange={(event) => setCapabilityForm((form) => ({ ...form, name: event.target.value }))} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Categorie"><select className={selectClass} value={capabilityForm.category} onChange={(event) => setCapabilityForm((form) => ({ ...form, category: event.target.value }))}>{["ui_component","section","template","effect","animation","prompt","agent","ai_tool","integration","api","mcp","plugin","skill","repository","documentation","asset"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Livrare"><select className={selectClass} value={capabilityForm.deliveryMethod} onChange={(event) => setCapabilityForm((form) => ({ ...form, deliveryMethod: event.target.value }))}>{["manual","copy","download","cli","api","mcp","git","plugin"].map((value) => <option key={value}>{value}</option>)}</select></Field></div><Field label="Descriere"><Textarea value={capabilityForm.summary} onChange={(event) => setCapabilityForm((form) => ({ ...form, summary: event.target.value }))} /></Field><Field label="Documentație HTTPS"><Input value={capabilityForm.documentationUrl} onChange={(event) => setCapabilityForm((form) => ({ ...form, documentationUrl: event.target.value }))} /></Field><Button disabled={busy} onClick={() => void createCapability()}>Adaugă ca descoperită</Button></FormDialog>
      <FormDialog open={connectorDialog} onOpenChange={setConnectorDialog} title="Conector nou" description="Înregistrează doar metadate. Cheile, tokenurile și parolele nu intră în browser sau D1."><Field label="Nume"><Input value={connectorForm.name} onChange={(event) => setConnectorForm((form) => ({ ...form, name: event.target.value }))} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Tip"><select className={selectClass} value={connectorForm.kind} onChange={(event) => setConnectorForm((form) => ({ ...form, kind: event.target.value }))}>{["public_http","api","mcp","git","oauth","manual_import"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Autentificare"><select className={selectClass} value={connectorForm.authType} onChange={(event) => setConnectorForm((form) => ({ ...form, authType: event.target.value }))}>{["none","oauth","api_key","bearer","account_session"].map((value) => <option key={value}>{value}</option>)}</select></Field></div>{connectorForm.kind !== "manual_import" && <Field label="Endpoint HTTPS"><Input value={connectorForm.endpointUrl} onChange={(event) => setConnectorForm((form) => ({ ...form, endpointUrl: event.target.value }))} /></Field>}<Field label="Capabilitate asociată (opțional)"><select className={selectClass} value={connectorForm.capabilityId} onChange={(event) => setConnectorForm((form) => ({ ...form, capabilityId: event.target.value }))}><option value="">Sursă generală</option>{detail?.capabilities.map((capability) => <option key={capability.id} value={capability.id}>{capability.name}</option>)}</select></Field><Button disabled={busy} onClick={() => void createConnector()}>Înregistrează fără activare</Button></FormDialog>
      <FormDialog open={bindingDialog} onOpenChange={setBindingDialog} title="Leagă o funcție" description="Legătura rămâne propusă până când sursa și funcția sunt aprobate."><Field label="Capabilitate"><select className={selectClass} value={bindingForm.capabilityId} onChange={(event) => setBindingForm((form) => ({ ...form, capabilityId: event.target.value }))}>{capabilities.map((capability) => <option key={capability.id} value={capability.id}>{capability.source_name} · {capability.name}</option>)}</select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Țintă"><select className={selectClass} value={bindingForm.targetType} onChange={(event) => setBindingForm((form) => ({ ...form, targetType: event.target.value }))}>{["avyron_os","agent","product","project","page"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Identificator"><Input value={bindingForm.targetKey} onChange={(event) => setBindingForm((form) => ({ ...form, targetKey: event.target.value }))} placeholder="ex. website-prezentare-premium" /></Field></div><Field label="Utilizare aprobată"><Textarea value={bindingForm.purpose} onChange={(event) => setBindingForm((form) => ({ ...form, purpose: event.target.value }))} /></Field><Button disabled={busy || !bindingForm.capabilityId} onClick={() => void createBinding()}>Creează propunerea</Button></FormDialog>
    </main>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>; }
function SectionTitle({ title, action }: { title: string; action?: React.ReactNode }) { return <div className="flex items-center justify-between gap-3 border-b pb-2"><h3 className="font-semibold">{title}</h3>{action}</div>; }
function FormDialog({ open, onOpenChange, title, description, children }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; description: string; children: React.ReactNode }) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-lg"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader><div className="space-y-4">{children}</div></DialogContent></Dialog>; }
function Empty({ icon: Icon, title, text }: { icon: typeof Clock3; title: string; text: string }) { return <div className="rounded-2xl border border-dashed bg-card/50 p-10 text-center"><Icon className="mx-auto size-7 text-muted-foreground" /><h2 className="mt-3 font-semibold">{title}</h2><p className="mx-auto mt-1 max-w-lg text-sm text-muted-foreground">{text}</p><Progress className="mx-auto mt-5 h-1 max-w-xs" value={0} /></div>; }
