import { useCallback, useEffect, useMemo, useState } from "react";
import {
  AlertTriangle, BarChart3, Bot, Building2, CreditCard,
  Gauge, Plus, Receipt, Search, ShieldCheck, TrendingDown, TrendingUp, Wallet,
} from "lucide-react";
import { toast } from "sonner";
import PageBackLink from "@/components/site/PageBackLink";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  BudgetProgress, ExpenseDetailDrawer, ExpenseRow, FinancialAlert, FinancialChart,
  FinancialSummaryCard, PaymentMethodMasked, QuotaProgress, UpcomingPayment,
} from "@/components/finance/FinanceComponents";
import { money } from "@/lib/financeFormat";
import {
  financeApi, type FinanceAccount, type FinanceAgentPolicy, type FinanceAlert as AlertRow, type FinanceBudget,
  type FinanceAnalytics, type FinanceExpense, type FinanceExpenseDetail, type FinanceOverview,
  type FinancePaymentMethod, type FinanceQuota, type FinanceRevenue,
} from "@/lib/financeApi";

type View = "overview" | "expenses" | "revenues" | "subscriptions" | "accounts" | "budgets" | "statistics" | "alerts" | "audit";
type CreateKind = "revenue" | "account" | "payment-method" | "budget" | "quota" | "agent-policy";
const views: Array<{ id: View; label: string; icon: typeof Wallet }> = [
  { id:"overview",label:"Overview",icon:BarChart3 }, { id:"expenses",label:"Cheltuieli",icon:TrendingDown },
  { id:"revenues",label:"Venituri",icon:TrendingUp }, { id:"subscriptions",label:"Abonamente & quotas",icon:Gauge },
  { id:"accounts",label:"Conturi & carduri",icon:CreditCard }, { id:"budgets",label:"Bugete",icon:Wallet },
  { id:"statistics",label:"Statistici",icon:BarChart3 }, { id:"alerts",label:"Alerte",icon:AlertTriangle },
  { id:"audit",label:"Audit",icon:ShieldCheck },
];
const field="w-full rounded-xl border border-border/70 bg-background px-3 py-2.5 text-sm outline-none focus-visible:ring-2 focus-visible:ring-violet-500/35";

export default function Finance({ embedded=false }: { embedded?: boolean }) {
  const [view,setView]=useState<View>("overview"),[overview,setOverview]=useState<FinanceOverview|null>(null);
  const [expenses,setExpenses]=useState<FinanceExpense[]>([]),[revenues,setRevenues]=useState<FinanceRevenue[]>([]);
  const [accounts,setAccounts]=useState<FinanceAccount[]>([]),[methods,setMethods]=useState<FinancePaymentMethod[]>([]);
  const [budgets,setBudgets]=useState<FinanceBudget[]>([]),[quotas,setQuotas]=useState<FinanceQuota[]>([]),[alerts,setAlerts]=useState<AlertRow[]>([]);
  const [agentPolicies,setAgentPolicies]=useState<FinanceAgentPolicy[]>([]);
  const [analytics,setAnalytics]=useState<FinanceAnalytics|null>(null);
  const [audit,setAudit]=useState<Array<{id:string;action:string;resource_type:string;resource_id:string|null;source:string;request_id:string|null;created_at:number}>>([]);
  const [vendors,setVendors]=useState<Array<{id:string;name:string;category:string;status:string}>>([]);
  const [projects,setProjects]=useState<Array<{id:string;name:string}>>([]),[clients,setClients]=useState<Array<{id:string;company_name:string}>>([]);
  const [loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState("");
  const [detail,setDetail]=useState<FinanceExpenseDetail|null>(null),[drawerOpen,setDrawerOpen]=useState(false),[createOpen,setCreateOpen]=useState(false),[busy,setBusy]=useState(false);
  const [createKind,setCreateKind]=useState<CreateKind|null>(null);
  const [period,setPeriod]=useState("current"),[customFrom,setCustomFrom]=useState(""),[customTo,setCustomTo]=useState("");
  const [expenseForm,setExpenseForm]=useState({vendorId:"",serviceName:"",category:"other",status:"needs_configuration",billingType:"recurring",billingCycle:"monthly",currency:"RON",grossAmount:"",nextBillingDate:"",notes:""});
  const [revenueForm,setRevenueForm]=useState({serviceName:"",revenueType:"digital_services",status:"draft",currency:"RON",grossAmount:"",invoiceNumber:"",clientId:"",projectId:""});
  const [accountForm,setAccountForm]=useState({name:"",institution:"",internalAlias:"",currency:"RON",ibanLast4:"",purpose:""});
  const [methodForm,setMethodForm]=useState({accountId:"",provider:"",alias:"",last4:"",currency:"RON",purpose:""});
  const [budgetForm,setBudgetForm]=useState({name:"",category:"general",currency:"RON",limit:"",hardStop:true});
  const [selectedQuota,setSelectedQuota]=useState<FinanceQuota|null>(null),[quotaForm,setQuotaForm]=useState({plan:"",total:"",used:"0",warning:"85",hardStop:true});
  const [selectedPolicy,setSelectedPolicy]=useState<FinanceAgentPolicy|null>(null),[policyForm,setPolicyForm]=useState({daily:"",monthly:"",maximum:"",currency:"RON",status:"needs_configuration"});

  const periodRange=useMemo(()=>{const end=Date.now(),d=new Date();if(period==="custom"&&customFrom&&customTo)return[new Date(`${customFrom}T00:00:00+03:00`).getTime(),new Date(`${customTo}T23:59:59+03:00`).getTime()] as const;if(period==="previous"){const from=new Date(d.getFullYear(),d.getMonth()-1,1).getTime();return[from,new Date(d.getFullYear(),d.getMonth(),1).getTime()-1] as const;} const months=period==="3m"?3:period==="6m"?6:period==="year"?d.getMonth()+1:1;return[new Date(d.getFullYear(),d.getMonth()-months+1,1).getTime(),end] as const;},[period,customFrom,customTo]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const[o,e,r,a,b,al,au,c,an]=await Promise.all([financeApi.overview(...periodRange),financeApi.expenses("limit=50"),financeApi.revenues(),financeApi.accounts(),financeApi.budgets(),financeApi.alerts(),financeApi.audit(),financeApi.config(),financeApi.analytics()]);setOverview(o);setExpenses(e.data);setRevenues(r.data);setAccounts(a.accounts);setMethods(a.methods);setBudgets(b.budgets);setQuotas(b.quotas);setAgentPolicies(b.policies||[]);setAlerts(al.data);setAudit(au.data);setVendors(c.vendors);setProjects(c.projects);setClients(c.clients);setAnalytics(an);if(!expenseForm.vendorId&&c.vendors[0])setExpenseForm((f)=>({...f,vendorId:c.vendors[0].id,category:c.vendors[0].category}));}catch(cause){setError(cause instanceof Error?cause.message:"Modulul financiar nu a putut fi încărcat.");}finally{setLoading(false);}},[periodRange,expenseForm.vendorId]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{void import("@/lib/seo").then(({setPageMeta})=>setPageMeta({title:"Financiar — AVYRON OS",description:"Control financiar intern Avyron.",path:"/finance",robots:"noindex, nofollow"}));},[]);
  const openExpense=async(row:FinanceExpense)=>{setDrawerOpen(true);setDetail(null);try{setDetail(await financeApi.expense(row.id));}catch(cause){toast.error(cause instanceof Error?cause.message:"Detaliile nu pot fi încărcate.");setDrawerOpen(false);}};
  const createExpense=async()=>{if(!expenseForm.vendorId||!expenseForm.serviceName.trim()){toast.error("Furnizorul și serviciul sunt obligatorii.");return;}setBusy(true);try{await financeApi.createExpense({vendorId:expenseForm.vendorId,serviceName:expenseForm.serviceName,category:expenseForm.category,status:expenseForm.status,billingType:expenseForm.billingType,billingCycle:expenseForm.billingCycle,currency:expenseForm.currency,grossAmountMinor:expenseForm.grossAmount?Math.round(Number(expenseForm.grossAmount)*100):null,nextBillingDate:expenseForm.nextBillingDate?new Date(`${expenseForm.nextBillingDate}T12:00:00+03:00`).getTime():null,notes:expenseForm.notes,source:"manual"});toast.success("Cheltuiala a fost creată și auditată.");setCreateOpen(false);setExpenseForm((f)=>({...f,serviceName:"",grossAmount:"",nextBillingDate:"",notes:""}));await load();}catch(cause){toast.error(cause instanceof Error?cause.message:"Cheltuiala nu a putut fi creată.");}finally{setBusy(false);}};
  const submitCreate=async()=>{if(!createKind)return;setBusy(true);try{
    if(createKind==="revenue"){
      if(!revenueForm.serviceName.trim()){toast.error("Serviciul este obligatoriu.");return;}
      await financeApi.createRevenue({serviceName:revenueForm.serviceName,revenueType:revenueForm.revenueType,status:revenueForm.status,currency:revenueForm.currency,grossAmountMinor:revenueForm.grossAmount?Math.round(Number(revenueForm.grossAmount)*100):null,invoiceNumber:revenueForm.invoiceNumber||null,clientId:revenueForm.clientId||null,projectId:revenueForm.projectId||null});
      setRevenueForm((form)=>({...form,serviceName:"",grossAmount:"",invoiceNumber:""}));
    }else if(createKind==="account"){
      if(!accountForm.name.trim()||!accountForm.institution.trim()||!accountForm.internalAlias.trim()){toast.error("Numele, instituția și aliasul sunt obligatorii.");return;}
      await financeApi.createAccount({...accountForm,ibanLast4:accountForm.ibanLast4||null,accountType:"bank",status:"needs_configuration"});
      setAccountForm({name:"",institution:"",internalAlias:"",currency:"RON",ibanLast4:"",purpose:""});
    }else if(createKind==="payment-method"){
      if(!methodForm.provider.trim()||!methodForm.alias.trim()){toast.error("Providerul și aliasul sunt obligatorii.");return;}
      await financeApi.createPaymentMethod({...methodForm,accountId:methodForm.accountId||null,last4:methodForm.last4||null,status:"active"});
      setMethodForm({accountId:"",provider:"",alias:"",last4:"",currency:"RON",purpose:""});
    }else if(createKind==="budget"){
      if(!budgetForm.name.trim()||!budgetForm.limit){toast.error("Numele și limita bugetului sunt obligatorii.");return;}
      const date=new Date(),start=new Date(date.getFullYear(),date.getMonth(),1).getTime(),end=new Date(date.getFullYear(),date.getMonth()+1,1).getTime();
      await financeApi.createBudget({name:budgetForm.name,category:budgetForm.category,currency:budgetForm.currency,limitMinor:Math.round(Number(budgetForm.limit)*100),period:"month",periodStart:start,periodEnd:end,hardStop:budgetForm.hardStop});
      setBudgetForm({name:"",category:"general",currency:"RON",limit:"",hardStop:true});
    }else if(createKind==="quota"){
      if(!selectedQuota){toast.error("Selectează o limită.");return;}
      await financeApi.updateQuota(selectedQuota.id,{plan:quotaForm.plan||null,quotaTotal:quotaForm.total===""?null:Number(quotaForm.total),quotaUsed:Number(quotaForm.used),warningThresholdBasisPoints:Math.round(Number(quotaForm.warning)*100),hardStopBeforePaid:quotaForm.hardStop,status:"active"});
      setSelectedQuota(null);
    }else{
      if(!selectedPolicy){toast.error("Selectează politica agentului.");return;}
      const amount=(value:string)=>value===""?null:Math.round(Number(value)*100);
      await financeApi.updateAgentPolicy(selectedPolicy.agent_slug,selectedPolicy.vendor_id,{dailyBudgetMinor:amount(policyForm.daily),monthlyBudgetMinor:amount(policyForm.monthly),maxRequestCostMinor:amount(policyForm.maximum),currency:policyForm.currency,status:policyForm.status});
      setSelectedPolicy(null);
    }
    toast.success("Configurarea financiară a fost salvată și auditată.");setCreateKind(null);await load();
  }catch(cause){toast.error(cause instanceof Error?cause.message:"Configurarea nu a putut fi salvată.");}finally{setBusy(false);}};
  const scanAlerts=async()=>{setBusy(true);try{await financeApi.scanAlerts();toast.success("Regulile financiare au fost reevaluate.");await load();}catch(cause){toast.error(cause instanceof Error?cause.message:"Alertele nu au putut fi reevaluate.");}finally{setBusy(false);}};
  const updateAlert=async(id:string,status:"acknowledged"|"resolved")=>{setBusy(true);try{await financeApi.updateAlert(id,status);await load();}catch(cause){toast.error(cause instanceof Error?cause.message:"Alerta nu a putut fi actualizată.");}finally{setBusy(false);}};
  const uploadExpenseDocument=async(file:File)=>{if(!detail)return;setBusy(true);try{await financeApi.uploadDocument("expense",detail.expense.id,file,"invoice");setDetail(await financeApi.expense(detail.expense.id));toast.success("Documentul a fost stocat privat și auditat.");}catch(cause){toast.error(cause instanceof Error?cause.message:"Documentul nu a putut fi încărcat.");}finally{setBusy(false);}};
  const downloadDocument=async(id:string,fileName:string)=>{try{await financeApi.downloadDocument(id,fileName);}catch(cause){toast.error(cause instanceof Error?cause.message:"Documentul nu a putut fi descărcat.");}};
  const shownExpenses=expenses.filter((row)=>`${row.vendor_name} ${row.service_name} ${row.category}`.toLowerCase().includes(search.toLowerCase()));

  return <main className={embedded?"space-y-5":"min-h-screen bg-secondary/30 px-4 py-7 sm:px-6"}><div className={embedded?"space-y-5":"mx-auto max-w-7xl space-y-5"}>
    {!embedded&&<PageBackLink to="/profil" label="Dashboard"/>}
    <header className="relative overflow-hidden rounded-3xl border border-violet-500/20 bg-card/75 p-6 shadow-sm sm:p-8"><div className="pointer-events-none absolute -right-24 -top-32 size-80 rounded-full bg-violet-500/10 blur-3xl"/><div className="relative flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-violet-500">AVYRON OS · Control plane intern</p><h1 className="mt-2 text-3xl font-semibold">Financiar</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Costuri, venituri, bugete și limite într-un singur sistem Cloudflare. Estimările sunt operaționale, nu contabilitate fiscală.</p></div><div className="flex flex-wrap justify-end gap-2"><select aria-label="Perioadă financiară" className={field} value={period} onChange={(e)=>setPeriod(e.target.value)}><option value="current">Luna curentă</option><option value="previous">Luna trecută</option><option value="3m">Ultimele 3 luni</option><option value="6m">Ultimele 6 luni</option><option value="year">Anul curent</option><option value="custom">Custom</option></select>{period==="custom"&&<><Input aria-label="De la" type="date" className="w-auto" value={customFrom} onChange={(e)=>setCustomFrom(e.target.value)}/><Input aria-label="Până la" type="date" className="w-auto" value={customTo} onChange={(e)=>setCustomTo(e.target.value)}/></>}{view==="expenses"&&<Button onClick={()=>setCreateOpen(true)}><Plus className="mr-2 size-4"/>Cheltuială</Button>}{view==="revenues"&&<Button onClick={()=>setCreateKind("revenue")}><Plus className="mr-2 size-4"/>Venit</Button>}{view==="accounts"&&<Button onClick={()=>setCreateKind("account")}><Plus className="mr-2 size-4"/>Cont</Button>}{view==="budgets"&&<Button onClick={()=>setCreateKind("budget")}><Plus className="mr-2 size-4"/>Buget</Button>}</div></div></header>
    <nav className="flex gap-1 overflow-x-auto rounded-2xl border border-border/70 bg-card/60 p-1.5" aria-label="Secțiuni financiare">{views.map((item)=>{const Icon=item.icon;return <button key={item.id} type="button" onClick={()=>setView(item.id)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-xs font-medium transition ${view===item.id?"bg-background shadow-sm":"text-muted-foreground hover:text-foreground"}`}><Icon className="size-3.5"/>{item.label}</button>;})}</nav>
    {loading&&<div className="h-72 animate-pulse rounded-2xl bg-card/50" aria-label="Se încarcă financiar"/>}
    {!loading&&error&&<div className="rounded-2xl border border-destructive/30 p-6"><p className="text-sm">{error}</p><Button className="mt-3" variant="outline" onClick={()=>void load()}>Reîncearcă</Button></div>}
    {!loading&&!error&&overview&&<>
      {view==="overview"&&<div className="space-y-5"><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><FinancialSummaryCard label="Cheltuieli" value={money(overview.kpis.expensesMinor)} icon={TrendingDown} tone="text-red-500"/><FinancialSummaryCard label="Venituri" value={money(overview.kpis.revenuesMinor)} icon={TrendingUp} tone="text-emerald-500"/><FinancialSummaryCard label="Profit estimat" value={money(overview.kpis.operatingProfitEstimateMinor)} hint="Management estimate" icon={Wallet}/><FinancialSummaryCard label="Costuri AI/API" value={money(overview.kpis.aiCostMinor)} icon={Bot}/><FinancialSummaryCard label="Abonamente active" value={String(overview.kpis.activeSubscriptions)} icon={Receipt}/><FinancialSummaryCard label="Publicitate" value={money(overview.kpis.advertisingMinor)} icon={TrendingDown}/><FinancialSummaryCard label="Cost / lead" value={money(overview.kpis.costPerLeadMinor)} icon={Gauge}/><FinancialSummaryCard label="Alerte critice" value={String(overview.kpis.criticalAlerts)} icon={AlertTriangle} tone="text-amber-500"/></section><details className="rounded-2xl border border-border/70 bg-card/60 p-4"><summary className="cursor-pointer text-sm font-medium">Mai mulți indicatori</summary><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><FinancialSummaryCard label="Facturi de plătit" value={String(overview.kpis.invoicesPayable)} icon={Receipt}/><FinancialSummaryCard label="Facturi de încasat" value={String(overview.kpis.invoicesReceivable)} icon={Receipt}/><FinancialSummaryCard label="Bugete active" value={String(overview.kpis.budgetCount)} hint={money(overview.kpis.budgetLimitMinor)} icon={Wallet}/><FinancialSummaryCard label="Economii free tiers" value={money(overview.kpis.freeTierSavingsMinor)} icon={Gauge}/></div></details><div className="grid gap-4 lg:grid-cols-3"><div className="lg:col-span-2 rounded-2xl border border-border/70 bg-card/70 p-5"><h2 className="text-sm font-semibold">Următoarea plată</h2><div className="mt-3"><UpcomingPayment payment={overview.kpis.nextPayment}/></div></div><div className="rounded-2xl border border-border/70 bg-card/70 p-5"><p className="font-mono text-[10px] uppercase text-muted-foreground">Free tiers</p><p className="mt-2 text-xl font-semibold">De configurat</p><p className="mt-1 text-xs text-muted-foreground">Economiile nu sunt estimate fără limite și tarife verificate.</p></div></div></div>}
      {view==="expenses"&&<section className="rounded-2xl border border-border/70 bg-card/70 p-4 sm:p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Cheltuieli</h2><p className="text-xs text-muted-foreground">{shownExpenses.length} intrări · click pentru detalii</p></div><div className="relative"><Search className="absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground"/><Input aria-label="Caută furnizor" className="w-64 pl-9" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Furnizor, serviciu…"/></div></div><div className="space-y-2">{shownExpenses.map((row)=><ExpenseRow key={row.id} expense={row} onOpen={()=>void openExpense(row)}/>)}</div></section>}
      {view==="revenues"&&<section className="rounded-2xl border border-border/70 bg-card/70 p-5"><h2 className="font-semibold">Venituri</h2><p className="mb-4 text-xs text-muted-foreground">Flux separat, corelat cu proiecte și clienți.</p><div className="space-y-2">{revenues.map((row)=><div key={row.id} className="grid gap-2 rounded-xl border border-border/65 p-3 sm:grid-cols-[1fr_auto_auto]"><div><p className="text-sm font-medium">{row.service_name}</p><p className="text-xs text-muted-foreground">{row.company_name||"General AVYRON"} · {row.revenue_type.replace(/_/g," ")}</p></div><p className="text-sm font-semibold">{money(row.gross_amount_minor,row.currency)}</p><span className="rounded-full bg-muted px-2 py-1 text-[9px] uppercase">{row.status}</span></div>)}{revenues.length===0&&<p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">Niciun venit introdus.</p>}</div></section>}
      {view==="subscriptions"&&<section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-border/70 bg-card/70 p-5"><h2 className="font-semibold">Free Tier & Quotas</h2><p className="mb-4 text-xs text-muted-foreground">FREE FIRST · hard stop implicit înainte de usage plătit.</p><div className="space-y-2">{quotas.map((quota)=><div key={quota.id} className="space-y-1"><QuotaProgress quota={quota}/><Button size="sm" variant="ghost" onClick={()=>{setSelectedQuota(quota);setQuotaForm({plan:quota.plan||"",total:quota.quota_total===null?"":String(quota.quota_total),used:String(quota.quota_used),warning:String(quota.warning_threshold_basis_points/100),hardStop:Boolean(quota.hard_stop_before_paid)});setCreateKind("quota");}}>Configurează</Button></div>)}{quotas.length===0&&<p className="rounded-xl border border-dashed p-5 text-center text-xs text-muted-foreground">Limitele nu sunt hardcodate. Configurează planurile din Super Admin.</p>}</div></div><div className="rounded-2xl border border-violet-500/20 bg-violet-500/5 p-5"><h2 className="flex items-center gap-2 font-semibold"><Bot className="size-4 text-violet-500"/>AI Cost Guard</h2><div className="mt-4 space-y-3 text-sm"><p>Agent → Budget Guard → Provider Quota → Execute</p><ol className="space-y-2 text-xs text-muted-foreground"><li>1. verifică permisiunea agent/provider</li><li>2. folosește free allowance</li><li>3. estimează costul și verifică bugetul</li><li>4. blochează sau cere aprobare la prag</li><li>5. deduplică prin idempotency key</li></ol></div></div><div className="rounded-2xl border border-border/70 bg-card/70 p-5 lg:col-span-2"><h2 className="font-semibold">Permisiuni agent → provider</h2><p className="mb-4 text-xs text-muted-foreground">Un agent nu poate apela providerul înainte ca politica și quota să fie activate explicit.</p><div className="grid gap-2 md:grid-cols-2">{agentPolicies.map((policy)=><div key={`${policy.agent_slug}:${policy.vendor_id}`} className="flex items-center justify-between gap-3 rounded-xl border border-border/65 p-3"><div><p className="text-sm font-medium">{policy.agent_name}</p><p className="text-[11px] text-muted-foreground">{policy.vendor_name} · {policy.status.replace(/_/g," ")}</p></div><Button size="sm" variant="outline" onClick={()=>{setSelectedPolicy(policy);setPolicyForm({daily:policy.daily_budget_minor===null?"":String(policy.daily_budget_minor/100),monthly:policy.monthly_budget_minor===null?"":String(policy.monthly_budget_minor/100),maximum:policy.max_request_cost_minor===null?"":String(policy.max_request_cost_minor/100),currency:policy.currency,status:policy.status});setCreateKind("agent-policy");}}>Configurează</Button></div>)}{agentPolicies.length===0&&<p className="text-sm text-muted-foreground">Nicio politică agent/provider disponibilă.</p>}</div></div></section>}
      {view==="accounts"&&<section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-border/70 bg-card/70 p-5"><h2 className="font-semibold">Conturi</h2><div className="mt-4 space-y-2">{accounts.map((account)=><div key={account.id} className="flex gap-3 rounded-xl border border-border/65 p-3"><Building2 className="size-4 text-cyan-500"/><div><p className="text-sm font-medium">{account.name}</p><p className="text-xs text-muted-foreground">{account.institution} · {account.currency} · {account.iban_last4?`•••• ${account.iban_last4}`:"IBAN neconfigurat"}</p><p className="mt-1 text-[10px] text-muted-foreground">{account.purpose}</p></div></div>)}</div></div><div className="rounded-2xl border border-border/70 bg-card/70 p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">Metode de plată mascate</h2><Button size="sm" variant="outline" onClick={()=>setCreateKind("payment-method")}><Plus className="mr-1 size-3"/>Metodă</Button></div><div className="mt-4 space-y-2">{methods.map((method)=><PaymentMethodMasked key={method.id} method={method}/>)}{methods.length===0&&<p className="rounded-xl border border-dashed p-5 text-center text-xs text-muted-foreground">Niciun card configurat. Nu se stochează număr complet, CVV sau PIN.</p>}</div></div></section>}
      {view==="budgets"&&<section className="rounded-2xl border border-border/70 bg-card/70 p-5"><h2 className="font-semibold">Bugete</h2><p className="mb-4 text-xs text-muted-foreground">General, AI, SaaS, Advertising, Lead Generation și infrastructură.</p><div className="grid gap-3 md:grid-cols-2">{budgets.map((budget)=><BudgetProgress key={budget.id} name={budget.name} limitMinor={budget.limit_minor} currency={budget.currency}/>)}{budgets.length===0&&<p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground md:col-span-2">Bugetele sunt configurabile; nicio limită financiară nu a fost inventată.</p>}</div></section>}
      {view==="statistics"&&<section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-border/70 bg-card/70 p-5"><h2 className="font-semibold">Cost breakdown</h2><div className="mt-4 space-y-2">{analytics?.categories.map((item)=><div key={item.category} className="flex justify-between rounded-lg bg-muted/45 p-3 text-sm"><span>{item.category.replace(/_/g," ")}</span><strong>{money(item.total_minor)}</strong></div>)}{!analytics?.categories.length&&<FinancialChart label="Cheltuieli pe categorie"/>}</div></div><div className="rounded-2xl border border-border/70 bg-card/70 p-5"><h2 className="font-semibold">Proiecții</h2><div className="mt-4 grid gap-2 sm:grid-cols-3 lg:grid-cols-1">{analytics?.projections.map((projection)=><div key={projection.months} className="rounded-xl border border-border/65 p-3"><p className="font-mono text-[10px] uppercase text-muted-foreground">{projection.months} luni</p><p className="mt-1 text-lg font-semibold">{money(projection.projectedMinor)}</p></div>)}</div><p className="mt-3 text-[10px] uppercase text-muted-foreground">Management estimate · recurente anualizate {money(analytics?.projections[0]?.annualizedRecurringMinor)}</p></div><div className="rounded-2xl border border-border/70 bg-card/70 p-5 lg:col-span-2"><h2 className="font-semibold">Profitabilitate per client</h2><div className="mt-4 grid gap-2 md:grid-cols-2">{analytics?.clients.filter((item)=>item.revenue_minor||item.direct_cost_minor).map((item)=><div key={item.id} className="rounded-xl border border-border/65 p-3"><div className="flex justify-between gap-3"><p className="text-sm font-medium">{item.company_name}</p><strong className="text-sm">{money(item.estimated_contribution_minor)}</strong></div><p className="mt-1 text-[10px] uppercase text-muted-foreground">Management estimate · venit {money(item.revenue_minor)} · cost direct {money(item.direct_cost_minor)}</p></div>)}{!analytics?.clients.some((item)=>item.revenue_minor||item.direct_cost_minor)&&<p className="text-sm text-muted-foreground">Date insuficiente pentru marje pe client.</p>}</div></div></section>}
      {view==="alerts"&&<section className="rounded-2xl border border-border/70 bg-card/70 p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">Alerte financiare</h2><Button size="sm" variant="outline" disabled={busy} onClick={()=>void scanAlerts()}>Reevaluează reguli</Button></div><div className="mt-4 space-y-2">{alerts.map((alert)=><div key={alert.id} className="space-y-2"><FinancialAlert alert={alert}/><div className="flex justify-end gap-2">{alert.status==="open"&&<Button size="sm" variant="ghost" disabled={busy} onClick={()=>void updateAlert(alert.id,"acknowledged")}>Confirmă</Button>}<Button size="sm" variant="ghost" disabled={busy} onClick={()=>void updateAlert(alert.id,"resolved")}>Rezolvă</Button></div></div>)}{alerts.length===0&&<p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">Nicio alertă activă.</p>}</div></section>}
      {view==="audit"&&<section className="rounded-2xl border border-border/70 bg-card/70 p-5"><h2 className="font-semibold">Istoric / Audit append-only</h2><div className="mt-4 space-y-2">{audit.map((event)=><div key={event.id} className="grid gap-1 rounded-xl border border-border/65 p-3 text-xs sm:grid-cols-[1fr_auto]"><p><strong>{event.action}</strong> · {event.resource_type}{event.resource_id?` / ${event.resource_id}`:""}</p><p className="text-muted-foreground">{new Date(event.created_at).toLocaleString("ro-RO",{timeZone:"Europe/Bucharest"})}</p></div>)}{audit.length===0&&<p className="text-sm text-muted-foreground">Nicio modificare financiară.</p>}</div></section>}
    </>}
    <ExpenseDetailDrawer detail={detail} open={drawerOpen} onOpenChange={setDrawerOpen} onUpload={(file)=>void uploadExpenseDocument(file)} onDownload={(id,fileName)=>void downloadDocument(id,fileName)}/>
    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogHeader><DialogTitle>Cheltuială nouă</DialogTitle><DialogDescription>Date manuale, auditabile. Câmpurile necunoscute rămân neconfigurate.</DialogDescription></DialogHeader><div className="grid max-h-[65vh] gap-3 overflow-y-auto pr-1 sm:grid-cols-2"><div><Label>Furnizor</Label><select className={field} value={expenseForm.vendorId} onChange={(e)=>{const vendor=vendors.find((v)=>v.id===e.target.value);setExpenseForm({...expenseForm,vendorId:e.target.value,category:vendor?.category||"other"});}}>{vendors.map((v)=><option key={v.id} value={v.id}>{v.name}</option>)}</select></div><div><Label>Categorie</Label><Input value={expenseForm.category} readOnly/></div><div className="sm:col-span-2"><Label>Serviciu</Label><Input value={expenseForm.serviceName} onChange={(e)=>setExpenseForm({...expenseForm,serviceName:e.target.value})}/></div><div><Label>Cost brut</Label><Input type="number" min="0" step="0.01" placeholder="Lasă gol dacă nu este cunoscut" value={expenseForm.grossAmount} onChange={(e)=>setExpenseForm({...expenseForm,grossAmount:e.target.value})}/></div><div><Label>Monedă</Label><select className={field} value={expenseForm.currency} onChange={(e)=>setExpenseForm({...expenseForm,currency:e.target.value})}><option>RON</option><option>EUR</option><option>USD</option></select></div><div><Label>Status</Label><select className={field} value={expenseForm.status} onChange={(e)=>setExpenseForm({...expenseForm,status:e.target.value})}><option value="needs_configuration">Needs configuration</option><option value="active">Active</option><option value="free">Free</option><option value="trial">Trial</option><option value="payment_due">Payment due</option></select></div><div><Label>Următoarea plată</Label><Input type="date" value={expenseForm.nextBillingDate} onChange={(e)=>setExpenseForm({...expenseForm,nextBillingDate:e.target.value})}/></div><div className="sm:col-span-2"><Label>Notițe</Label><Textarea rows={3} value={expenseForm.notes} onChange={(e)=>setExpenseForm({...expenseForm,notes:e.target.value})}/></div></div><Button onClick={()=>void createExpense()} disabled={busy}>{busy?"Se salvează…":"Salvează"}</Button></DialogContent></Dialog>
    <Dialog open={createKind!==null} onOpenChange={(open)=>!open&&setCreateKind(null)}><DialogContent><DialogHeader><DialogTitle>{createKind==="revenue"?"Venit nou":createKind==="account"?"Cont nou":createKind==="payment-method"?"Metodă de plată mascată":createKind==="quota"?"Configurează free tier":createKind==="agent-policy"?"Politică agent/provider":"Buget nou"}</DialogTitle><DialogDescription>{createKind==="payment-method"?"Introdu numai alias și ultimele patru cifre. Numărul complet, CVV și PIN nu sunt acceptate.":"Configurare manuală protejată de MFA și audit server-side."}</DialogDescription></DialogHeader>
      {createKind==="revenue"&&<div className="grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Serviciu</Label><Input value={revenueForm.serviceName} onChange={(e)=>setRevenueForm({...revenueForm,serviceName:e.target.value})}/></div><div><Label>Tip</Label><select className={field} value={revenueForm.revenueType} onChange={(e)=>setRevenueForm({...revenueForm,revenueType:e.target.value})}><option value="website_development">Dezvoltare website</option><option value="digital_services">Servicii digitale</option><option value="maintenance">Mentenanță</option><option value="hosting">Hosting</option><option value="subscriptions">Abonamente</option><option value="ai_services">AI services</option><option value="seo">SEO</option><option value="marketing">Marketing</option><option value="digital_products">Produse digitale</option><option value="marketplace">Marketplace</option><option value="other">Altele</option></select></div><div><Label>Status</Label><select className={field} value={revenueForm.status} onChange={(e)=>setRevenueForm({...revenueForm,status:e.target.value})}><option value="draft">Draft</option><option value="invoiced">Facturat</option><option value="sent">Trimis</option><option value="partially_paid">Plătit parțial</option><option value="paid">Plătit</option><option value="overdue">Restant</option></select></div><div><Label>Valoare brută</Label><Input type="number" min="0" step="0.01" value={revenueForm.grossAmount} onChange={(e)=>setRevenueForm({...revenueForm,grossAmount:e.target.value})}/></div><div><Label>Monedă</Label><select className={field} value={revenueForm.currency} onChange={(e)=>setRevenueForm({...revenueForm,currency:e.target.value})}><option>RON</option><option>EUR</option><option>USD</option></select></div><div><Label>Client</Label><select className={field} value={revenueForm.clientId} onChange={(e)=>setRevenueForm({...revenueForm,clientId:e.target.value})}><option value="">General AVYRON</option>{clients.map((client)=><option key={client.id} value={client.id}>{client.company_name}</option>)}</select></div><div><Label>Proiect</Label><select className={field} value={revenueForm.projectId} onChange={(e)=>setRevenueForm({...revenueForm,projectId:e.target.value})}><option value="">Fără alocare</option>{projects.map((project)=><option key={project.id} value={project.id}>{project.name}</option>)}</select></div><div className="sm:col-span-2"><Label>Număr factură</Label><Input value={revenueForm.invoiceNumber} onChange={(e)=>setRevenueForm({...revenueForm,invoiceNumber:e.target.value})}/></div></div>}
      {createKind==="account"&&<div className="grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Nume cont</Label><Input value={accountForm.name} onChange={(e)=>setAccountForm({...accountForm,name:e.target.value})}/></div><div><Label>Instituție</Label><Input value={accountForm.institution} onChange={(e)=>setAccountForm({...accountForm,institution:e.target.value})}/></div><div><Label>Alias intern</Label><Input value={accountForm.internalAlias} onChange={(e)=>setAccountForm({...accountForm,internalAlias:e.target.value})}/></div><div><Label>Monedă</Label><select className={field} value={accountForm.currency} onChange={(e)=>setAccountForm({...accountForm,currency:e.target.value})}><option>RON</option><option>EUR</option><option>USD</option></select></div><div><Label>Ultimele caractere IBAN</Label><Input maxLength={4} autoComplete="off" value={accountForm.ibanLast4} onChange={(e)=>setAccountForm({...accountForm,ibanLast4:e.target.value.toUpperCase()})}/></div><div className="sm:col-span-2"><Label>Scop</Label><Input value={accountForm.purpose} onChange={(e)=>setAccountForm({...accountForm,purpose:e.target.value})}/></div></div>}
      {createKind==="payment-method"&&<div className="grid gap-3 sm:grid-cols-2"><div><Label>Provider</Label><Input value={methodForm.provider} onChange={(e)=>setMethodForm({...methodForm,provider:e.target.value})}/></div><div><Label>Alias</Label><Input value={methodForm.alias} onChange={(e)=>setMethodForm({...methodForm,alias:e.target.value})}/></div><div><Label>Cont asociat</Label><select className={field} value={methodForm.accountId} onChange={(e)=>setMethodForm({...methodForm,accountId:e.target.value})}><option value="">Neasociat</option>{accounts.map((account)=><option key={account.id} value={account.id}>{account.name}</option>)}</select></div><div><Label>Ultimele 4 cifre</Label><Input inputMode="numeric" maxLength={4} autoComplete="off" value={methodForm.last4} onChange={(e)=>setMethodForm({...methodForm,last4:e.target.value.replace(/\D/g,"")})}/></div><div><Label>Monedă</Label><select className={field} value={methodForm.currency} onChange={(e)=>setMethodForm({...methodForm,currency:e.target.value})}><option>RON</option><option>EUR</option><option>USD</option></select></div><div><Label>Scop</Label><Input value={methodForm.purpose} onChange={(e)=>setMethodForm({...methodForm,purpose:e.target.value})}/></div></div>}
      {createKind==="budget"&&<div className="grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Nume buget</Label><Input value={budgetForm.name} onChange={(e)=>setBudgetForm({...budgetForm,name:e.target.value})}/></div><div><Label>Categorie</Label><select className={field} value={budgetForm.category} onChange={(e)=>setBudgetForm({...budgetForm,category:e.target.value})}><option value="general">General AVYRON</option><option value="ai">AI</option><option value="saas">SaaS</option><option value="advertising">Publicitate</option><option value="lead_generation">Lead generation</option><option value="infrastructure">Infrastructură</option><option value="accounting">Contabilitate</option><option value="other">Altele</option></select></div><div><Label>Limită lunară</Label><Input type="number" min="0" step="0.01" value={budgetForm.limit} onChange={(e)=>setBudgetForm({...budgetForm,limit:e.target.value})}/></div><div><Label>Monedă</Label><select className={field} value={budgetForm.currency} onChange={(e)=>setBudgetForm({...budgetForm,currency:e.target.value})}><option>RON</option><option>EUR</option><option>USD</option></select></div><label className="flex items-center gap-2 self-end rounded-xl border border-border/70 px-3 py-2.5 text-sm"><input type="checkbox" checked={budgetForm.hardStop} onChange={(e)=>setBudgetForm({...budgetForm,hardStop:e.target.checked})}/>Hard stop la limită</label></div>}
      {createKind==="quota"&&<div className="grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Provider</Label><Input value={selectedQuota?.vendor_name||""} readOnly/></div><div><Label>Plan</Label><Input value={quotaForm.plan} onChange={(e)=>setQuotaForm({...quotaForm,plan:e.target.value})}/></div><div><Label>Tip limită</Label><Input value={selectedQuota?.quota_type||""} readOnly/></div><div><Label>Limită totală</Label><Input type="number" min="0" value={quotaForm.total} onChange={(e)=>setQuotaForm({...quotaForm,total:e.target.value})}/></div><div><Label>Utilizat</Label><Input type="number" min="0" value={quotaForm.used} onChange={(e)=>setQuotaForm({...quotaForm,used:e.target.value})}/></div><div><Label>Prag avertizare (%)</Label><Input type="number" min="1" max="100" step="1" value={quotaForm.warning} onChange={(e)=>setQuotaForm({...quotaForm,warning:e.target.value})}/></div><label className="flex items-center gap-2 self-end rounded-xl border border-border/70 px-3 py-2.5 text-sm"><input type="checkbox" checked={quotaForm.hardStop} onChange={(e)=>setQuotaForm({...quotaForm,hardStop:e.target.checked})}/>Oprește înainte de cost</label></div>}
      {createKind==="agent-policy"&&<div className="grid gap-3 sm:grid-cols-2"><div><Label>Agent</Label><Input value={selectedPolicy?.agent_name||""} readOnly/></div><div><Label>Provider</Label><Input value={selectedPolicy?.vendor_name||""} readOnly/></div><div><Label>Buget zilnic</Label><Input type="number" min="0" step="0.01" value={policyForm.daily} onChange={(e)=>setPolicyForm({...policyForm,daily:e.target.value})}/></div><div><Label>Buget lunar</Label><Input type="number" min="0" step="0.01" value={policyForm.monthly} onChange={(e)=>setPolicyForm({...policyForm,monthly:e.target.value})}/></div><div><Label>Cost maxim/request</Label><Input type="number" min="0" step="0.01" value={policyForm.maximum} onChange={(e)=>setPolicyForm({...policyForm,maximum:e.target.value})}/></div><div><Label>Monedă</Label><select className={field} value={policyForm.currency} onChange={(e)=>setPolicyForm({...policyForm,currency:e.target.value})}><option>RON</option><option>EUR</option><option>USD</option></select></div><div className="sm:col-span-2"><Label>Status</Label><select className={field} value={policyForm.status} onChange={(e)=>setPolicyForm({...policyForm,status:e.target.value})}><option value="needs_configuration">Needs configuration</option><option value="active">Active</option><option value="paused">Paused</option></select><p className="mt-1 text-[10px] text-muted-foreground">Activează numai după configurarea și verificarea limitei providerului.</p></div></div>}
      <Button onClick={()=>void submitCreate()} disabled={busy}>{busy?"Se salvează…":"Salvează"}</Button>
    </DialogContent></Dialog>
  </div></main>;
}
