import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {centersApi} from '@/lib/centersApi';
import {cfAuth} from '@/lib/cfAuth';
import {Notice} from './CenterPanels';
import {inputClass,panelClass,useCenterAction,useCenterData} from './centerHooks';
type Account={id:string;brand:string;provider:string;label:string;auth_method:string;login_url:string;external_id:string;api_version:string;status:string;revision:number;expires_at:number|null;has_secret:boolean;error_code:string|null};
type Device={id:string;label:string;status:string;last_seen_at:number;expires_at:number};
type Task={id:string;label:string;action:string;instructions:string;login_url:string};
const empty={brand:'avyron',provider:'instagram',label:'',auth_method:'oauth_token',login_url:'https://www.instagram.com/',external_id:'',api_version:'v26.0',expires_at:null as number|null};
export default function AccountsPanel(){
 const {data,error,loading,reload}=useCenterData<{data:Account[]}>('accounts'),{busy,act}=useCenterAction();const [form,setForm]=useState({...empty}),[edit,setEdit]=useState<Account|null>(null),[open,setOpen]=useState(false),[secretAccount,setSecretAccount]=useState<Account|null>(null),[secret,setSecret]=useState(''),[revealed,setRevealed]=useState(''),[reason,setReason]=useState('');
 useEffect(()=>{if(!revealed)return;const timer=setTimeout(()=>setRevealed(''),30000);const hide=()=>{if(document.hidden)setRevealed('');};document.addEventListener('visibilitychange',hide);return()=>{clearTimeout(timer);document.removeEventListener('visibilitychange',hide);};},[revealed]);
 const field=(key:keyof typeof empty,value:string)=>setForm(f=>({...f,[key]:value}));
 return <div className="space-y-5"><Notice error={error} loading={loading}/><div className={panelClass}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Conturi Avyron / Cutiuța Magică</h2><Button onClick={()=>{setEdit(null);setForm({...empty});setOpen(true);}}>Adaugă cont</Button></div><p className="mt-2 text-sm text-slate-400">Acces rezervat administratorilor principali. Token-urile rămân în seiful serverului; parolele se afișează temporar, cu motiv în jurnal.</p><div className="mt-4 grid gap-3 lg:grid-cols-2">{data?.data.map(a=><article key={a.id} className="min-w-0 rounded-xl border border-white/10 p-4"><h3 className="font-medium break-words">{a.label}</h3><p className="my-2 text-xs text-slate-400">{a.brand} · {a.provider} · {a.auth_method} · {a.status}</p>{a.error_code&&<p className="mb-2 text-xs text-amber-300">Verificare necesară: {a.error_code}</p>}<div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" asChild><a href={a.login_url} target="_blank" rel="noopener noreferrer">Deschide cont</a></Button><Button size="sm" variant="outline" onClick={()=>{setEdit(a);setForm(Object.fromEntries(Object.keys(empty).map(k=>[k,a[k as keyof Account]])) as typeof empty);setOpen(true);}}>Configurare</Button>{['api_token','oauth_token','password'].includes(a.auth_method)&&<Button size="sm" variant="outline" onClick={()=>{setSecret('');setReason('');setRevealed('');setSecretAccount(a);}}>Seif</Button>}{['api_token','oauth_token'].includes(a.auth_method)&&<Button size="sm" disabled={busy||!a.has_secret||a.status==='disabled'} onClick={()=>void act(async()=>{await centersApi.write(`accounts/${a.id}/verify`,{revision:a.revision});await reload();})}>Verifică</Button>}{a.status!=='disabled'&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void act(async()=>{await centersApi.write(`accounts/${a.id}/disable`,{revision:a.revision});await reload();})}>Dezactivează</Button>}</div></article>)}</div>{!data?.data.length&&!loading&&<p className="mt-4 text-sm text-slate-400">Nu există conturi configurate.</p>}</div>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>{edit?'Configurare cont':'Cont nou'}</DialogTitle><DialogDescription>Identitatea, brandul și metoda de acces rămân fixe după creare. Pentru o altă identitate, adaugă un cont separat.</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();void act(async()=>{await centersApi.write(`accounts${edit?`/${edit.id}`:''}`,{...form,...(edit?{revision:edit.revision}:{})},edit?'PATCH':'POST');setOpen(false);await reload();});}}>
 {(['brand','provider','auth_method'] as const).map(k=><label key={k} className="block text-sm">{k==='brand'?'Brand':k==='provider'?'Platformă':'Metodă de acces'}<select className={inputClass} value={form[k]} disabled={!!edit} onChange={e=>field(k,e.target.value)}>{(k==='brand'?['avyron','cutiutamagica']:k==='provider'?['instagram','facebook','cloudflare','github','google','tiktok','other']:['api_token','oauth_token','password','passkey','device']).map(v=><option key={v}>{v}</option>)}</select></label>)}
 {(['label','login_url','external_id','api_version'] as const).map(k=><label key={k} className="block text-sm">{{label:'Denumire',login_url:'Pagina oficială de conectare (HTTPS)',external_id:'ID cont / pagină / business',api_version:'Versiune API Meta'}[k]}<input className={inputClass} required={k!=='external_id'} value={form[k]} disabled={!!edit&&k==='external_id'} onChange={e=>field(k,e.target.value)}/></label>)}<label className="block text-sm">Expirarea credentialului (opțional)<input type="date" className={inputClass} value={form.expires_at?new Date(form.expires_at).toISOString().slice(0,10):''} onChange={e=>setForm(f=>({...f,expires_at:e.target.value?Date.parse(e.target.value):null}))}/></label><p className="text-xs text-muted-foreground">Instagram: cont profesional conectat la o pagină Facebook și token cu permisiunile Meta necesare. Cloudflare: Account ID și token D1 Read. Passkey și accesul pe dispozitiv se folosesc prin pagina oficială.</p><Button disabled={busy}>Salvează</Button></form></DialogContent></Dialog>
 <Dialog open={!!secretAccount} onOpenChange={o=>{if(!o){setSecretAccount(null);setSecret('');setRevealed('');}}}><DialogContent><DialogHeader><DialogTitle>Seif · {secretAccount?.label}</DialogTitle><DialogDescription>Introdu credentialul aici. Nu îl include în descrieri, capturi sau comentarii.</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();void act(async()=>{await centersApi.write(`accounts/${secretAccount!.id}/secret`,{secret,revision:secretAccount!.revision},'PUT');setSecret('');setSecretAccount(null);await reload();});}}><label className="block text-sm">Parolă / token nou<input type="password" autoComplete="new-password" required className={inputClass} value={secret} onChange={e=>setSecret(e.target.value)}/></label><Button disabled={busy}>Salvează criptat</Button></form>{secretAccount?.auth_method==='password'&&secretAccount.has_secret&&<div className="space-y-3 border-t pt-3"><label className="block text-sm">Motiv acces<input className={inputClass} minLength={8} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button variant="outline" disabled={busy||reason.trim().length<8} onClick={()=>void act(async()=>{const result=await centersApi.write<{secret:string}>(`accounts/${secretAccount.id}/reveal`,{reason});setRevealed(result.secret);})}>Afișează 30 secunde</Button>{revealed&&<p className="break-all rounded bg-muted p-3 font-mono" aria-live="polite">{revealed}</p>}</div>}</DialogContent></Dialog>
 <DevicePanel accounts={data?.data||[]}/></div>;
}
function DevicePanel({accounts}:{accounts:Account[]}){
 const {data,error,reload}=useCenterData<{data:Device[]}>('devices'),{busy,act}=useCenterAction();const [device,setDevice]=useState<{id:string;token:string}|null>(null),[tasks,setTasks]=useState<Task[]>([]),[label,setLabel]=useState(''),[target,setTarget]=useState(''),[account,setAccount]=useState(''),[action,setAction]=useState('login'),[instructions,setInstructions]=useState(''),[evidence,setEvidence]=useState(''),[deviceError,setDeviceError]=useState('');
 // In-memory token intentionally disappears on logout/unmount/reload.
 useEffect(()=>{if(!device)return;let alive=true;const beat=async()=>{if(document.hidden)return;try{const r=await cfAuth.request<{data:Task[]}>(`/api/centers/devices/${device.id}/heartbeat`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID(),'X-Device-Token':device.token},body:'{}'});if(alive){setTasks(r.data);setDeviceError('');}}catch{if(alive)setDeviceError('Sesiunea dispozitivului a expirat sau accesul a fost revocat.');}};void beat();const timer=setInterval(()=>void beat(),30000);document.addEventListener('visibilitychange',beat);return()=>{alive=false;clearInterval(timer);document.removeEventListener('visibilitychange',beat);};},[device]);
 return <details className={panelClass}><summary className="cursor-pointer font-semibold">iMac / telefon · sesiuni asistate</summary><p className="my-3 text-sm text-slate-400">Deschide acest centru pe dispozitivul dorit și activează sesiunea. Primești sarcini timp de 8 ore, cât pagina este deschisă. Acțiunile în celelalte aplicații sunt executate și confirmate de admin; această sesiune nu controlează automat ecranul.</p><Notice error={error||deviceError} loading={false}/><div className="flex flex-wrap gap-2"><input aria-label="Denumire dispozitiv" placeholder="iMac birou / iPhone" className={`${inputClass} sm:max-w-xs`} value={label} onChange={e=>setLabel(e.target.value)}/><Button disabled={busy||!label.trim()||!!device} onClick={()=>void act(async()=>{const d=await centersApi.write<{id:string;token:string}>('devices',{label});setDevice(d);await reload();})}>Conectează acest dispozitiv</Button></div><div className="my-4 space-y-2">{data?.data.map(d=><div key={d.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-white/10 p-3"><span className="text-sm">{d.label} · {d.status==='active'&&d.expires_at>Date.now()?(d.last_seen_at>Date.now()-90000?'online recent':'inactiv'):'revocat / expirat'}</span>{d.status==='active'&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void act(async()=>{await centersApi.write(`devices/${d.id}/revoke`);if(device?.id===d.id){setDevice(null);setTasks([]);}await reload();})}>Revocă</Button>}</div>)}</div>
 <form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void act(async()=>{await centersApi.write(`devices/${target}/tasks`,{account_id:account,action,instructions});setInstructions('');});}}><select required aria-label="Dispozitiv destinație" className={inputClass} value={target} onChange={e=>setTarget(e.target.value)}><option value="">Dispozitiv destinație</option>{data?.data.filter(d=>d.status==='active'&&d.expires_at>Date.now()).map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select><select required aria-label="Cont sarcină" className={inputClass} value={account} onChange={e=>setAccount(e.target.value)}><option value="">Cont</option>{accounts.filter(a=>a.status!=='disabled').map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select><select aria-label="Tip sarcină" className={inputClass} value={action} onChange={e=>setAction(e.target.value)}><option value="login">Conectare</option><option value="publish">Publicare asistată</option><option value="review_unfollow">Revizuire unfollow</option></select><input required minLength={5} aria-label="Instrucțiuni sarcină" className={inputClass} placeholder="Instrucțiuni, fără parole" value={instructions} onChange={e=>setInstructions(e.target.value)}/><Button disabled={busy}>Trimite sarcina · expiră în 15 min</Button></form>
 {tasks.map(t=><article className="mt-4 rounded-xl border border-violet-400/30 p-4" key={t.id}><h3>{t.label} · {t.action}</h3><p className="my-2 whitespace-pre-wrap text-sm">{t.instructions}</p><a className="text-violet-300 underline" href={t.login_url} target="_blank" rel="noopener noreferrer">Deschide platforma</a><input aria-label="Dovadă finalizare" className={`${inputClass} my-2`} placeholder="Rezultat / URL postare / motiv eșec" value={evidence} onChange={e=>setEvidence(e.target.value)}/>{['completed','failed'].map(status=><Button key={status} className="mr-2" disabled={busy||evidence.trim().length<5} onClick={()=>void act(async()=>{await cfAuth.request(`/api/centers/devices/${device!.id}/tasks/${t.id}`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID(),'X-Device-Token':device!.token},body:JSON.stringify({status,evidence})});setTasks(list=>list.filter(item=>item.id!==t.id));setEvidence('');})}>{status==='completed'?'Confirm executarea':'Raportează eșec'}</Button>)}</article>)}
 </details>;
}
