import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {centersApi} from '@/lib/centersApi';
import {cfAuth} from '@/lib/cfAuth';
import {Notice,RegistryPanel} from './CenterPanels';
import {inputClass,panelClass,useCenterAction,useCenterData} from './centerHooks';
type Settings={enabled:number;account_id:string|null;interval_hours:number;retention_days:number;keep_count:number;max_bytes:number;include_files:number;include_media:number;next_run_at:number|null;revision:number};
type Run={id:string;status:string;protected:number;bytes:number;objects_count:number;error_code:string|null;created_at:number;completed_at:number|null;verified_at:number|null;restore_evidence:string|null};
export default function BackupsPanel({canWrite}:{canWrite:boolean}){
 const {data,error,loading,reload}=useCenterData<{settings:Settings;runs:Run[];accounts:{id:string;label:string;status:string}[]}>('backups'),{busy,act}=useCenterAction();const [settings,setSettings]=useState<Settings|null>(null),[manual,setManual]=useState(false),[baseline,setBaseline]=useState(false),[ack,setAck]=useState(false),[recovery,setRecovery]=useState<Run|null>(null),[evidence,setEvidence]=useState('');
 useEffect(()=>{if(data&&!settings)setSettings({...data.settings});},[data,settings]);
 useEffect(()=>{if(!data?.runs.some(r=>['queued','running'].includes(r.status)))return;const timer=setInterval(()=>void reload(),30000);return()=>clearInterval(timer);},[data,reload]);
 const download=async(run:Run,kind:'sql'|'manifest')=>{const response=await cfAuth.requestResponse(`/api/centers/backups/${run.id}/download/${kind}`);const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`avyron-${run.id}-${kind==='sql'?'data.sql':'manifest.json'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <div className="space-y-4"><Notice error={error} loading={loading}/><section className={panelClass}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Backup & recuperare</h2><p className="mt-1 text-sm text-slate-400">D1 + fișiere R2 + credentiale criptate · stocare privată Cloudflare</p></div>{canWrite&&<Button disabled={busy||data?.runs.some(r=>['queued','running','deleting'].includes(r.status))} onClick={()=>{setManual(true);setBaseline(false);setAck(false);}}>Creează backup</Button>}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-white/5 p-3"><p className="text-xs text-slate-400">Copii complete</p><p className="mt-1 text-xl">{data?.runs.filter(r=>r.status==='complete').length||0}</p></div><div className="rounded-xl bg-white/5 p-3"><p className="text-xs text-slate-400">Copii de bază protejate</p><p className="mt-1 text-xl">{data?.runs.filter(r=>r.protected).length||0}</p></div><div className="rounded-xl bg-white/5 p-3"><p className="text-xs text-slate-400">Următoarea execuție</p><p className="mt-1 text-sm">{data?.settings.enabled&&data.settings.next_run_at?new Date(data.settings.next_run_at).toLocaleString('ro-RO'):'Programarea este oprită'}</p></div></div></section>
 {canWrite&&settings&&<details className={panelClass}><summary className="cursor-pointer font-semibold">Configurare: frecvență, retenție și spațiu</summary><form className="mt-4 grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void act(async()=>{await centersApi.write('backups/settings',{enabled:!!settings.enabled,account_id:settings.account_id,interval_hours:settings.interval_hours,retention_days:settings.retention_days,keep_count:settings.keep_count,max_bytes:settings.max_bytes,include_files:!!settings.include_files,include_media:!!settings.include_media,revision:settings.revision},'PUT');setSettings(null);await reload();});}}><label className="text-sm sm:col-span-2">Cont Cloudflare verificat<select required className={inputClass} value={settings.account_id||''} onChange={e=>setSettings(s=>s&&({...s,account_id:e.target.value||null}))}><option value="">Selectează din Conturi & dispozitive</option>{data?.accounts.map(a=><option key={a.id} value={a.id} disabled={a.status!=='verified'}>{a.label} · {a.status}</option>)}</select></label><label className="text-sm">Frecvență<select className={inputClass} value={settings.interval_hours} onChange={e=>setSettings(s=>s&&({...s,interval_hours:Number(e.target.value)}))}>{[[6,'La 6 ore'],[12,'La 12 ore'],[24,'Zilnic'],[168,'Săptămânal']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label className="text-sm">Retenție (zile)<input required type="number" min="7" max="365" className={inputClass} value={settings.retention_days} onChange={e=>setSettings(s=>s&&({...s,retention_days:Number(e.target.value)}))}/></label><label className="text-sm">Păstrează minimum ultimele copii complete<input required type="number" min="2" max="100" className={inputClass} value={settings.keep_count} onChange={e=>setSettings(s=>s&&({...s,keep_count:Number(e.target.value)}))}/></label><label className="text-sm">Limită totală backup (MiB)<input required type="number" min="10" max="102400" className={inputClass} value={settings.max_bytes/1048576} onChange={e=>setSettings(s=>s&&({...s,max_bytes:Number(e.target.value)*1048576}))}/></label>{(['include_files','include_media','enabled'] as const).map(k=><label key={k} className="flex gap-2 text-sm"><input type="checkbox" checked={!!settings[k]} onChange={e=>setSettings(s=>s&&({...s,[k]:Number(e.target.checked)}))}/>{{include_files:'Include fișierele private',include_media:'Include biblioteca media',enabled:'Activează programarea automată'}[k]}</label>)}<p className="text-xs text-slate-400 sm:col-span-2">Retenția elimină copii expirate după o execuție completă, păstrând minimul ales și toate copiile de bază. Fișierele identice sunt deduplicate. Limita oprește copiile noi dacă spațiul nu ajunge. Exportul D1 poate întrerupe temporar accesul la bază; alege frecvența potrivită.</p><Button disabled={busy}>Salvează configurarea</Button></form></details>}
 <section className={panelClass}><div className="flex items-center justify-between gap-2"><h2 className="font-semibold">Istoric execuții</h2><Button variant="outline" size="sm" onClick={()=>void reload()}>Actualizează</Button></div><div className="mt-3 space-y-3">{data?.runs.map(r=><article key={r.id} className="rounded-xl border border-white/10 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-medium">{new Date(r.created_at).toLocaleString('ro-RO')}</h3><span className="text-xs text-violet-300">{r.status}{r.protected?' · BAZĂ PROTEJATĂ':''}</span></div><p className="my-2 text-xs text-slate-400">{(r.bytes/1048576).toFixed(1)} MiB logici · {r.objects_count} fișiere{r.verified_at?` · inventar verificat ${new Date(r.verified_at).toLocaleDateString('ro-RO')}`:''}</p>{r.error_code&&<p className="mb-2 text-sm text-amber-300">Execuție nereușită. Verifică tokenul, spațiul disponibil și jurnalul Workflow în Cloudflare.</p>}{canWrite&&r.status==='complete'&&<div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={()=>void act(async()=>{await centersApi.write(`backups/${r.id}/verify`);await reload();})}>Verifică inventarul</Button><Button size="sm" onClick={()=>{setRecovery(r);setEvidence(r.restore_evidence||'');}}>Recuperare controlată</Button></div>}</article>)}{!loading&&!data?.runs.length&&<p className="text-sm text-slate-400">Nicio copie executată. Configurează contul și pornește primul backup.</p>}</div></section>
 <details className={panelClass}><summary className="cursor-pointer font-semibold">Acoperire și limite</summary><p className="mt-3 text-sm text-slate-400">Manifestul conține schema, inventarul fișierelor și instrucțiunile de restaurare. Baza D1 și fișierele sunt copiate la momente apropiate, fără o tranzacție comună. Cheile secrete ale Workerului, starea Durable Objects, DNS-ul și codul GitHub necesită proceduri separate. Copiile din același cont Cloudflare nu acoperă pierderea întregului cont. Verificarea inventarului nu echivalează cu un test de restaurare.</p></details><details className={panelClass}><summary className="cursor-pointer">Dovezi și evidențe manuale existente</summary><div className="mt-4"><RegistryPanel kind="backup" canWrite={canWrite}/></div></details>
 <Dialog open={manual} onOpenChange={setManual}><DialogContent><DialogHeader><DialogTitle>Pornește copia de siguranță</DialogTitle><DialogDescription>Operația copiază datele în spațiul privat de backup. Nu modifică datele originale. Exportul D1 poate provoca o scurtă pauză de acces.</DialogDescription></DialogHeader><label className="flex gap-2 text-sm"><input type="checkbox" checked={baseline} onChange={e=>setBaseline(e.target.checked)}/>Aceasta este o copie de bază: păstrează permanent după finalizare.</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>Accept posibila pauză pe durata exportului.</label><Button disabled={busy||!ack} onClick={()=>void act(async()=>{await centersApi.write('backups',{baseline,acknowledge_export_pause:true});setManual(false);await reload();})}>Confirmă și pornește</Button></DialogContent></Dialog>
 <Dialog open={!!recovery} onOpenChange={o=>{if(!o)setRecovery(null);}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>Recuperare controlată</DialogTitle><DialogDescription>Descarcă copia și manifestul. Restaurarea se face mai întâi într-un mediu izolat; nu există suprascriere directă a producției din acest buton.</DialogDescription></DialogHeader><ol className="list-decimal space-y-2 pl-5 text-sm"><li>Verifică inventarul și păstrează o copie a stării curente.</li><li>Creează resurse D1/R2 izolate. Aplică schema din manifest, importă datele, apoi indexurile și triggerele.</li><li>Reface indexurile FTS și restaurează fișierele la cheile originale. Credentialele necesită cheia de criptare originală, păstrată separat.</li><li>Verifică autentificarea, permisiunile și documentele înainte de schimbarea bindingurilor.</li></ol><div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>void act(()=>download(recovery!,'sql'))}>Descarcă datele SQL</Button><Button variant="outline" disabled={busy} onClick={()=>void act(()=>download(recovery!,'manifest'))}>Descarcă manifestul</Button></div><label className="text-sm">Dovada testului în mediu izolat<textarea className={inputClass} minLength={20} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Mediu, data testului, verificări și rezultat"/></label><Button disabled={busy||evidence.trim().length<20} onClick={()=>void act(async()=>{await centersApi.write(`backups/${recovery!.id}/restore-evidence`,{evidence});setRecovery(null);await reload();})}>Înregistrează dovada</Button></DialogContent></Dialog>
 </div>;
}
