import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { centersApi } from '@/lib/centersApi';
import { osApi } from '@/lib/osApi';
import { workspaceApi, type WorkItem } from '@/lib/workspaceApi';
import { useCenterData, useCenterAction, inputClass, panelClass } from './centerHooks';
import { centerFields, fieldLabels, stateLabels } from './centerForms';
export function Notice({error,loading}:{error:string;loading:boolean}){return <>{loading&&<p role="status" className="text-sm text-slate-400">Se încarcă…</p>}{error&&<p role="alert" className="text-sm text-rose-300">{error}</p>}</>;}
const date=(v:unknown)=>typeof v==='number'?new Date(v).toLocaleString('ro-RO'):'—';
const localDate=(v:unknown)=>typeof v==='number'?new Date(v-new Date(v).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
type Row={id:string;kind:string;title:string;description:string;status:string;client_id:string|null;project_id:string|null;assignee_id:string|null;due_at:number|null;revision:number;has_secret:number;data:Record<string,unknown>};
type Config={staff?:{id:string;name:string}[];clients:{id:string;name:string}[];projects:{id:string;name:string;client_id:string}[]};
export function RegistryPanel({kind,canWrite}:{kind:string;canWrite:boolean}){
 const [search,setSearch]=useState(''),[offset,setOffset]=useState(0),[editing,setEditing]=useState<Row|null>(null),[opened,setOpened]=useState(false);
 const {data,error,loading,reload}=useCenterData<{data:Row[];total:number}>(`records/${kind}?${new URLSearchParams({search,offset:String(offset)})}`),config=useCenterData<Config>('config'),{busy,act}=useCenterAction();
 const fields=centerFields[kind];const defaults=()=>Object.fromEntries(fields.map(f=>[f.key,f.type==='select'?f.options![0]:f.key==='warning_hours'?'48':f.key==='minutes'?'0':'']));
 const blank=()=>({title:'',description:'',status:kind==='newsletter'?'pending':'draft',client_id:'',project_id:'',assignee_id:'',due_at:'',values:defaults()});
 const [form,setForm]=useState(blank),[secret,setSecret]=useState(''),[secretRow,setSecretRow]=useState<Row|null>(null),[revealed,setRevealed]=useState(''),[reason,setReason]=useState('');
 useEffect(()=>{if(!revealed)return;const timer=setTimeout(()=>setRevealed(''),30000);return()=>clearTimeout(timer);},[revealed]);
 const edit=(row:Row|null)=>{setEditing(row);setForm(row?{title:row.title,description:row.description,status:row.status,client_id:row.client_id||'',project_id:row.project_id||'',assignee_id:row.assignee_id||'',due_at:localDate(row.due_at),values:Object.fromEntries(fields.map(f=>[f.key,f.type==='datetime-local'?localDate(row.data[f.key]):f.money&&typeof row.data[f.key]==='number'?String(Number(row.data[f.key])/100):String(row.data[f.key]??'')]))}:blank());setOpened(true);};
 const set=(key:keyof ReturnType<typeof blank>,value:string)=>setForm(old=>({...old,[key]:value}));
 const statuses=kind==='newsletter'?['pending','subscribed','unsubscribed']:['draft','active','warning','resolved','archived',...(kind==='backup'?['recovery_requested']:[])];
 return <div className="space-y-4">
 {kind==='newsletter'&&<p className="text-sm text-slate-400">Abonații rămân în așteptare fără dovada consimțământului. Campaniile se vor activa după configurarea furnizorului email.</p>}
 {kind==='backup'&&<p className="text-sm text-slate-400">Dovezile se adaugă după verificare. Cererea de recuperare inițiază revizuirea planului; restaurarea se execută separat, controlat.</p>}
 <div className="flex flex-wrap gap-2"><input aria-label="Caută în centru" placeholder="Caută…" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}} className={`${inputClass} flex-1`}/>{canWrite&&<Button onClick={()=>edit(null)}>Adaugă</Button>}<Button variant="outline" onClick={()=>void reload()}>Actualizează</Button></div>
 <Notice error={error} loading={loading}/>
 {opened&&<form className={`${panelClass} grid gap-3 sm:grid-cols-2`} onSubmit={e=>{e.preventDefault();void act(async()=>{
  const payload=Object.fromEntries(fields.map(f=>[f.key,f.type==='datetime-local'?(form.values[f.key]?new Date(form.values[f.key]).getTime():null):f.type==='number'?(form.values[f.key]!==''?(f.money?Math.round(Number(form.values[f.key])*100):Number(form.values[f.key])):null):form.values[f.key]]));
  await centersApi.write(`records/${kind}${editing?`/${editing.id}`:''}`,{title:form.title,description:form.description,status:form.status,client_id:form.client_id||null,project_id:form.project_id||null,assignee_id:form.assignee_id||null,due_at:form.due_at?new Date(form.due_at).getTime():null,data:payload,...(editing?{revision:editing.revision}:{})},editing?'PATCH':'POST');setOpened(false);await reload();toast.success('Înregistrare salvată.');
 });}}><h3 className="font-semibold sm:col-span-2">{editing?'Editează':'Adaugă înregistrare'}</h3>
 <label className="grid gap-1 text-sm">Denumire<input required maxLength={200} value={form.title} onChange={e=>set('title',e.target.value)} className={inputClass}/></label>
 <label className="grid gap-1 text-sm">Stare<select value={form.status} onChange={e=>set('status',e.target.value)} className={inputClass}>{statuses.map(s=><option key={s} value={s}>{stateLabels[s]}</option>)}</select></label>
 <label className="grid gap-1 text-sm">Client<select value={form.client_id} onChange={e=>{set('client_id',e.target.value);set('project_id','');}} className={inputClass}><option value="">Fără asociere</option>{config.data?.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
 <label className="grid gap-1 text-sm">Proiect<select value={form.project_id} onChange={e=>set('project_id',e.target.value)} className={inputClass}><option value="">Fără asociere</option>{config.data?.projects.filter(p=>!form.client_id||p.client_id===form.client_id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 <label className="grid gap-1 text-sm">Responsabil<select value={form.assignee_id} onChange={e=>set('assignee_id',e.target.value)} className={inputClass}><option value="">Neasignat</option>{config.data?.staff?.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>
 <label className="grid gap-1 text-sm">Termen / expirare<input type="datetime-local" value={form.due_at} onChange={e=>set('due_at',e.target.value)} className={inputClass}/></label>
 {fields.map(f=><label key={f.key} className="grid gap-1 text-sm">{f.label}{f.type==='select'?<select value={form.values[f.key]} onChange={e=>setForm(o=>({...o,values:{...o.values,[f.key]:e.target.value}}))} className={inputClass}>{f.options!.map(v=><option key={v}>{v}</option>)}</select>:<input type={f.type||'text'} step={f.money?'0.01':undefined} min={f.type==='number'?0:undefined} required={f.required} maxLength={1000} value={form.values[f.key]} onChange={e=>setForm(o=>({...o,values:{...o.values,[f.key]:e.target.value}}))} className={inputClass}/>}</label>)}
 <label className="grid gap-1 text-sm sm:col-span-2">Detalii<textarea maxLength={4000} value={form.description} onChange={e=>set('description',e.target.value)} className={inputClass}/></label>
 <div className="flex gap-2"><Button disabled={busy}>Salvează</Button><Button type="button" variant="ghost" onClick={()=>setOpened(false)}>Anulează</Button></div></form>}
 {data?.data.map(row=><article key={row.id} className={panelClass}><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words font-semibold">{row.title}</h3><p className="mt-1 text-xs text-slate-400">{stateLabels[row.status]} · termen {date(row.due_at)} · v{row.revision}</p></div>{canWrite&&<Button variant="outline" onClick={()=>edit(row)}>Editează</Button>}</div><p className="mt-3 whitespace-pre-wrap break-words text-sm text-slate-300">{row.description}</p><details className="mt-3 text-sm"><summary className="cursor-pointer text-violet-300">Detalii</summary><dl className="mt-3 grid gap-2 sm:grid-cols-2">{fields.map(f=><div key={f.key} className="min-w-0"><dt className="text-xs text-slate-500">{f.label}</dt><dd className="break-words">{f.type==='datetime-local'?date(row.data[f.key]):f.money&&typeof row.data[f.key]==='number'?`${(Number(row.data[f.key])/100).toLocaleString('ro-RO')} RON`:String(row.data[f.key]??'—')}</dd></div>)}</dl></details>{kind==='vault'&&canWrite&&<Button className="mt-3" variant="outline" onClick={()=>{setSecretRow(row);setSecret('');setRevealed('');setReason('');}}>Seif securizat {row.has_secret?'· secret salvat':''}</Button>}</article>)}
 {!loading&&data?.data.length===0&&<p className="rounded-xl border border-dashed border-white/10 p-6 text-sm text-slate-400">Nicio înregistrare. Datele adăugate vor apărea aici.</p>}
 {secretRow&&<section className={panelClass}><h3 className="font-semibold">Secret: {secretRow.title}</h3><label className="my-3 grid gap-1 text-sm">Secret nou (criptat la salvare)<input type="password" autoComplete="new-password" value={secret} onChange={e=>setSecret(e.target.value)} className={inputClass}/></label><Button disabled={busy||!secret} onClick={()=>void act(async()=>{await centersApi.write(`vault/${secretRow.id}/secret`,{secret,revision:secretRow.revision});setSecret('');setSecretRow(null);await reload();})}>Salvează / rotește</Button>{Boolean(secretRow.has_secret)&&<><label className="my-3 grid gap-1 text-sm">Motivul accesului<input value={reason} onChange={e=>setReason(e.target.value)} className={inputClass}/></label><Button disabled={busy||reason.trim().length<5} variant="outline" onClick={()=>void act(async()=>{const r=await centersApi.write<{secret:string}>(`vault/${secretRow.id}/reveal`,{reason});setRevealed(r.secret);})}>Dezvăluie 30 secunde</Button>{revealed&&<pre className="mt-3 whitespace-pre-wrap break-all rounded-lg bg-black/30 p-3">{revealed}</pre>}</>}<Button variant="ghost" onClick={()=>{setSecretRow(null);setSecret('');setRevealed('');}}>Închide</Button></section>}
 <div className="flex flex-wrap items-center gap-3 text-sm"><Button variant="outline" disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-40))}>Înapoi</Button>{data?.total||0} înregistrări<Button variant="outline" disabled={offset+40>=(data?.total||0)} onClick={()=>setOffset(v=>v+40)}>Următoarele</Button></div>
 </div>;
}
function Value({name,value,currency}:{name:string;value:unknown;currency?:unknown}){if(typeof value==='number'&&['revenue','cost','margin','contract_value','estimated_labor_ron_minor'].includes(name)){const unit=name==='estimated_labor_ron_minor'?'RON':String(currency||'');try{return <>{new Intl.NumberFormat('ro-RO',{style:'currency',currency:unit}).format(value/100)}</>;}catch{return <>{(value/100).toLocaleString('ro-RO')} {unit||'(monedă necunoscută)'}</>;}}if(value===null||value===undefined)return <>—</>;if(/(_at|review_after)$/.test(name)&&typeof value==='number')return <>{date(value)}</>;return <>{stateLabels[String(value)]||String(value)}</>;}
export function DataCards({rows}:{rows:Record<string,unknown>[]}){return <div className="space-y-2">{rows.map((row,i)=><details className={panelClass} key={String(row.id||i)}><summary className="cursor-pointer break-words text-sm font-medium">{String(row.title||row.client||row.name||row.agent_slug||row.page||row.action||row.source||row.client_id||'Înregistrare')} {row.status?`· ${stateLabels[String(row.status)]||row.status}`:''}{row.day?` · ${row.day}`:''}</summary><dl className="mt-3 grid gap-3 sm:grid-cols-2">{Object.entries(row).filter(([k])=>k!=='id').map(([name,value])=><div key={name} className="min-w-0"><dt className="text-xs text-slate-500">{fieldLabels[name]||name}</dt><dd className="whitespace-pre-wrap break-words text-sm text-slate-200"><Value name={name} value={value} currency={row.currency}/></dd></div>)}</dl></details>)}{rows.length===0&&<p className="rounded-xl border border-dashed border-white/10 p-6 text-sm text-slate-400">Nicio înregistrare disponibilă.</p>}</div>;}
export function ReportPanel({center,canWrite}:{center:string;canWrite:boolean}){
 const [search,setSearch]=useState(''),[days,setDays]=useState('30');
 const {data,error,loading,reload}=useCenterData<{data:Record<string,unknown>[];steps?:Record<string,unknown>[];contracts?:Record<string,unknown>[];effort?:Record<string,unknown>[];totals?:Record<string,number>;note?:string}>(`report/${center}?${new URLSearchParams({search,days})}`),{busy,act}=useCenterAction();
 return <div className="space-y-4"><div className="flex flex-wrap gap-2">{['documents','plugins'].includes(center)&&<input aria-label="Caută documente sau pluginuri" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Caută în sursele existente…" className={`${inputClass} flex-1`}/>} {center==='visits'&&<select aria-label="Perioadă analytics" value={days} onChange={e=>setDays(e.target.value)} className={inputClass}>{[7,30,90].map(n=><option key={n} value={n}>Ultimele {n} zile</option>)}</select>}<Button variant="outline" onClick={()=>void reload()}>Actualizează</Button>{center==='infrastructure'&&canWrite&&<Button disabled={busy} onClick={()=>void act(async()=>{await centersApi.write('infrastructure/probe');await reload();})}>Verifică acum</Button>}{['plugins','documents'].includes(center)&&<Button asChild variant="outline"><Link to="/intern/avy-engine">Gestionează în AVY Engine</Link></Button>}</div><Notice error={error} loading={loading}/>{data?.note&&<p className="text-sm text-slate-400">{data.note}</p>}{data?.totals&&<div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{Object.entries(data.totals).map(([k,v])=><div className={panelClass} key={k}><p className="text-xs text-slate-400">{fieldLabels[k]||k}</p><strong className="mt-2 block text-xl">{v}</strong></div>)}</div>}
 {center==='infrastructure'?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data?.data.map(row=><details key={String(row.service)} className={panelClass}><summary className="flex cursor-pointer items-center gap-2 text-sm"><span className={`size-2.5 shrink-0 rounded-full ${row.status==='ok'?'bg-emerald-400':row.status==='error'?'bg-rose-400':row.status==='warning'?'bg-amber-300':'bg-slate-500'}`}/>{String(row.service)} · {stateLabels[String(row.status)]}</summary><p className="mt-3 text-xs text-slate-400">{String(row.detail)}<br/>{date(row.checked_at)} · {String(row.source)}</p></details>)}</div>:data&&<DataCards rows={data.data}/>}
 {data?.contracts&&<section><h3 className="mb-3 font-semibold">Contracte aprobate pe client și monedă</h3><DataCards rows={data.contracts}/></section>}{data?.effort&&<section><h3 className="mb-3 font-semibold">Resurse înregistrate</h3><DataCards rows={data.effort}/></section>}{data?.steps&&<details><summary className="cursor-pointer">Pași și rezultate ale agenților</summary><DataCards rows={data.steps}/></details>}
 </div>;
}
export function ApprovalsPanel(){
 const {data,error,loading,reload}=useCenterData<{data:{id:string;revision:number;summary:string;request_json:string;agent_slug:string;action_class:string;expires_at:number}[]}>('report/approvals'),{busy,act}=useCenterAction();
 const [editing,setEditing]=useState<string|null>(null),[summary,setSummary]=useState(''),[payload,setPayload]=useState('');
 return <div className="space-y-4"><Notice error={error} loading={loading}/><p className="text-sm text-slate-400">Revizuiește intenția completă. Aprobarea autorizează versiunea afișată; executarea externă depinde de conectorul activ și politica agentului.</p>{data?.data.map(row=><article key={row.id} className={panelClass}><p className="text-xs text-violet-300">{row.agent_slug} · {row.action_class} · v{row.revision} · expiră {date(row.expires_at)}</p><h3 className="my-3 font-semibold">{row.summary}</h3><details><summary className="cursor-pointer text-sm">Vezi intenția</summary><pre className="mt-2 whitespace-pre-wrap break-all text-xs">{JSON.stringify(JSON.parse(row.request_json),null,2)}</pre></details>{editing===row.id?<form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();void act(async()=>{await centersApi.write(`approvals/${row.id}`,{summary,request:JSON.parse(payload),revision:row.revision},'PATCH');setEditing(null);await reload();});}}><label className="grid gap-1 text-sm">Rezumat<textarea value={summary} onChange={e=>setSummary(e.target.value)} className={inputClass}/></label><label className="grid gap-1 text-sm">Intenție structurată (JSON)<textarea rows={8} value={payload} onChange={e=>setPayload(e.target.value)} className={inputClass}/></label><Button disabled={busy}>Salvează pentru o nouă revizuire</Button><Button type="button" variant="ghost" onClick={()=>setEditing(null)}>Anulează</Button></form>:<div className="mt-4 flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>void act(async()=>{await osApi.decideApproval(row.id,'approved',row.revision);await reload();})}>Aprobă</Button><Button disabled={busy} variant="outline" onClick={()=>{setEditing(row.id);setSummary(row.summary);setPayload(JSON.stringify(JSON.parse(row.request_json),null,2));}}>Editează</Button><Button disabled={busy} variant="destructive" onClick={()=>void act(async()=>{await osApi.decideApproval(row.id,'rejected',row.revision);await reload();})}>Respinge</Button></div>}</article>)}{data?.data.length===0&&<p className="text-sm text-slate-400">Nicio aprobare în așteptare.</p>}</div>;
}
export function CommentsPanel({canWrite}:{canWrite:boolean}){
 const [status,setStatus]=useState('pending'),{data,error,loading,reload}=useCenterData<{data:{id:string;path:string;content:string;author:string;revision:number;created_at:number}[]}>(`comments?status=${status}`),{busy,act}=useCenterAction();
 return <div className="space-y-4"><select aria-label="Stare comentarii" value={status} onChange={e=>setStatus(e.target.value)} className={inputClass}>{['pending','approved','rejected','spam'].map(s=><option key={s} value={s}>{stateLabels[s]}</option>)}</select><Notice error={error} loading={loading}/>{data?.data.map(r=><article className={panelClass} key={r.id}><p className="text-xs text-slate-400">{r.author} · {r.path} · {date(r.created_at)}</p><p className="my-3 whitespace-pre-wrap break-words">{r.content}</p>{canWrite&&<div className="flex flex-wrap gap-2">{['approved','rejected','spam','pending'].filter(s=>s!==status).map(s=><Button key={s} disabled={busy} variant="outline" onClick={()=>void act(async()=>{await centersApi.write(`comments/${r.id}`,{status:s,revision:r.revision},'PATCH');await reload();})}>{stateLabels[s]}</Button>)}</div>}</article>)}{data?.data.length===0&&<p className="text-sm text-slate-400">Niciun comentariu în această stare.</p>}</div>;
}
export function BriefingPanel(){
 const {data,error,loading}=useCenterData<{enabled:number;lookahead_days:number;include_finance:number}>('briefing'),{busy,act}=useCenterAction();
 const [enabled,setEnabled]=useState(true),[days,setDays]=useState(7),[finance,setFinance]=useState(true);
 useEffect(()=>{if(data){setEnabled(Boolean(data.enabled));setDays(data.lookahead_days);setFinance(Boolean(data.include_finance));}},[data]);
 return <form className={`${panelClass} space-y-4`} onSubmit={e=>{e.preventDefault();void act(async()=>{await centersApi.write('briefing',{enabled,lookahead_days:days,include_finance:finance},'PUT');toast.success('Preferințe salvate.');});}}><Notice error={error} loading={loading}/><p className="text-sm text-slate-400">Sinteza se generează din datele autorizate la deschiderea dashboardului. Notificările programate se configurează separat în Automation Center.</p><label className="flex gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Afișează AVY Briefing</label><label className="grid gap-1 text-sm">Fereastra de avertizare (zile)<input type="number" min={1} max={30} value={days} onChange={e=>setDays(Number(e.target.value))} className={inputClass}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={finance} onChange={e=>setFinance(e.target.checked)}/>Include financiarul când rolul permite</label><Button disabled={busy||loading}>Salvează preferințele</Button></form>;
}
export function WorkPanel({center,canWrite}:{center:string;canWrite:boolean}){
 const {data,error,loading,reload}=useCenterData<{data:(WorkItem&{project:string})[]}>(`report/${center}`),config=useCenterData<Config>('config'),{busy,act}=useCenterAction();
 const [project,setProject]=useState(''),[title,setTitle]=useState(''),[due,setDue]=useState('');
 const kind=center==='deliverables'?'deliverable':center;
 const create=async(title:string)=>workspaceApi.write(`work-items/${project}`,{kind,title,description:null,due_at:due?new Date(due).getTime():null,status:'open'});
 return <div className="space-y-4"><Notice error={error} loading={loading}/>{canWrite&&<form className={`${panelClass} grid gap-3 sm:grid-cols-2`} onSubmit={e=>{e.preventDefault();void act(async()=>{await create(title);setTitle('');await reload();});}}><label className="grid gap-1 text-sm">Proiect<select required value={project} onChange={e=>setProject(e.target.value)} className={inputClass}><option value="">Selectează proiectul</option>{config.data?.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="grid gap-1 text-sm">Termen<input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)} className={inputClass}/></label><label className="grid gap-1 text-sm">Element<input required value={title} onChange={e=>setTitle(e.target.value)} className={inputClass}/></label><div className="flex flex-wrap items-end gap-2"><Button disabled={busy||!project}>Adaugă element</Button>{center!=='deliverables'&&<Button type="button" variant="outline" disabled={busy||!project} onClick={()=>void act(async()=>{await centersApi.write('checklists',{project_id:project,kind,due_at:due?new Date(due).getTime():null});await reload();})}>Aplică checklist standard</Button>}</div></form>}{data?.data.map(row=><article key={row.id} className={panelClass}><p className="text-xs text-violet-300">{row.project} · {date(row.due_at)}</p><h3 className="my-2 font-semibold">{row.title}</h3><p className="text-sm text-slate-400">{row.description}</p>{canWrite?<select aria-label={`Stare ${row.title}`} value={row.status} disabled={busy} className={`${inputClass} mt-3`} onChange={e=>void act(async()=>{await workspaceApi.write(`work-items/${row.project_id}/${row.id}`,{kind:row.kind,title:row.title,description:row.description,due_at:row.due_at,status:e.target.value,revision:row.revision},'PATCH');await reload();})}>{['open','in_progress','blocked','done','cancelled'].map(s=><option key={s}>{s}</option>)}</select>:<p className="text-sm">{row.status}</p>}</article>)}{data?.data.length===0&&<p className="text-sm text-slate-400">Niciun element în proiectele accesibile.</p>}</div>;
}
