export type Field={key:string;label:string;type?:'text'|'number'|'datetime-local'|'email'|'select';options?:string[];required?:boolean;money?:boolean};
export const centerFields:Record<string,Field[]>={
 domains:[{key:'domain',label:'Domeniu',required:true},{key:'dns',label:'DNS / nameservere'},{key:'ssl_expires_at',label:'Expirare SSL',type:'datetime-local'},{key:'redirect',label:'Redirect / subdomenii'},{key:'estimated_value_minor',label:'Valoare estimată (RON)',type:'number',money:true},{key:'opportunity',label:'Oportunitate / sursa Domain Trader'}],
 sla:[{key:'category',label:'Categorie',type:'select',options:['response','delivery','support','wcag','incident']},{key:'warning_hours',label:'Avertizează cu câte ore înainte',type:'number',required:true},{key:'evidence',label:'Dovadă / referință'}],
 vault:[{key:'asset_type',label:'Tip de activ',type:'select',options:['brand','document','credential','domain','other']},{key:'location',label:'Locație / ID document privat'},{key:'owner',label:'Proprietar'}],
 backup:[{key:'resource',label:'Resursă',required:true},{key:'evidence',label:'Dovadă backup / bookmark / run ID'},{key:'last_backup_at',label:'Ultimul backup verificat',type:'datetime-local'},{key:'last_restore_test_at',label:'Ultimul test de restaurare',type:'datetime-local'},{key:'recovery_note',label:'Motiv și plan de recuperare'}],
 security:[{key:'category',label:'Categorie',type:'select',options:['incident','key','ssl','auth','wcag']},{key:'evidence',label:'Dovadă / referință'}],
 profitability:[{key:'minutes',label:'Timp consumat (minute)',type:'number',required:true},{key:'hourly_cost_minor',label:'Cost orar estimat (RON)',type:'number',money:true},{key:'upsell',label:'Oportunitate upsell'},{key:'churn_risk',label:'Risc de plecare evaluat',type:'select',options:['unknown','low','medium','high']}],
 newsletter:[{key:'email',label:'Email abonat',type:'email',required:true},{key:'consent_evidence',label:'Dovada consimțământului'},{key:'policy_version',label:'Versiunea politicii'},{key:'source',label:'Sursa înscrierii',required:true}],
};
export const stateLabels:Record<string,string>={draft:'Ciornă',active:'Activ',warning:'Atenție',resolved:'Rezolvat',archived:'Arhivat',pending:'În așteptare',subscribed:'Abonat cu consimțământ',unsubscribed:'Dezabonat',recovery_requested:'Cerere de recuperare',approved:'Aprobat',rejected:'Respins',spam:'Spam',ok:'Funcțional',error:'Eroare',unknown:'Neverificat'};
export const fieldLabels:Record<string,string>={id:'ID',client:'Client',company_name:'Client',currency:'Monedă',revenue:'Venit facturat',cost:'Cheltuieli',margin:'Marjă documentată',incomplete_amounts:'Sume necunoscute',active_services:'Servicii active',contract_value:'Valoare contract',client_id:'ID client',minutes:'Minute',estimated_labor_ron_minor:'Cost muncă estimat (RON)',title:'Titlu',status:'Stare',summary:'Rezumat',agent_slug:'Agent',created_at:'Creat',completed_at:'Finalizat',input_tokens:'Tokenuri intrare',output_tokens:'Tokenuri ieșire',estimated_cost_micros:'Cost estimat (micro-unități)',error_code:'Cod eroare',source:'Sursă',message:'Mesaj',action:'Acțiune',outcome:'Rezultat',severity:'Severitate',target_id:'Țintă',day:'Zi UTC',page:'Pagină',views:'Vizualizări',visitors:'Sesiuni',leads:'Conversii lead',cta_clicks:'Clickuri CTA',name:'Denumire',category:'Categorie',implementation_status:'Stare implementare',risk_level:'Risc',requirements_json:'Cerințe / permisiuni',last_verified_at:'Ultima verificare',updated_at:'Actualizat',visibility:'Vizibilitate',excerpt:'Fragment',review_after:'Revizuire până la',file_name:'Fișier',evidence:'Dovadă',run_id:'Execuție',sequence:'Pas',kind:'Tip',output_json:'Rezultat înregistrat'};
