import { useState } from 'react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { cfAuth } from '@/lib/cfAuth';
import { centersApi } from '@/lib/centersApi';
import { Notice, ReportPanel } from './CenterPanels';
import { inputClass, panelClass, useCenterAction, useCenterData } from './centerHooks';
const categories:Record<string,string>={offer:'Oferte',contract:'Contracte',brief:'Briefuri',invoice:'Facturi',technical:'Documentație tehnică',client_file:'Fișiere client',report:'Rapoarte'};
type Doc={id:string;title:string;category:string;content_text:string;client_id:string|null;project_id:string|null;status:string;review_after:number|null;revision:number;file_name:string|null;updated_at:number};
type Source={id:string;title:string;revision:number};
type Citation={id:string;quote:string};
type Analysis={answer?:string;citations?:Citation[];findings?:{summary:string;citations:Citation[]}[];sources?:Source[];scope?:string;run_id?:string;error?:{message:string}};
const when=(n:number)=>new Date(n).toLocaleString('ro-RO');
const dateInput=(n:number|null)=>n?new Date(n-new Date(n).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
function AnalysisView({result}:{result:Analysis}){
 const citations=(list:Citation[])=>list.map((c,i)=><blockquote key={i} className="mt-2 border-l-2 border-violet-400/40 pl-3 text-sm text-slate-300"><p className="whitespace-pre-wrap break-words">„{c.quote}”</p><footer className="mt-1 text-xs text-violet-300">{result.sources?.find(s=>s.id===c.id)?.title||c.id} · v{result.sources?.find(s=>s.id===c.id)?.revision}</footer></blockquote>);
 return <div className="space-y-3">{result.error?<p role="alert" className="text-amber-300">{result.error.message}</p>:<>{result.answer&&<p className="whitespace-pre-wrap break-words text-sm">{result.answer}</p>}{result.citations&&citations(result.citations)}{result.findings?.map((f,i)=><article key={i} className="rounded-xl bg-amber-400/5 p-3"><p className="text-sm text-amber-200">{f.summary}</p>{citations(f.citations)}</article>)}{result.findings?.length===0&&!result.answer&&<p className="text-sm">Nu au fost semnalate contradicții în eșantion. Este necesară și revizuirea umană.</p>}<p className="text-xs text-slate-400">{result.scope||'Răspuns AI de verificat pe baza surselor citate.'}</p></>}</div>;
}
export default function DocumentsHub({canWrite}:{canWrite:boolean}){
 const [search,setSearch]=useState(''),[category,setCategory]=useState(''),[client,setClient]=useState(''),[offset,setOffset]=useState(0);
 const listing=useCenterData<{data:Doc[];total:number;stale:{id:string;title:string;revision:number;review_after:number}[]}>(`documents?${new URLSearchParams({search,category,client,offset:String(offset)})}`);
 const config=useCenterData<{clients:{id:string;name:string}[];projects:{id:string;name:string;client_id:string}[]}>('config');
 const history=useCenterData<{data:{id:string;result_json:string;created_at:number}[]}>('documents/audits');
 const {busy,act}=useCenterAction();
 const [editing,setEditing]=useState<Doc|null>(null),[opened,setOpened]=useState(false),[file,setFile]=useState<File|null>(null),[question,setQuestion]=useState(''),[result,setResult]=useState<Analysis|null>(null);
 const blank=()=>({title:'',category:'technical',content_text:'',client_id:client,project_id:'',status:'draft',review_after:''});
 const [form,setForm]=useState(blank);
 const edit=(d:Doc|null)=>{setEditing(d);setForm(d?{title:d.title,category:d.category,content_text:d.content_text,client_id:d.client_id||'',project_id:d.project_id||'',status:d.status,review_after:dateInput(d.review_after)}:blank());setFile(null);setOpened(true);};
 const field=(key:keyof typeof form,value:string)=>setForm(f=>({...f,[key]:value}));
 const download=async(d:Doc)=>{const r=await cfAuth.requestResponse(`/api/centers/documents/${d.id}/file`),url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=d.file_name||'document';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const analyze=(mode:'search'|'audit')=>act(async()=>{setResult(null);const value=await centersApi.write<Analysis>('documents/ai',{mode,query:question,client_id:client||null});setResult(value);if(mode==='audit')await history.reload();});
 return <div className="space-y-5">
 <div className={`${panelClass} grid gap-3 sm:grid-cols-3`}><input aria-label="Caută documente" placeholder="Titlu sau conținut…" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}} className={inputClass}/><select aria-label="Categorie documente" value={category} onChange={e=>{setCategory(e.target.value);setOffset(0);}} className={inputClass}><option value="">Toate categoriile</option>{Object.entries(categories).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><select aria-label="Client documente" value={client} onChange={e=>{setClient(e.target.value);setOffset(0);setResult(null);}} className={inputClass}><option value="">Toți clienții / intern Avyron</option>{config.data?.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>
 <Notice error={listing.error||config.error} loading={listing.loading}/>
 {Boolean(listing.data?.stale?.length)&&<details className={`${panelClass} border-amber-400/30`}><summary className="cursor-pointer text-amber-200">Documente de revizuit: {listing.data?.stale.length}</summary>{listing.data?.stale.map(d=><p className="mt-2 text-sm" key={d.id}>{d.title} · v{d.revision} · termen {when(d.review_after)}</p>)}</details>}
 <section className={panelClass}><h2 className="font-semibold">Căutare AI · AVY Knowledge Auditor</h2><p className="my-2 text-xs text-slate-400">Răspunsuri cu citate din maximum 8 documente aprobate, filtrate după client. Documentele expirate sunt excluse din răspunsuri. Fișierele PDF/imagine necesită text extras și revizuit în câmpul de conținut. Cost Guard controlează fiecare apel.</p><textarea aria-label="Întrebare pentru documente" maxLength={500} value={question} onChange={e=>{setQuestion(e.target.value);setResult(null);}} placeholder="Ce prevede contractul despre mentenanță?" className={inputClass}/>{canWrite&&<div className="my-3 flex flex-wrap gap-2"><Button disabled={busy||question.trim().length<3} onClick={()=>void analyze('search')}>Caută cu AI</Button><Button variant="outline" disabled={busy} onClick={()=>void analyze('audit')}>Verifică posibile contradicții</Button></div>}{busy&&<p role="status" className="text-sm">Se procesează…</p>}{result&&<AnalysisView result={result}/>}</section>
 {canWrite&&<Button onClick={()=>edit(null)}>Adaugă document</Button>}
 {opened&&<form className={`${panelClass} grid gap-3 sm:grid-cols-2`} onSubmit={e=>{e.preventDefault();void act(async()=>{
  const saved=await centersApi.write<{id:string}>(`documents${editing?`/${editing.id}`:''}`,{...form,client_id:form.client_id||null,project_id:form.project_id||null,review_after:form.review_after?new Date(form.review_after).getTime():null,...(editing?{revision:editing.revision}:{})},editing?'PATCH':'POST');
  // Metadata is already committed. Keep the editor in sync even if file upload fails.
  const nextRevision=editing?editing.revision+1:1;setEditing({id:saved.id,...form,client_id:form.client_id||null,project_id:form.project_id||null,review_after:form.review_after?new Date(form.review_after).getTime():null,revision:nextRevision,file_name:editing?.file_name||null,updated_at:Date.now()});
  if(file){try{const body=new FormData();body.set('file',file);body.set('revision',String(nextRevision));await cfAuth.request(`/api/centers/documents/${saved.id}/file`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body});}catch(error){await listing.reload();throw new Error(`Documentul a fost salvat, dar fișierul nu a fost încărcat: ${error instanceof Error?error.message:'eroare'}`);}}
  setOpened(false);await listing.reload();toast.success(file?'Document salvat. Fișierul nou necesită reaprobare.':'Document salvat.');
 });}}><h2 className="font-semibold sm:col-span-2">{editing?'Editează documentul':'Document nou'}</h2>
 <label className="grid gap-1 text-sm">Titlu document<input className={inputClass} required maxLength={200} value={form.title} onChange={e=>field('title',e.target.value)}/></label><label className="grid gap-1 text-sm">Categorie<select aria-label="Categorie document" className={inputClass} value={form.category} onChange={e=>field('category',e.target.value)}>{Object.entries(categories).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
 <label className="grid gap-1 text-sm">Client<select className={inputClass} value={form.client_id} onChange={e=>{field('client_id',e.target.value);field('project_id','');}}><option value="">Intern Avyron</option>{config.data?.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="grid gap-1 text-sm">Proiect<select className={inputClass} value={form.project_id} onChange={e=>field('project_id',e.target.value)}><option value="">Fără proiect</option>{config.data?.projects.filter(p=>!form.client_id||p.client_id===form.client_id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 <label className="grid gap-1 text-sm">Stare document<select aria-label="Stare document" className={inputClass} value={form.status} onChange={e=>field('status',e.target.value)}><option value="draft">Ciornă</option><option value="approved">Aprobat pentru AI</option><option value="archived">Arhivat</option></select></label><label className="grid gap-1 text-sm">Revizuire până la<input type="datetime-local" className={inputClass} value={form.review_after} onChange={e=>field('review_after',e.target.value)}/></label>
 <label className="grid gap-1 text-sm sm:col-span-2">Conținut pentru căutare și AI<textarea rows={8} maxLength={24000} className={inputClass} value={form.content_text} onChange={e=>field('content_text',e.target.value)}/></label><label className="grid gap-1 text-sm sm:col-span-2">Fișier privat (PDF, PNG, JPEG, TXT, Markdown, JSON · maximum 10 MB)<input type="file" accept=".pdf,.png,.jpg,.jpeg,.txt,.md,.json" className={inputClass} onChange={e=>{const f=e.target.files?.[0]||null;if(f&&f.size>10000000){toast.error('Fișierul depășește 10 MB.');e.target.value='';setFile(null);}else setFile(f);}}/></label><div className="flex gap-2"><Button disabled={busy}>Salvează documentul</Button><Button type="button" variant="ghost" onClick={()=>setOpened(false)}>Anulează</Button></div></form>}
 <div className="grid gap-3 lg:grid-cols-2">{listing.data?.data.map(d=><article key={d.id} className={`${panelClass} min-w-0`}><p className="text-xs text-violet-300">{categories[d.category]} · {d.status==='approved'?'Aprobat':d.status==='draft'?'Ciornă':'Arhivat'} · v{d.revision}</p><h3 className="my-2 break-words font-semibold">{d.title}</h3><p className="text-xs text-slate-400">Actualizat {when(d.updated_at)}{d.review_after?` · revizuire ${when(d.review_after)}`:''}</p><details className="my-3"><summary className="cursor-pointer text-sm text-violet-300">Conținut document</summary><p className="mt-3 whitespace-pre-wrap break-words text-sm">{d.content_text||'Conținutul nu a fost transcris.'}</p></details><div className="flex flex-wrap gap-2">{canWrite&&<Button variant="outline" onClick={()=>edit(d)}>Editează documentul</Button>}{d.file_name&&<Button variant="outline" disabled={busy} onClick={()=>void act(()=>download(d))}>Descarcă fișierul</Button>}</div></article>)}</div>
 {listing.data?.data.length===0&&<p className="text-sm text-slate-400">Niciun document pentru filtrele selectate.</p>}<div className="flex items-center gap-3"><Button variant="outline" disabled={!offset} onClick={()=>setOffset(n=>Math.max(0,n-30))}>Anterior</Button><span className="text-xs">{listing.data?.total||0} documente</span><Button variant="outline" disabled={offset+30>=(listing.data?.total||0)} onClick={()=>setOffset(n=>n+30)}>Următor</Button></div>
 <details className={panelClass}><summary className="cursor-pointer">Istoric AVY Knowledge Auditor</summary><Notice error={history.error} loading={history.loading}/>{history.data?.data.map(item=><div key={item.id} className="mt-4 border-t border-white/10 pt-4"><p className="mb-2 text-xs text-slate-400">Snapshot {when(item.created_at)} · versiunile citate pot fi între timp modificate</p><AnalysisView result={JSON.parse(item.result_json) as Analysis}/></div>)}</details>
 <details className={panelClass}><summary className="cursor-pointer">Surse existente din Knowledge și AVY Engine</summary><div className="mt-4"><ReportPanel center="documents" canWrite={false}/></div></details>
 </div>;
}
