import { useCallback, useEffect, useRef, useState } from 'react';
import { cfAuth } from '@/lib/cfAuth';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
const input='w-full rounded-xl border border-white/15 bg-[#10172a] p-2.5 text-sm text-slate-100';
const panel='rounded-2xl border border-white/10 bg-[#0d1425] p-4 sm:p-5';
const write=<T,>(path:string,body:unknown={},method='POST')=>cfAuth.request<T>(`/api/operations/${path}`,{method,headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(body)});
function useData<T>(path:string){
 const [data,setData]=useState<T|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);const version=useRef(0);
 const cancel=useCallback(()=>{version.current++;},[]);
 const reload=useCallback(async()=>{const current=++version.current;setLoading(true);setError('');try{const result=await cfAuth.request<T>(`/api/operations/${path}`);if(current===version.current)setData(result);}catch(e){if(current===version.current)setError(e instanceof Error?e.message:'Datele nu pot fi încărcate.');}finally{if(current===version.current)setLoading(false);}},[path]);
 useEffect(()=>{void reload();return cancel;},[reload,cancel]);return {data,error,loading,reload};
}
function useAction(){const [busy,setBusy]=useState(false);const act=async(action:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);try{await action();}catch(e){toast.error(e instanceof Error?e.message:'Acțiunea a eșuat.');}finally{setBusy(false);}};return {busy,act};}
const date=(value:number|null|undefined)=>value?new Date(value).toLocaleString('ro-RO'):'—';
const localDate=(value:number|null)=>value?new Date(value-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
const timestamp=(value:string)=>value?new Date(value).getTime():null;
const labels:Record<string,string>={draft:'Ciornă',pending:'În aprobare',approved:'Aprobat',active:'Activ',done:'Finalizat',cancelled:'Anulat',queued:'În coadă',running:'În execuție',succeeded:'Reușit',failed:'Eșuat',configured:'De verificat',connected:'Verificat',error:'Eroare',disconnected:'Deconectat'};
const money=(value:number|null,currency:string)=>value===null?'—':new Intl.NumberFormat('ro-RO',{style:'currency',currency}).format(value/100);
const minor=(value:string)=>{const match=/^(\d{1,10})(?:[.,](\d{1,2}))?$/.exec(value.trim());return match?Number(match[1])*100+Number((match[2]||'').padEnd(2,'0')):null;};
function Notice({error,loading}:{error:string;loading:boolean}){return <>{error&&<p role="alert" className="text-sm text-rose-300">{error}</p>}{loading&&<p role="status" className="text-sm text-slate-400">Se încarcă…</p>}</>;}
const recordKinds={contract:'Contracte și reînnoiri',change_request:'Cereri de modificare',appointment:'Programări',compliance:'Calendar de conformitate',privacy_request:'Cereri de confidențialitate',experiment:'Registru de experimente'};
type RecordKind=keyof typeof recordKinds;
type OperationRecord={id:string;kind:RecordKind;title:string;description:string;project_id:string|null;client_id:string|null;assignee_id:string|null;status:string;starts_at:number|null;due_at:number|null;amount_minor:number|null;currency:string;revision:number;approved_revision:number|null};
type Config={clients:{id:string;name:string}[];projects:{id:string;name:string;client_id:string|null}[];staff:{id:string;name:string}[];canManageIntegrations:boolean};
export function Records({initialKind='contract'}:{initialKind:RecordKind}){
 const [kind,setKind]=useState<RecordKind>(initialKind),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[offset,setOffset]=useState(0);
 const {data,error,loading,reload}=useData<{data:OperationRecord[];total:number}>(`records?${new URLSearchParams({kind,search,status,offset:String(offset)})}`),config=useData<Config>('config');
 const blank={title:'',description:'',project_id:'',client_id:'',assignee_id:'',status:'draft',starts_at:'',due_at:'',amount:'',currency:'RON'};
 const [form,setForm]=useState(blank),[editing,setEditing]=useState<OperationRecord|null>(null),[showForm,setShowForm]=useState(false);const {busy,act}=useAction();
 const set=(key:keyof typeof blank,value:string)=>setForm(old=>({...old,[key]:value}));
 function edit(row:OperationRecord){setEditing(row);setForm({...row,project_id:row.project_id||'',client_id:row.client_id||'',assignee_id:row.assignee_id||'',starts_at:localDate(row.starts_at),due_at:localDate(row.due_at),amount:row.amount_minor===null?'':String(row.amount_minor/100)});setShowForm(true);}
 const save=()=>act(async()=>{const amount=form.amount?minor(form.amount):null;if(form.amount&&amount===null)throw new Error('Suma trebuie să aibă maximum două zecimale.');
  await write(`records${editing?`/${editing.id}`:''}`,{kind,title:form.title,description:form.description,project_id:form.project_id||null,client_id:form.client_id||null,assignee_id:form.assignee_id||null,status:form.status,starts_at:timestamp(form.starts_at),due_at:timestamp(form.due_at),amount_minor:amount,currency:form.currency,...(editing?{revision:editing.revision}:{})},editing?'PATCH':'POST');setForm(blank);setEditing(null);setShowForm(false);await reload();toast.success('Înregistrare salvată.');});
 return <div className="space-y-4"><div className="flex flex-wrap gap-2">{Object.entries(recordKinds).map(([key,label])=><Button key={key} variant={kind===key?'default':'outline'} onClick={()=>{setKind(key as RecordKind);setOffset(0);setEditing(null);setShowForm(false);setForm(blank);}}>{label}</Button>)}</div>
 <p className="text-sm text-slate-400">{kind==='privacy_request'?'Registrul urmărește solicitarea și verificarea identității. Exportul și ștergerea datelor necesită procedura de execuție dedicată.':kind==='experiment'?'Definește ipoteza, perioada și concluziile. Acest registru nu distribuie automat traficul între variante.':kind==='appointment'?'Selectează responsabilul, începutul și sfârșitul. Programările suprapuse sunt respinse.':'Contractele și costurile suplimentare se aprobă pe versiunea exactă. Aprobarea internă nu semnează un contract și nu facturează clientul.'}</p>
 <div className="grid gap-3 sm:grid-cols-[1fr_180px_auto]"><input aria-label="Caută în registru" placeholder="Caută după titlu sau detalii…" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}} className={input}/><select aria-label="Filtrează starea" value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);}} className={input}><option value="">Toate stările</option>{['draft','pending','approved','active','done','cancelled'].map(value=><option key={value} value={value}>{labels[value]}</option>)}</select><Button onClick={()=>{setEditing(null);setForm(blank);setShowForm(true);}}>Adaugă înregistrare</Button></div>
 <Notice error={error||config.error} loading={loading}/>
 {showForm&&<form className={`${panel} grid gap-3 sm:grid-cols-2`} onSubmit={e=>{e.preventDefault();void save();}}><h3 className="font-semibold sm:col-span-2">{editing?'Editează înregistrarea':'Înregistrare nouă'}</h3>
 <label className="grid gap-1 text-sm">Titlu<input required maxLength={200} value={form.title} onChange={e=>set('title',e.target.value)} className={input}/></label>
 <label className="grid gap-1 text-sm">Stare<select value={form.status} onChange={e=>set('status',e.target.value)} className={input}>{['draft','pending','approved','active','done','cancelled'].map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></label>
 <label className="grid gap-1 text-sm">Client<select value={form.client_id} onChange={e=>setForm(old=>({...old,client_id:e.target.value,project_id:''}))} className={input}><option value="">Fără asociere</option>{config.data?.clients.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
 <label className="grid gap-1 text-sm">Proiect<select value={form.project_id} onChange={e=>set('project_id',e.target.value)} className={input}><option value="">Fără asociere</option>{config.data?.projects.filter(row=>!form.client_id||row.client_id===form.client_id).map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
 <label className="grid gap-1 text-sm">Responsabil<select value={form.assignee_id} onChange={e=>set('assignee_id',e.target.value)} className={input}><option value="">Neasignat</option>{config.data?.staff.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
 <label className="grid gap-1 text-sm">Început<input type="datetime-local" value={form.starts_at} onChange={e=>set('starts_at',e.target.value)} className={input}/></label>
 <label className="grid gap-1 text-sm">Termen / reînnoire<input type="datetime-local" value={form.due_at} onChange={e=>set('due_at',e.target.value)} className={input}/></label>
 <div className="flex gap-2"><label className="grid min-w-0 flex-1 gap-1 text-sm">Valoare<input inputMode="decimal" value={form.amount} onChange={e=>set('amount',e.target.value)} className={input}/></label><label className="grid gap-1 text-sm">Valută<select value={form.currency} onChange={e=>set('currency',e.target.value)} className={input}>{['RON','EUR','USD','GBP','CHF'].map(currency=><option key={currency}>{currency}</option>)}</select></label></div>
 <label className="grid gap-1 text-sm sm:col-span-2">Detalii / concluzii<textarea rows={4} maxLength={8000} value={form.description} onChange={e=>set('description',e.target.value)} className={input}/></label>
 <div className="flex gap-2"><Button disabled={busy}>Salvează înregistrarea</Button><Button type="button" variant="outline" onClick={()=>setShowForm(false)}>Anulează</Button></div></form>}
 <div className="space-y-3">{data?.data.map(row=><article key={row.id} className={panel}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{row.title}</h3><p className="text-xs text-slate-400">{labels[row.status]} · versiunea {row.revision} · termen {date(row.due_at)}{row.approved_revision?` · aprobare v${row.approved_revision}`:''}</p></div>{row.amount_minor!==null&&<span>{money(row.amount_minor,row.currency)}</span>}</div><p className="my-3 whitespace-pre-wrap break-words text-sm text-slate-300">{row.description}</p><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>edit(row)}>Editează</Button>{['contract','change_request'].includes(row.kind)&&row.status==='pending'&&config.data?.canManageIntegrations&&<Button disabled={busy} onClick={()=>void act(async()=>{await write(`records/${row.id}/approve`,{revision:row.revision});await reload();})}>Aprobă versiunea {row.revision}</Button>}<Button disabled={busy} variant="ghost" onClick={()=>void act(async()=>{await write(`records/${row.id}`,{revision:row.revision},'DELETE');await reload();})}>Arhivează</Button></div></article>)}{!loading&&data?.data.length===0&&<p className="text-sm text-slate-400">Nicio înregistrare.</p>}</div>
 <div className="flex items-center gap-3"><Button variant="outline" disabled={!offset||loading} onClick={()=>setOffset(value=>Math.max(0,value-50))}>Înapoi</Button><span className="text-sm">{data?.total||0} înregistrări</span><Button variant="outline" disabled={offset+50>=(data?.total||0)||loading} onClick={()=>setOffset(value=>value+50)}>Următoarele</Button></div></div>;
}
const actionLabels={briefing:'AVY Briefing',deadlines:'Termene și reînnoiri',health:'Verificare infrastructură'};
type Action=keyof typeof actionLabels;
type Rule={manual_minutes_saved:number|null;successful_runs:number;id:string;name:string;action:Action;interval_minutes:number;enabled:number;revision:number;next_run_at:number};
type Job={id:string;action:Action;status:string;attempts:number;result_json:string|null;error_code:string|null;created_at:number};
function Report({value}:{value:unknown}){
 const report=value as {generated_at?:number;checked_at?:number;probes?:{service:string;status:string}[];work?:{id:string;title:string;due_at:number}[];records?:{id:string;title:string;due_at:number}[];open_leads?:{total:number};approvals?:{total:number};receipts_30_days?:{currency:string;amount_minor:number}[]};
 return <div className="space-y-2 rounded-xl bg-white/5 p-3 text-sm"><p className="text-slate-400">Generat: {date(report.generated_at||report.checked_at)}</p>{report.probes?.map(row=><p key={row.service}>{row.service}: <strong>{row.status==='ok'?'Operație reușită':'Eroare'}</strong></p>)}{report.open_leads&&<p>Leaduri deschise: {report.open_leads.total} · Aprobări: {report.approvals?.total||0}</p>}{report.receipts_30_days?.map(row=><p key={row.currency}>Încasări în 30 zile: {money(row.amount_minor,row.currency)}</p>)}{[...(report.work||[]),...(report.records||[])].map(row=><p key={row.id}>{row.title} · {date(row.due_at)}</p>)}</div>;
}
export function Automations(){
 const {data,error,loading,reload}=useData<{data:Rule[];jobs:Job[]}>('automations'),{busy,act}=useAction();
 const [minutes,setMinutes]=useState('');
 const [name,setName]=useState(''),[action,setAction]=useState<Action>('briefing'),[interval,setInterval]=useState(1440),[enabled,setEnabled]=useState(false),[editing,setEditing]=useState<Rule|null>(null),[preview,setPreview]=useState<unknown>(null);
 return <div className="space-y-4"><p className="text-sm text-slate-400">Execuții în Cloudflare, cu istoric și notificări interne. Rulările programate sunt preluate la intervale de 15 minute după activarea Workerului.</p><Notice error={error} loading={loading}/><form className={`${panel} grid gap-3 sm:grid-cols-2`} onSubmit={e=>{e.preventDefault();void act(async()=>{await write(`automations${editing?`/${editing.id}`:''}`,{name,action,interval_minutes:interval,enabled,manual_minutes_saved:minutes===''?null:Number(minutes),...(editing?{revision:editing.revision}:{})},editing?'PATCH':'POST');setName('');setEditing(null);await reload();});}}><label className="grid gap-1 text-sm">Nume automatizare<input required maxLength={160} value={name} onChange={e=>setName(e.target.value)} className={input}/></label><label className="grid gap-1 text-sm">Acțiune<select value={action} onChange={e=>setAction(e.target.value as Action)} className={input}>{Object.entries(actionLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="grid gap-1 text-sm">Interval în minute<input required type="number" min={15} max={10080} value={interval} onChange={e=>setInterval(Number(e.target.value))} className={input}/></label><label className="grid gap-1 text-sm">Minute economisite / execuție (estimare proprie)<input type="number" min={0} max={10080} value={minutes} onChange={e=>setMinutes(e.target.value)} className={input}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Programare activă</label><div className="flex flex-wrap gap-2 sm:col-span-2"><Button disabled={busy}>{editing?'Salvează automatizarea':'Creează automatizarea'}</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>void act(async()=>setPreview(await write('preview',{action})))}>Simulează raportul</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>void act(async()=>{await write('jobs',{action});await reload();toast.success('Execuție pusă în coadă.');})}>Execută acum</Button><Button type="button" variant="ghost" onClick={()=>void reload()}>Actualizează istoricul</Button></div></form>{preview!==null&&<Report value={preview}/>}
 {data?.data.map(rule=><article className={panel} key={rule.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">{rule.name}</h3><p className="text-sm text-slate-400">{actionLabels[rule.action]} · {rule.enabled?'Activă':'Oprită'} · următoarea: {date(rule.next_run_at)}</p><p className="text-xs text-slate-400">{rule.successful_runs||0} execuții reușite · economie estimată: {rule.manual_minutes_saved==null?'neconfigurată':`${(rule.successful_runs||0)*rule.manual_minutes_saved} minute (estimare proprie)`}</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>{setEditing(rule);setName(rule.name);setAction(rule.action);setInterval(rule.interval_minutes);setEnabled(Boolean(rule.enabled));setMinutes(rule.manual_minutes_saved===null||rule.manual_minutes_saved===undefined?'':String(rule.manual_minutes_saved));}}>Editează</Button><Button variant="outline" disabled={busy} onClick={()=>void act(async()=>{await write(`automations/${rule.id}`,{name:rule.name,action:rule.action,interval_minutes:rule.interval_minutes,enabled:!rule.enabled,manual_minutes_saved:rule.manual_minutes_saved,revision:rule.revision},'PATCH');await reload();})}>{rule.enabled?'Oprește':'Activează'}</Button></div></div></article>)}
 <h3 className="font-semibold">Istoric execuții</h3>{data?.jobs.map(job=><details key={job.id} className={panel}><summary className="cursor-pointer text-sm">{actionLabels[job.action]} · {labels[job.status]} · {date(job.created_at)} · {job.attempts} încercări</summary><div className="mt-3 space-y-3">{job.error_code&&<p className="text-rose-300">{job.error_code}</p>}{job.result_json&&<Report value={JSON.parse(job.result_json)}/>}<div className="flex gap-2">{job.status==='failed'&&<Button disabled={busy} onClick={()=>void act(async()=>{await write(`jobs/${job.id}/retry`);await reload();})}>Reîncearcă</Button>}{['running','queued'].includes(job.status)&&<Button disabled={busy} onClick={()=>void act(async()=>{await write(`jobs/${job.id}/cancel`);await reload();})}>Anulează execuția</Button>}</div></div></details>)}</div>;
}
type Account={id:string;provider:string;label:string;environment:'test'|'live';status:string;revision:number;checked_at:number|null;synced_at:number|null;error_code:string|null;has_credential:number};
export function Integrations(){
 const {data,error,loading,reload}=useData<{providers:Record<string,{name:string;description:string;documentation:string}>;data:Account[];canEdit:boolean}>('integrations'),{busy,act}=useAction();
 const [provider,setProvider]=useState('stripe'),[label,setLabel]=useState(''),[environment,setEnvironment]=useState('test'),[selected,setSelected]=useState<Account|null>(null),[token,setToken]=useState(''),[documents,setDocuments]=useState<{external_id:string;kind:string;data:Record<string,unknown>}[]>([]);
 return <div className="space-y-4"><p className="text-sm text-slate-400">Conectează conturile proprii cu permisiuni de citire. Verificarea și sincronizarea apelează furnizorul selectat; nu trimit facturi și nu inițiază plăți. Pentru Revolut, tokenul de acces expirat se înlocuiește aici.</p><Notice error={error} loading={loading}/>
 {data?.canEdit&&<form className={`${panel} grid gap-3 sm:grid-cols-3`} onSubmit={e=>{e.preventDefault();void act(async()=>{await write('integrations',{provider,label,environment});setLabel('');await reload();});}}><label className="grid gap-1 text-sm">Furnizor<select value={provider} onChange={e=>{setProvider(e.target.value);if(['github','cloudflare'].includes(e.target.value))setEnvironment('live');}} className={input}>{Object.entries(data.providers).map(([key,row])=><option key={key} value={key}>{row.name}</option>)}</select></label><label className="grid gap-1 text-sm">Denumire cont<input required maxLength={120} value={label} onChange={e=>setLabel(e.target.value)} className={input}/></label><label className="grid gap-1 text-sm">Mediu<select value={environment} onChange={e=>setEnvironment(e.target.value)} className={input}>{!['github','cloudflare'].includes(provider)&&<option value="test">Test / sandbox</option>}<option value="live">Cont real</option></select></label><Button disabled={busy}>Adaugă cont</Button><p className="text-xs text-slate-400 sm:col-span-2">{data.providers[provider]?.description}</p></form>}
 {selected&&data?.canEdit&&<form className={`${panel} space-y-3`} onSubmit={e=>{e.preventDefault();void act(async()=>{try{await write(`integrations/${selected.id}/credential`,{token,revision:selected.revision},'PUT');setSelected(null);await reload();toast.success('Cheie salvată securizat. Verifică acum conexiunea.');}finally{setToken('');}});}}><h3 className="font-semibold">Activează / înlocuiește cheia · {selected.label}</h3><label className="grid gap-1 text-sm">Token API<input required type="password" autoComplete="new-password" spellCheck={false} maxLength={8000} value={token} onChange={e=>setToken(e.target.value)} className={input}/></label><p className="text-xs text-slate-400">Cheia este criptată în Cloudflare și nu va fi afișată din nou. Rotirea ei invalidează verificarea și datele sincronizate anterior.</p><div className="flex gap-2"><Button disabled={busy}>Salvează cheia</Button><Button type="button" variant="outline" onClick={()=>{setSelected(null);setToken('');}}>Anulează</Button></div></form>}
 {data?.data.map(account=><article key={account.id} className={panel}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{account.label} <span className="text-xs text-slate-400">{data.providers[account.provider]?.name} · {account.environment}</span></h3><p className="text-sm text-slate-400">{labels[account.status]} · verificat {date(account.checked_at)} · sincronizat {date(account.synced_at)}</p>{account.error_code&&<p className="text-xs text-rose-300">{account.error_code}</p>}</div><a className="text-xs text-violet-300" href={data.providers[account.provider]?.documentation} target="_blank" rel="noreferrer">Documentație furnizor ↗</a></div><div className="mt-3 flex flex-wrap gap-2">{data.canEdit&&<><Button variant="outline" onClick={()=>{setSelected(account);setToken('');setDocuments([]);}}>Configurează cheia</Button>{(['verify','sync','disconnect'] as const).map(action=><Button key={action} disabled={busy||!account.has_credential} variant="outline" onClick={()=>void act(async()=>{try{await write(`integrations/${account.id}/${action}`);setDocuments([]);}finally{await reload();}toast.success(action==='sync'?'Date sincronizate.':action==='verify'?'Conexiune verificată.':'Cont deconectat.');})}>{action==='verify'?'Verifică':action==='sync'?'Sincronizează':'Deconectează'}</Button>)}</>}<Button variant="ghost" onClick={()=>void act(async()=>{const result=await cfAuth.request<{data:typeof documents}>(`/api/operations/integrations/${account.id}/documents`);setDocuments(result.data);})}>Vezi datele importate</Button></div></article>)}
 {documents.length>0&&<section className={panel}><h3 className="mb-3 font-semibold">Date importate pentru revizuire</h3><p className="mb-3 text-xs text-slate-400">Importul păstrează identificatorii furnizorului și nu modifică automat registrul financiar. Fiecare sincronizare preia cel mult 100 documente, respectiv 50 zone Cloudflare.</p><div className="grid gap-2 sm:grid-cols-2">{documents.map(row=><article key={row.external_id} className="min-w-0 rounded-xl bg-white/5 p-3"><p className="break-all text-xs text-slate-400">{row.external_id}</p>{Object.entries(row.data).map(([key,value])=><p key={key} className="break-words text-sm"><span className="text-slate-400">{({name:'Nume',number:'Număr',status:'Stare',currency:'Valută',amount_due:'Sold de plată (unități minore)',amount_paid:'Încasat (unități minore)',total:'Total (unități minore)',balance:'Sold',state:'Stare',private:'Privat',default_branch:'Ramură principală',updated_at:'Actualizat',created:'Creat',due_date:'Scadență'} as Record<string,string>)[key]||key}: </span>{value===null?'—':String(value)}</p>)}</article>)}</div></section>}
 <p className="text-xs text-slate-400">FGO, NETOPIA, Ads și conturile sociale necesită fluxurile specifice furnizorilor. Nu sunt prezentate ca integrări conectate.</p></div>;
}
type Agent={slug:string;name:string;status:string;version_id:string|null;current_version:number;version_status:string;model:string;max_tokens:number;stopped:number};
type Run={id:string;agent_slug:string;status:string;input_tokens:number;output_tokens:number;usage_source:string;actual_cost_micros:number|null;started_at:number};
type Evaluation={score:number;checks:{name:string;passed:boolean}[];matches:{id:string;question:string;score:number;source:string}[];reply:string|null};
export function Agents(){
 const {data,error,loading,reload}=useData<{data:Agent[];runs:Run[];evaluations:{id:string;case_name:string;status:string;score:number;created_at:number}[]}>('agents'),config=useData<Config>('config'),{busy,act}=useAction();
 const [question,setQuestion]=useState(''),[result,setResult]=useState<Evaluation|null>(null);
 return <div className="space-y-4"><Notice error={error} loading={loading}/><p className="text-sm text-slate-400">Agenții folosesc configurația aprobată. Întrebările identice cu o cunoștință validată primesc răspuns direct; cunoștințele expirate sunt excluse. Verificarea de mai jos testează configurarea și căutarea, fără consum de model.</p><label className="grid gap-1 text-sm">Întrebare pentru evaluare<input value={question} onChange={e=>setQuestion(e.target.value)} maxLength={1000} placeholder="Introdu o întrebare reprezentativă pentru agent…" className={input}/></label><div className="grid gap-3 md:grid-cols-2">{data?.data.map(agent=><article key={agent.slug} className={panel}><h3 className="font-semibold">{agent.name}</h3><p className="mt-1 break-all text-xs text-slate-400">v{agent.current_version} · {agent.version_status} · {agent.model}</p><p className="mt-1 text-sm">{agent.stopped?'Oprit din controlul de siguranță':labels[agent.status]||agent.status} · maximum {agent.max_tokens} tokenuri</p><div className="mt-3 flex flex-wrap gap-2"><Button disabled={busy||question.trim().length<2} onClick={()=>void act(async()=>{setResult(await write<Evaluation>(`agents/${agent.slug}/evaluate`,{question,expected_knowledge_id:null}));await reload();})}>Verifică agentul</Button>{config.data?.canManageIntegrations&&<Button variant="outline" disabled={busy} onClick={()=>void act(async()=>{await write(`agents/${agent.slug}/stop`,{enabled:!agent.stopped,reason:agent.stopped?'Reluare manuală din consola AVYRON':'Oprire manuală din consola AVYRON'});await reload();})}>{agent.stopped?'Reia':'Oprește'}</Button>}</div></article>)}</div>
 {result&&<section className={panel}><h3 className="font-semibold">Verificare: {Math.round(result.score*100)}%</h3>{result.checks.map(check=><p key={check.name} className="mt-2 text-sm">{check.passed?'✓':'!'} {({approved_version:'Versiune aprobată',cloudflare_model:'Model Cloudflare',bounded_output:'Limită de răspuns',platform_instructions:'Instrucțiuni și reguli',knowledge_coverage:'Acoperire în baza de cunoștințe',expected_knowledge:'Sursa așteptată'} as Record<string,string>)[check.name]}</p>)}{result.reply&&<p className="my-3 whitespace-pre-wrap text-sm">{result.reply}</p>}{result.matches.map(row=><p key={row.id} className="text-xs text-slate-400">Sursă: {row.question} · {row.source}</p>)}</section>}
 <h3 className="font-semibold">Execuții recente și consum</h3><div className="overflow-x-auto rounded-xl border border-white/10"><table className="w-full text-left text-sm"><thead><tr>{['Agent','Stare','Intrare / ieșire','Sursa consumului','Cost efectiv','Data'].map(value=><th className="p-3" key={value}>{value}</th>)}</tr></thead><tbody>{data?.runs.map(run=><tr key={run.id} className="border-t border-white/10"><td className="p-3">{run.agent_slug}</td><td className="p-3">{labels[run.status]||run.status}</td><td className="p-3">{run.input_tokens} / {run.output_tokens}</td><td className="p-3">{run.usage_source==='provider'?'Raportat de furnizor':run.usage_source==='retrieval'?'Fără apel de model':'Estimare / rezervare'}</td><td className="p-3">{run.actual_cost_micros===null?'Necunoscut':`${run.actual_cost_micros} micro-unități`}</td><td className="p-3">{date(run.started_at)}</td></tr>)}</tbody></table></div>
 <details className={panel}><summary>Istoric evaluări</summary>{data?.evaluations.map(row=><p key={row.id} className="mt-2 text-sm">{row.case_name} · {Math.round(row.score*100)}% · {date(row.created_at)}</p>)}</details></div>;
}
function Notifications(){const {data,error,loading,reload}=useData<{data:{id:string;title:string;body:string;read_at:number|null;created_at:number}[]}>('notifications'),{busy,act}=useAction();return <div className="space-y-3"><Notice error={error} loading={loading}/>{data?.data.map(row=><article key={row.id} className={panel}><h3 className="font-semibold">{row.title}</h3><p className="my-2 text-sm text-slate-400">{row.body} · {date(row.created_at)}</p>{!row.read_at&&<Button variant="outline" disabled={busy} onClick={()=>void act(async()=>{await write(`notifications/${row.id}/read`);await reload();})}>Marchează citită</Button>}</article>)}{data?.data.length===0&&<p className="text-sm text-slate-400">Nicio notificare internă.</p>}</div>;}
export default function OperationsConsole(){
 const [tab,setTab]=useState('records');
 return <section className="space-y-5"><header><p className="text-xs uppercase tracking-widest text-violet-300">AVYRON OS · Cloudflare</p><h2 className="mt-2 text-2xl font-semibold">Centrul operațional</h2><p className="mt-1 text-sm text-slate-400">Organizează livrarea, programează rapoarte și gestionează conturile conectate.</p></header><nav className="flex flex-wrap gap-2" aria-label="Module operaționale">{Object.entries({records:'Registre',automations:'Automatizări',integrations:'Integrări',agents:'Agenți și evaluări',notifications:'Notificări'}).map(([id,label])=><Button key={id} variant={id===tab?'default':'outline'} onClick={()=>setTab(id)}>{label}</Button>)}</nav>{tab==='records'?<Records initialKind="contract"/>:tab==='automations'?<Automations/>:tab==='integrations'?<Integrations/>:tab==='agents'?<Agents/>:<Notifications/>}</section>;
}
