import { useEffect, useState } from "react";
import { ArrowUpRight, BookOpen, BriefcaseBusiness } from "lucide-react";
import { adminOperationsApi, type InternalResource } from "@/lib/adminOperationsApi";

export default function ResourceSurfaceTab({ kind }: { kind: "career" | "library" }) {
  const [items, setItems] = useState<InternalResource[]>([]);
  useEffect(() => { adminOperationsApi.resources().then((result) => setItems(result.data.filter((item) => item.kind === kind))).catch(() => setItems([])); }, [kind]);
  const careers = kind === "career";
  const Icon = careers ? BriefcaseBusiness : BookOpen;
  return <div className="space-y-4 text-slate-100"><header className="rounded-2xl border border-white/[0.08] bg-gradient-to-br from-violet-500/[0.10] via-[#11182d] to-cyan-400/[0.07] p-5 sm:p-6"><Icon className="size-5 text-violet-300" /><h1 className="mt-3 font-display text-2xl font-bold text-white">{careers ? "Cariere" : "Bibliotecă"}</h1><p className="mt-1 max-w-3xl text-sm text-slate-400">{careers ? "Roluri, resurse de recrutare și elemente planificate pentru viitoarea zonă de cariere." : "Surse, referințe, instrumente și materiale utile centralizate fără duplicate."}</p><a href={careers ? "/cariere" : "/biblioteca"} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1.5 rounded-xl border border-white/10 px-3 py-2 text-xs text-cyan-300 hover:bg-white/[0.04]">Deschide pagina publică <ArrowUpRight className="size-3.5" /></a></header><section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item.id} className="rounded-2xl border border-white/[0.08] bg-[#10162a]/90 p-4"><p className="text-[10px] uppercase tracking-[0.14em] text-violet-300/70">{item.category} · {item.status}</p><h2 className="mt-2 text-sm font-semibold text-slate-200">{item.title}</h2><p className="mt-1 text-xs leading-relaxed text-slate-500">{item.description || "Descriere necompletată."}</p>{item.url && <a href={item.url} target="_blank" rel="noreferrer" className="mt-3 inline-flex text-xs text-cyan-300">Deschide ↗</a>}</article>)}{items.length === 0 && <div className="rounded-2xl border border-dashed border-white/10 p-7 text-sm text-slate-500 md:col-span-2 xl:col-span-3">Nu există încă înregistrări. Adaugă-le din „Documente și Resurse” pentru a păstra o singură sursă de adevăr.</div>}</section></div>;
}
