import { useCallback, useEffect, useState } from 'react';
import { cfAuth } from '@/lib/cfAuth';
import { financeApi, type FinanceRevenue } from '@/lib/financeApi';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
type Receipt={id:string;amount_minor:number;currency:string;reference:string;paid_at:number;invoice_number:string|null;service_name:string};
type Result={data:Receipt[];totals:{currency:string;amount_minor:number;count:number}[];canWrite:boolean};
const money=(amount:number,currency:string)=>new Intl.NumberFormat('ro-RO',{style:'currency',currency}).format(amount/100);
const minor=(value:string)=>{const match=/^(\d{1,10})(?:[.,](\d{1,2}))?$/.exec(value.trim());return match?Number(match[1])*100+Number((match[2]||'').padEnd(2,'0')):null;};
export function StaffPaymentsTab(){
 const [result,setResult]=useState<Result|null>(null),[revenues,setRevenues]=useState<FinanceRevenue[]>([]),[error,setError]=useState(''),[offset,setOffset]=useState(0),[saving,setSaving]=useState(false);
 const [revenueId,setRevenueId]=useState(''),[amount,setAmount]=useState(''),[ron,setRon]=useState(''),[reference,setReference]=useState(''),[paidAt,setPaidAt]=useState('');
 const load=useCallback(async()=>{setError('');try{const [receipts,invoices]=await Promise.all([cfAuth.request<Result>(`/api/finance/receipts?offset=${offset}`),financeApi.revenues()]);setResult(receipts);setRevenues(invoices.data);}catch(e){setError(e instanceof Error?e.message:'Încasările nu pot fi încărcate.');}},[offset]);
 useEffect(()=>{void load();},[load]);
 const selected=revenues.find(r=>r.id===revenueId);
 async function save(e:React.FormEvent){e.preventDefault();const amountMinor=minor(amount),ronMinor=ron?minor(ron):null;if(!amountMinor||(ron&& !ronMinor))return toast.error('Introdu sume pozitive, cu maximum două zecimale.');setSaving(true);
  try{await cfAuth.request('/api/finance/receipts',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({revenue_id:revenueId,amount_minor:amountMinor,amount_ron_minor:ronMinor,reference,paid_at:new Date(paidAt).getTime()})});setAmount('');setReference('');setRon('');await load();toast.success('Încasare înregistrată.');}catch(e){toast.error(e instanceof Error?e.message:'Înregistrarea a eșuat.');}finally{setSaving(false);}}
 const cls='rounded-lg border bg-background p-2 text-sm';
 return <section className="space-y-4"><header><h2 className="text-2xl font-semibold">Încasări înregistrate</h2><p className="text-sm text-muted-foreground">Înregistrează sumele deja primite, inclusiv plățile parțiale. Această acțiune nu transferă bani.</p></header>{error&&<p role="alert" className="text-destructive">{error}</p>}
 <div className="flex flex-wrap gap-3">{result?.totals.map(t=><div key={t.currency} className="rounded-xl border bg-card p-4"><p className="text-sm text-muted-foreground">Total înregistrat · {t.count} încasări</p><p className="text-xl font-semibold">{money(t.amount_minor,t.currency)}</p></div>)}</div>
 {result?.canWrite&&<form onSubmit={save} className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">Document<select required value={revenueId} onChange={e=>setRevenueId(e.target.value)} className={cls}><option value="">Selectează documentul</option>{revenues.filter(r=>['invoiced','sent','partially_paid','overdue'].includes(r.status)).map(r=><option key={r.id} value={r.id}>{r.invoice_number||r.service_name} · {r.currency}</option>)}</select></label><label className="grid gap-1 text-sm">Suma primită ({selected?.currency||'valuta documentului'})<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} className={cls}/></label><label className="grid gap-1 text-sm">Referință unică încasare<input required maxLength={200} value={reference} onChange={e=>setReference(e.target.value)} className={cls}/></label><label className="grid gap-1 text-sm">Data încasării<input required type="datetime-local" value={paidAt} onChange={e=>setPaidAt(e.target.value)} className={cls}/></label>{selected?.currency!=='RON'&&<label className="grid gap-1 text-sm">Echivalent RON documentat (opțional)<input inputMode="decimal" value={ron} onChange={e=>setRon(e.target.value)} className={cls}/></label>}<Button disabled={saving||!revenueId} className="self-end">{saving?'Se salvează…':'Înregistrează încasarea'}</Button></form>}
 <div className="divide-y rounded-xl border bg-card px-4">{result?.data.map(r=><article key={r.id} className="flex flex-wrap justify-between gap-3 py-3"><div><p className="font-medium">{r.invoice_number||r.service_name}</p><p className="text-xs text-muted-foreground">{r.reference} · {new Date(r.paid_at).toLocaleString('ro-RO')}</p></div><p>{money(r.amount_minor,r.currency)}</p></article>)}{result&&!result.data.length&&<p className="p-4 text-sm text-muted-foreground">Nicio încasare în registru. Documentele istorice marcate plătite rămân vizibile în Financiar.</p>}</div>
 <div className="flex gap-2"><Button variant="outline" disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-50))}>Înapoi</Button><Button variant="outline" disabled={result?.data.length!==50} onClick={()=>setOffset(v=>v+50)}>Următoarele</Button></div></section>;
}
