import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { centers, departments, departmentLabels, defaultReads, ownerOnly, type Department, type StaffPolicy, type CenterId } from '@/shared/osCatalog';
import { centersApi } from '@/lib/centersApi';
import { Button } from '@/components/ui/button';
import { Notice } from './CenterPanels';
import {inputClass,useCenterAction,useCenterData} from './centerHooks';
export default function StaffPrivilegesEditor({userId}:{userId:string}){
 const {data,error,loading,reload}=useCenterData<StaffPolicy>(`team/${userId}`),[policy,setPolicy]=useState<StaffPolicy|null>(null),{busy,act}=useCenterAction();
 useEffect(()=>setPolicy(data),[data]);
 const toggle=(id:CenterId,write:boolean,checked:boolean)=>setPolicy(p=>{if(!p)return p;const read=new Set(p.read),writes=new Set(p.write);if(write){if(checked){read.add(id);writes.add(id);}else writes.delete(id);}else if(checked)read.add(id);else{read.delete(id);writes.delete(id);}return {...p,read:[...read],write:[...writes]};});
 return <section className="my-4 space-y-3 rounded-xl border border-violet-400/20 p-3"><h3 className="font-semibold">Rol profesional și privilegii în centre</h3><Notice error={error} loading={loading}/>{policy&&<><label className="grid gap-1 text-sm">Denumirea funcției<input value={policy.job_title} onChange={e=>setPolicy({...policy,job_title:e.target.value})} maxLength={120} className={inputClass}/></label><label className="grid gap-1 text-sm">Dashboard profesional<select value={policy.department} onChange={e=>{const department=e.target.value as Department;setPolicy({...policy,department,read:defaultReads(department),write:[]});}} className={inputClass}>{departments.map(d=><option key={d} value={d}>{departmentLabels[d]}</option>)}</select></label><p className="text-xs text-slate-400">Schimbarea profilului propune acces de citire. Activează separat modificările necesare. Controlul financiar global, aprobările AI și seiful rămân rezervate Super Adminului.</p><div className="max-h-52 space-y-2 overflow-y-auto">{centers.filter(c=>!ownerOnly.includes(c.id)).map(c=><div key={c.id} className="flex flex-wrap items-center gap-3 border-b border-white/5 pb-2 text-xs"><span className="min-w-36 flex-1">{c.name}</span><label className="flex gap-1"><input type="checkbox" checked={policy.read.includes(c.id)} onChange={e=>toggle(c.id,false,e.target.checked)}/>Citește</label><label className="flex gap-1"><input type="checkbox" checked={policy.write.includes(c.id)} onChange={e=>toggle(c.id,true,e.target.checked)}/>Modifică</label></div>)}</div><Button type="button" disabled={busy||loading} onClick={()=>void act(async()=>{await centersApi.write(`team/${userId}`,policy,'PUT');toast.success('Privilegiile au fost salvate și auditate.');await reload();})}>Salvează privilegiile</Button></>}</section>;
}
