/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=CloudflareBindings cloudflare/workers/api/src/worker-configuration.d.ts` (hash: b979c0c0a4d7590ecf7bb01425f1a49a)
interface __BaseEnv_CloudflareBindings {
	KV: KVNamespace;
	FILES: R2Bucket;
	MEDIA: R2Bucket;
	DB: D1Database;
	SURVEY_EMAIL: SendEmail;
	ASYNC_JOBS: Queue;
	PUBLIC_API_RATE_LIMITER: RateLimit;
	AI: Ai;
	ASSETS: Fetcher;
	APP_ENV: "preview" | "production";
	ADMIN_MFA_POLICY: "disabled";
	MFA_AUTH_ENABLED: "false";
	TURNSTILE_AUTH_ENABLED: "false";
	PAID_AI_ENABLED: "false";
	ALLOW_AI_OVERAGE: "false";
	AUTO_AI_UPGRADE: "false";
	ALLOWED_ORIGINS: "https://surveys.avyron.ro,https://avyron.ro,https://www.avyron.ro,https://app.avyron.ro,https://api.avyron.ro,https://avyrontech-preview.avyrontech.workers.dev,https://avyrontech.lovable.app,http://localhost:8080" | "https://surveys.avyron.ro,https://avyron.ro,https://www.avyron.ro,https://app.avyron.ro,https://api.avyron.ro,https://avyrontech.lovable.app,https://id-preview--3432ba2d-bd12-41f5-9dc2-a3e04fe788d0.lovable.app,https://3432ba2d-bd12-41f5-9dc2-a3e04fe788d0.lovableproject.com,http://localhost:8080";
	APP_URL: "https://avyrontech-preview.avyrontech.workers.dev" | "https://avyron.ro";
	SMTP_HOST: "smtp.mx.cloudflare.net";
	SMTP_PORT: "465";
	SMTP_USER: "api_token";
	SMTP_FROM: "contact@avyron.ro";
	LEAD_TO: "avyrontech@gmail.com";
	SUPABASE_DATA_OPERATIONS_ENABLED: "false";
	GOOGLE_DRIVE_DATA_OPERATIONS_ENABLED: "false";
	BACKUP_JOBS_ENABLED: "false";
	TURNSTILE_ALLOWED_HOSTNAMES: "surveys.avyron.ro,app.avyron.ro,*.avyrontech.workers.dev,avyrontech.lovable.app,localhost" | "surveys.avyron.ro,avyron.ro,www.avyron.ro,app.avyron.ro,avyrontech.pages.dev,*.avyrontech.pages.dev,*.avyrontech.workers.dev,avyrontech.lovable.app,localhost";
	JWT_SECRET: string;
	MFA_ENCRYPTION_KEY: string;
	AVYRON_AGENT_RUNTIME: DurableObjectNamespace<import("./index").AvyronAgentRuntime>;
	AVYRON_WORKFLOW: Workflow<Parameters<import("./index").AvyronMaintenanceWorkflow['run']>[0]['payload']>;
	TURNSTILE_SECRET?: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "AvyronAgentRuntime";
	}
	interface PreviewEnv {
		KV: KVNamespace;
		FILES: R2Bucket;
		MEDIA: R2Bucket;
		DB: D1Database;
		SURVEY_EMAIL: SendEmail;
		ASYNC_JOBS: Queue;
		PUBLIC_API_RATE_LIMITER: RateLimit;
		AI: Ai;
		ASSETS: Fetcher;
		APP_ENV: "preview";
		ADMIN_MFA_POLICY: "disabled";
		MFA_AUTH_ENABLED: "false";
		TURNSTILE_AUTH_ENABLED: "false";
		PAID_AI_ENABLED: "false";
		ALLOW_AI_OVERAGE: "false";
		AUTO_AI_UPGRADE: "false";
		ALLOWED_ORIGINS: "https://surveys.avyron.ro,https://avyron.ro,https://www.avyron.ro,https://app.avyron.ro,https://api.avyron.ro,https://avyrontech-preview.avyrontech.workers.dev,https://avyrontech.lovable.app,http://localhost:8080";
		APP_URL: "https://avyrontech-preview.avyrontech.workers.dev";
		SMTP_HOST: "smtp.mx.cloudflare.net";
		SMTP_PORT: "465";
		SMTP_USER: "api_token";
		SMTP_FROM: "contact@avyron.ro";
		LEAD_TO: "avyrontech@gmail.com";
		SUPABASE_DATA_OPERATIONS_ENABLED: "false";
		GOOGLE_DRIVE_DATA_OPERATIONS_ENABLED: "false";
		BACKUP_JOBS_ENABLED: "false";
		TURNSTILE_ALLOWED_HOSTNAMES: "surveys.avyron.ro,app.avyron.ro,*.avyrontech.workers.dev,avyrontech.lovable.app,localhost";
		JWT_SECRET: string;
		MFA_ENCRYPTION_KEY: string;
		AVYRON_AGENT_RUNTIME: DurableObjectNamespace<import("./index").AvyronAgentRuntime>;
		AVYRON_WORKFLOW: Workflow<Parameters<import("./index").AvyronMaintenanceWorkflow['run']>[0]['payload']>;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "ADMIN_MFA_POLICY" | "MFA_AUTH_ENABLED" | "TURNSTILE_AUTH_ENABLED" | "PAID_AI_ENABLED" | "ALLOW_AI_OVERAGE" | "AUTO_AI_UPGRADE" | "ALLOWED_ORIGINS" | "APP_URL" | "SMTP_HOST" | "SMTP_PORT" | "SMTP_USER" | "SMTP_FROM" | "LEAD_TO" | "SUPABASE_DATA_OPERATIONS_ENABLED" | "GOOGLE_DRIVE_DATA_OPERATIONS_ENABLED" | "BACKUP_JOBS_ENABLED" | "TURNSTILE_ALLOWED_HOSTNAMES" | "JWT_SECRET" | "MFA_ENCRYPTION_KEY" | "TURNSTILE_SECRET">> {}
}
