/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=CloudflareBindings cloudflare/workers/api/src/worker-configuration.d.ts` (hash: eeb92ed5bfe3ac53438c1d4f6083bdac)
interface __BaseEnv_CloudflareBindings {
	KV: KVNamespace;
	FILES: R2Bucket;
	MEDIA: R2Bucket;
	DB: D1Database;
	PUBLIC_API_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	APP_ENV: "preview" | "production";
	ALLOWED_ORIGINS: "https://avyron.ro,https://www.avyron.ro,https://app.avyron.ro,https://codex-prelaunch-improvements-2026-08-23-avyrontech.avyrontech.workers.dev,https://avyrontech.lovable.app,http://localhost:8080" | "https://avyron.ro,https://www.avyron.ro,https://app.avyron.ro,https://avyrontech.lovable.app,https://id-preview--3432ba2d-bd12-41f5-9dc2-a3e04fe788d0.lovable.app,https://3432ba2d-bd12-41f5-9dc2-a3e04fe788d0.lovableproject.com,http://localhost:8080";
	APP_URL: "https://codex-prelaunch-improvements-2026-08-23-avyrontech.avyrontech.workers.dev" | "https://avyron.ro";
	SMTP_HOST: "smtp.mx.cloudflare.net";
	SMTP_PORT: "465";
	SMTP_USER: "api_token";
	SMTP_FROM: "contact@avyron.ro";
	LEAD_TO: "avyrontech@gmail.com";
	TURNSTILE_ALLOWED_HOSTNAMES: "app.avyron.ro,*.avyrontech.workers.dev,avyrontech.lovable.app,localhost" | "avyron.ro,www.avyron.ro,app.avyron.ro,avyrontech.pages.dev,*.avyrontech.pages.dev,*.avyrontech.workers.dev,avyrontech.lovable.app,localhost";
	JWT_SECRET: string;
	TURNSTILE_SECRET?: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface PreviewEnv {
		KV: KVNamespace;
		FILES: R2Bucket;
		MEDIA: R2Bucket;
		DB: D1Database;
		PUBLIC_API_RATE_LIMITER: RateLimit;
		ASSETS: Fetcher;
		APP_ENV: "preview";
		ALLOWED_ORIGINS: "https://avyron.ro,https://www.avyron.ro,https://app.avyron.ro,https://codex-prelaunch-improvements-2026-08-23-avyrontech.avyrontech.workers.dev,https://avyrontech.lovable.app,http://localhost:8080";
		APP_URL: "https://codex-prelaunch-improvements-2026-08-23-avyrontech.avyrontech.workers.dev";
		SMTP_HOST: "smtp.mx.cloudflare.net";
		SMTP_PORT: "465";
		SMTP_USER: "api_token";
		SMTP_FROM: "contact@avyron.ro";
		LEAD_TO: "avyrontech@gmail.com";
		TURNSTILE_ALLOWED_HOSTNAMES: "app.avyron.ro,*.avyrontech.workers.dev,avyrontech.lovable.app,localhost";
		JWT_SECRET: string;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "ALLOWED_ORIGINS" | "APP_URL" | "SMTP_HOST" | "SMTP_PORT" | "SMTP_USER" | "SMTP_FROM" | "LEAD_TO" | "TURNSTILE_ALLOWED_HOSTNAMES" | "JWT_SECRET" | "TURNSTILE_SECRET">> {}
}
